//! Embedded donor element for learning a skill on a hero whose ActiveEffects
//! array is empty (nothing to clone).
//!
//! A single `CharacterStateSaveGameData_ActiveGameplayEffect` array element,
//! captured verbatim from a known-good Gothic 1 Remake save (the
//! `Melee_OneHanded` effect). It is appended to the hero's empty ActiveEffects
//! array and its GE class reference (`EffectSpec.Def`) is then retargeted to the
//! desired skill; the game re-derives the effect from that class on load.
//!
//! Ported from the reference editor's `skill_donor.py`
//! (github.com/Xetoxyc/gothic-remake-savegame-editor). Base64-encoded so it
//! ships as source.

use base64::Engine as _;

const DONOR_B64: &str = concat!(
    "CwAAAEVmZmVjdFNwZWMADwAAAFN0cnVjdFByb3BlcnR5AAEAAAATAAAAR2FtZXBsYXlFZmZlY3RTcGVjAAEAAAAaAAAAL1Njcmlw",
    "dC9HYW1lcGxheUFiaWxpdGllcwAAAAAAnxAAAAAEAAAARGVmAA8AAABPYmplY3RQcm9wZXJ0eQAAAAAAQQAAAAA9AAAAL1Njcmlw",
    "dC9BbmdlbHNjcmlwdC5EZWZhdWx0X19HRV9Ta2lsbF9NZWxlZV9PbmVIYW5kZWRfTWFzdGVyABMAAABNb2RpZmllZEF0dHJpYnV0",
    "ZXMADgAAAEFycmF5UHJvcGVydHkAAQAAAA8AAABTdHJ1Y3RQcm9wZXJ0eQABAAAAIAAAAEdhbWVwbGF5RWZmZWN0TW9kaWZpZWRB",
    "dHRyaWJ1dGUAAQAAABoAAAAvU2NyaXB0L0dhbWVwbGF5QWJpbGl0aWVzAAAAAAAEAAAAAAAAAAAbAAAAQ2FwdHVyZWRSZWxldmFu",
    "dEF0dHJpYnV0ZXMADwAAAFN0cnVjdFByb3BlcnR5AAEAAAAsAAAAR2FtZXBsYXlFZmZlY3RBdHRyaWJ1dGVDYXB0dXJlU3BlY0Nv",
    "bnRhaW5lcgABAAAAGgAAAC9TY3JpcHQvR2FtZXBsYXlBYmlsaXRpZXMAAAAAAHQBAAAAEQAAAFNvdXJjZUF0dHJpYnV0ZXMADgAA",
    "AEFycmF5UHJvcGVydHkAAQAAAA8AAABTdHJ1Y3RQcm9wZXJ0eQABAAAAIwAAAEdhbWVwbGF5RWZmZWN0QXR0cmlidXRlQ2FwdHVy",
    "ZVNwZWMAAQAAABoAAAAvU2NyaXB0L0dhbWVwbGF5QWJpbGl0aWVzAAAAAAAEAAAAAAAAAAARAAAAVGFyZ2V0QXR0cmlidXRlcwAO",
    "AAAAQXJyYXlQcm9wZXJ0eQABAAAADwAAAFN0cnVjdFByb3BlcnR5AAEAAAAjAAAAR2FtZXBsYXlFZmZlY3RBdHRyaWJ1dGVDYXB0",
    "dXJlU3BlYwABAAAAGgAAAC9TY3JpcHQvR2FtZXBsYXlBYmlsaXRpZXMAAAAAAAQAAAAAAAAAAB0AAABiSGFzTm9uU25hcHNob3R0",
    "ZWRBdHRyaWJ1dGVzAA0AAABCb29sUHJvcGVydHkAAAAAAAAAAAAABQAAAE5vbmUACQAAAER1cmF0aW9uAA4AAABGbG9hdFByb3Bl",
    "cnR5AAAAAAAEAAAAAAAAgL8HAAAAUGVyaW9kAA4AAABGbG9hdFByb3BlcnR5AAAAAAAEAAAAAAAAAAAWAAAAQ2hhbmNlVG9BcHBs",
    "eVRvVGFyZ2V0AA4AAABGbG9hdFByb3BlcnR5AAAAAAAEAAAAAAAAgD8TAAAAQ2FwdHVyZWRTb3VyY2VUYWdzAA8AAABTdHJ1Y3RQ",
    "cm9wZXJ0eQABAAAAFwAAAFRhZ0NvbnRhaW5lckFnZ3JlZ2F0b3IAAQAAABoAAAAvU2NyaXB0L0dhbWVwbGF5QWJpbGl0aWVzAAAA",
    "AADZBAAAABIAAABDYXB0dXJlZEFjdG9yVGFncwAPAAAAU3RydWN0UHJvcGVydHkAAQAAABUAAABHYW1lcGxheVRhZ0NvbnRhaW5l",
    "cgABAAAAFQAAAC9TY3JpcHQvR2FtZXBsYXlUYWdzAAAAAABjAwAACCAAAAALAAAAR3VpbGQuTm9uZQAOAAAAU3BlY2llcy5IdW1h",
    "bgARAAAAQ2hhcmFjdGVyLlBsYXllcgAUAAAAQ2hhcmFjdGVyLkNhbi5CbGVlZAAoAAAAQ2hhcmFjdGVyLkNhbi5SZWFjdFRvRm9y",
    "Y2VkQ29udmVyc2F0aW9uABwAAABTa2lsbC5Mb2NrcGlja2luZy5VbnRyYWluZWQAHgAAAFNraWxsLlBpY2twb2NrZXRpbmcuVW50",
    "cmFpbmVkABcAAABTa2lsbC5PcmNpc2guVW50cmFpbmVkABsAAABTa2lsbC5SYW5nZWQuQm93LlVudHJhaW5lZAAgAAAAU2tpbGwu",
    "UmFuZ2VkLkNyb3NzYm93LlVudHJhaW5lZAAcAAAAU2tpbGwuTWFnZS5DaXJjbGUuVW50cmFpbmVkABMAAABTa2lsbC5IdW50aW5n",
    "LlNraW4AFAAAAFNraWxsLkh1bnRpbmcuVGVldGgAEgAAAFNraWxsLkh1bnRpbmcuRnVyABMAAABTa2lsbC5IdW50aW5nLkNsYXcA",
    "HgAAAFNraWxsLk1lbGVlLk9uZUhhbmRlZC5UcmFpbmVkABkAAABTa2lsbC5BY3JvYmF0aWNzLlRyYWluZWQAFAAAAFN0YXRlLlJp",
    "ZGluZ0Jsb2NrZWQAEAAAAFVJLk1hcC5JblJlZ2lvbgAPAAAAU3RhdGUuR3JvdW5kZWQAEwAAAFN0YXRlLkNvbnZlcnNhdGlvbgAa",
    "AAAAU3RhdGUuSWdub3JlTW92ZW1lbnRJbnB1dAASAAAAQmxvY2suQWN0aW9uLkp1bXAAGQAAAFN0YXRlLk5vSW5wdXQuQ29udHJv",
    "bGxlcgAZAAAAU3RhdGUuQmxvY2tBYmlsaXR5QXR0YWNrABYAAABTdGF0ZS5QYXJ0T2ZDaW5lbWF0aWMAGQAAAFN0YXRlLkNvbnZl",
    "cnNhdGlvbi5SZWFkeQAaAAAAU3RhdGUuQ29udmVyc2F0aW9uLkFjdGluZwAYAAAAU3RhdGUuTWVudS5Db252ZXJzYXRpb24AGQAA",
    "AFN0YXRlLlBlcmNlcHRpb25zLklnbm9yZQAdAAAAU3RhdGUuUGVyY2VwdGlvbnMuR2V0SWdub3JlZAATAAAAU3RhdGUuSW52dWxu",
    "ZXJhYmxlABEAAABDYXB0dXJlZFNwZWNUYWdzAA8AAABTdHJ1Y3RQcm9wZXJ0eQABAAAAFQAAAEdhbWVwbGF5VGFnQ29udGFpbmVy",
    "AAEAAAAVAAAAL1NjcmlwdC9HYW1lcGxheVRhZ3MAAAAAAC0AAAAIAgAAAA4AAABHRS5QZXJzaXN0ZW50ABMAAABHRS5Ta2lsbC5P",
    "bmVIYW5kZWQACwAAAFNjb3BlZFRhZ3MADwAAAFN0cnVjdFByb3BlcnR5AAEAAAAVAAAAR2FtZXBsYXlUYWdDb250YWluZXIAAQAA",
    "ABUAAAAvU2NyaXB0L0dhbWVwbGF5VGFncwAAAAAABAAAAAgAAAAABQAAAE5vbmUAEwAAAENhcHR1cmVkVGFyZ2V0VGFncwAPAAAA",
    "U3RydWN0UHJvcGVydHkAAQAAABcAAABUYWdDb250YWluZXJBZ2dyZWdhdG9yAAEAAAAaAAAAL1NjcmlwdC9HYW1lcGxheUFiaWxp",
    "dGllcwAAAAAAngMAAAASAAAAQ2FwdHVyZWRBY3RvclRhZ3MADwAAAFN0cnVjdFByb3BlcnR5AAEAAAAVAAAAR2FtZXBsYXlUYWdD",
    "b250YWluZXIAAQAAABUAAAAvU2NyaXB0L0dhbWVwbGF5VGFncwAAAAAAUQIAAAgWAAAADgAAAFNwZWNpZXMuSHVtYW4AFAAAAFN0",
    "YXRlLlJpZGluZ0Jsb2NrZWQAEAAAAFVJLk1hcC5JblJlZ2lvbgAUAAAAU3RhdGUuUmVzdG9yaW5nU2F2ZQAPAAAAU3RhdGUuR3Jv",
    "dW5kZWQAFQAAAEFybW9yTWF0ZXJpYWwuRmFicmljABEAAABDaGFyYWN0ZXIuUGxheWVyABQAAABDaGFyYWN0ZXIuQ2FuLkJsZWVk",
    "ACgAAABDaGFyYWN0ZXIuQ2FuLlJlYWN0VG9Gb3JjZWRDb252ZXJzYXRpb24AHAAAAFNraWxsLkxvY2twaWNraW5nLlVudHJhaW5l",
    "ZAAeAAAAU2tpbGwuUGlja3BvY2tldGluZy5VbnRyYWluZWQAFwAAAFNraWxsLk9yY2lzaC5VbnRyYWluZWQAGwAAAFNraWxsLlJh",
    "bmdlZC5Cb3cuVW50cmFpbmVkACAAAABTa2lsbC5SYW5nZWQuQ3Jvc3Nib3cuVW50cmFpbmVkACIAAABTdGF0ZS5Mb2FkaW5nLkFj",
    "dGl2YXRpbmdBYmlsaXRpZXMAGwAAAEd1aWxkLkh1bWFuLk9sZENhbXAuU2hhZG93AA8AAABDYW1wUm9sZS5HdWFyZAAaAAAAU2tp",
    "bGwuTWFnZS5DaXJjbGUuQW1hdGV1cgATAAAAU2tpbGwuSHVudGluZy5Ta2luABQAAABTa2lsbC5IdW50aW5nLlRlZXRoABIAAABT",
    "a2lsbC5IdW50aW5nLkZ1cgATAAAAU2tpbGwuSHVudGluZy5DbGF3ABEAAABDYXB0dXJlZFNwZWNUYWdzAA8AAABTdHJ1Y3RQcm9w",
    "ZXJ0eQABAAAAFQAAAEdhbWVwbGF5VGFnQ29udGFpbmVyAAEAAAAVAAAAL1NjcmlwdC9HYW1lcGxheVRhZ3MAAAAAAAQAAAAIAAAA",
    "AAsAAABTY29wZWRUYWdzAA8AAABTdHJ1Y3RQcm9wZXJ0eQABAAAAFQAAAEdhbWVwbGF5VGFnQ29udGFpbmVyAAEAAAAVAAAAL1Nj",
    "cmlwdC9HYW1lcGxheVRhZ3MAAAAAAAQAAAAIAAAAAAUAAABOb25lABMAAABEeW5hbWljR3JhbnRlZFRhZ3MADwAAAFN0cnVjdFBy",
    "b3BlcnR5AAEAAAAVAAAAR2FtZXBsYXlUYWdDb250YWluZXIAAQAAABUAAAAvU2NyaXB0L0dhbWVwbGF5VGFncwAAAAAABAAAAAgA",
    "AAAAEQAAAER5bmFtaWNBc3NldFRhZ3MADwAAAFN0cnVjdFByb3BlcnR5AAEAAAAVAAAAR2FtZXBsYXlUYWdDb250YWluZXIAAQAA",
    "ABUAAAAvU2NyaXB0L0dhbWVwbGF5VGFncwAAAAAABAAAAAgAAAAACgAAAE1vZGlmaWVycwAOAAAAQXJyYXlQcm9wZXJ0eQABAAAA",
    "DwAAAFN0cnVjdFByb3BlcnR5AAEAAAANAAAATW9kaWZpZXJTcGVjAAEAAAAaAAAAL1NjcmlwdC9HYW1lcGxheUFiaWxpdGllcwAA",
    "AAAAQwAAAAABAAAAEwAAAEV2YWx1YXRlZE1hZ25pdHVkZQAOAAAARmxvYXRQcm9wZXJ0eQAAAAAABAAAAAAAAKBABQAAAE5vbmUA",
    "CwAAAFN0YWNrQ291bnQADAAAAEludFByb3BlcnR5AAAAAAAEAAAAAAEAAAAhAAAAYkNvbXBsZXRlZFNvdXJjZUF0dHJpYnV0ZUNh",
    "cHR1cmUADQAAAEJvb2xQcm9wZXJ0eQAAAAAAAAAAABAhAAAAYkNvbXBsZXRlZFRhcmdldEF0dHJpYnV0ZUNhcHR1cmUADQAAAEJv",
    "b2xQcm9wZXJ0eQAAAAAAAAAAABAQAAAAYkR1cmF0aW9uTG9ja2VkAA0AAABCb29sUHJvcGVydHkAAAAAAAAAAAAAFAAAAEdyYW50",
    "ZWRBYmlsaXR5U3BlY3MADgAAAEFycmF5UHJvcGVydHkAAQAAAA8AAABTdHJ1Y3RQcm9wZXJ0eQABAAAAFwAAAEdhbWVwbGF5QWJp",
    "bGl0eVNwZWNEZWYAAQAAABoAAAAvU2NyaXB0L0dhbWVwbGF5QWJpbGl0aWVzAAAAAAAEAAAAAAAAAAAOAAAARWZmZWN0Q29udGV4",
    "dAAPAAAAU3RydWN0UHJvcGVydHkAAQAAABwAAABHYW1lcGxheUVmZmVjdENvbnRleHRIYW5kbGUAAQAAABoAAAAvU2NyaXB0L0dh",
    "bWVwbGF5QWJpbGl0aWVzAAAAAAAJAAAAAAUAAABOb25lAAYAAABMZXZlbAAOAAAARmxvYXRQcm9wZXJ0eQAAAAAABAAAAAAAAIA/",
    "BQAAAE5vbmUAGQAAAFNldEJ5Q2FsbGVyVGFnTWFnbml0dWRlcwAMAAAATWFwUHJvcGVydHkAAgAAAA8AAABTdHJ1Y3RQcm9wZXJ0",
    "eQABAAAADAAAAEdhbWVwbGF5VGFnAAEAAAAVAAAAL1NjcmlwdC9HYW1lcGxheVRhZ3MAAAAAAA4AAABGbG9hdFByb3BlcnR5AAAA",
    "AAAIAAAAAAAAAAAAAAAABQAAAE5vbmUA",
);

/// The captured donor element bytes (a single ActiveGameplayEffect array
/// element). Decoded once on first use.
pub fn donor_template() -> Vec<u8> {
    base64::engine::general_purpose::STANDARD
        .decode(DONOR_B64)
        .expect("embedded skill donor template must be valid base64")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn donor_decodes_and_contains_ge_reference() {
        let bytes = donor_template();
        assert!(!bytes.is_empty());
        // The donor carries exactly one GE class reference (its EffectSpec.Def).
        let needle = b"/Script/Angelscript.Default__GE_Skill_Melee_OneHanded_Master";
        assert!(
            bytes.windows(needle.len()).any(|w| w == needle),
            "donor template lost its GE class reference"
        );
    }
}
