-- gore-dump (generated by gore-cli) — do not edit by hand.
-- Live CDO reader. Writes gore_game_data.json (item stats) and gore_loc.json
-- (localized FText names/descriptions, all cultures). Triggered by config.lua
-- on launch and/or the `gore-dump` console command.
local CONFIG = require("config")
local STATS_SCHEMA = require("items")
local LOC = require("loc_targets")
local STATS_OUT = "gore_game_data.json"
local LOC_OUT = "gore_loc.json"
local INTL_CDO = "/Script/Engine.Default__KismetInternationalizationLibrary"

local function log(msg) print("[gore-dump] " .. tostring(msg) .. "\n") end

local function json_escape(s)
  return (s:gsub('[%z\1-\31\\"]', function(c)
    local map = {['"']='\\"', ['\\']='\\\\', ['\n']='\\n', ['\r']='\\r', ['\t']='\\t'}
    return map[c] or string.format('\\u%04x', string.byte(c))
  end))
end

-- ============================ stats dump ============================

-- Encode a read value as JSON, typed by the field. Returns nil when the value
-- is missing or the wrong Lua type (the field is then emitted without a default).
local function value_json(field_type, v)
  if field_type == "bool" then
    if type(v) == "boolean" then return v and "true" or "false" end
    return nil
  end
  if type(v) ~= "number" then return nil end
  -- JSON has no inf/nan; skip non-finite values so the file stays valid JSON
  -- (the field is then emitted without a default -> GUI shows a placeholder).
  if v ~= v or v == math.huge or v == -math.huge then return nil end
  if field_type == "int" or field_type == "enum" then
    return string.format("%d", math.floor(v + 0.5))
  end
  return string.format("%.17g", v) -- float: round-trips a double
end

local function dump_stats()
  local classes = {}
  for _, cls in ipairs(STATS_SCHEMA) do
    local cdo = StaticFindObject("/Script/Angelscript.Default__" .. cls.id)
    if cdo and cdo:IsValid() then
      local fields = {}
      for _, f in ipairs(cls.fields) do
        local ok, raw = pcall(function() return cdo[f.name] end)
        local parts = {
          string.format('"name":"%s"', json_escape(f.name)),
          string.format('"type":"%s"', json_escape(f.type)),
        }
        if f.enum_values then
          local evs = {}
          for _, e in ipairs(f.enum_values) do
            evs[#evs + 1] = string.format('"%s"', json_escape(e))
          end
          parts[#parts + 1] = '"enum_values":[' .. table.concat(evs, ",") .. ']'
        end
        if f.enum_value_ints then
          local ivs = {}
          for _, n in ipairs(f.enum_value_ints) do
            ivs[#ivs + 1] = string.format("%d", n)
          end
          parts[#parts + 1] = '"enum_value_ints":[' .. table.concat(ivs, ",") .. ']'
        end
        local dj = ok and value_json(f.type, raw) or nil
        if dj then parts[#parts + 1] = '"default":' .. dj end
        fields[#fields + 1] = "{" .. table.concat(parts, ",") .. "}"
      end
      classes[#classes + 1] = string.format(
        '"%s":{"fields":[%s]}', json_escape(cls.id), table.concat(fields, ","))
    else
      log("stats: CDO not found (skipped): " .. cls.id)
    end
  end
  local json = '{"classes":{' .. table.concat(classes, ",") .. '}}'
  local fh = io.open(STATS_OUT, "w")
  if fh then
    fh:write(json); fh:close()
    log("stats: wrote " .. tostring(#classes) .. " classes -> " .. STATS_OUT)
  else
    log("stats: FAILED to open " .. STATS_OUT .. " for writing")
  end
  return #classes
end

-- ============================ loc dump =============================

local function intl() return StaticFindObject(INTL_CDO) end

local function to_str(v)
  if type(v) == "string" then return v end
  if v == nil then return nil end
  local ok, s = pcall(function() return v:ToString() end)
  if ok and type(s) == "string" then return s end
  return nil
end

local function current_culture()
  local o = intl(); if not o then return nil end
  local ok, c = pcall(function() return o:GetCurrentCulture() end)
  if ok then return to_str(c) end
  return nil
end

local function set_culture(c)
  local o = intl(); if not o then return false end
  return (pcall(function() o:SetCurrentCulture(c, false) end))
end

-- Best-effort enumerate the cultures the game ships (Game + Additional).
local function discover_cultures()
  local out, o = {}, intl()
  if not o then return out end
  local ok, arr = pcall(function() return o:GetLocalizedCultures(true, false, false, true) end)
  if ok and arr then
    pcall(function()
      arr:ForEach(function(_, elem)
        local s
        local got = pcall(function() s = to_str(elem:get()) end)
        if not got or not s then s = to_str(elem) end
        if type(s) == "string" and s ~= "" then out[#out + 1] = s end
      end)
    end)
  end
  return out
end

local function read_ftext(cdo, field)
  local ok, val = pcall(function() return cdo[field] end)
  if not ok then return nil end
  local s = to_str(val)
  if s and s ~= "" then return s end
  return nil
end

local function resolve_cultures(want)
  if type(want) == "table" then return want end
  return discover_cultures()
end

local function dump_loc(kinds, cultures_want)
  local kindset = {}
  for _, k in ipairs(kinds or {"item", "npc", "knowledge"}) do kindset[k] = true end

  local cultures = resolve_cultures(cultures_want)
  if #cultures == 0 then
    log('loc: no cultures resolved. Set loc.cultures = {"en","de",...} in config.lua. Aborting.')
    return 0
  end
  log("loc: cultures = " .. table.concat(cultures, ", "))

  local targets = {}
  for _, t in ipairs(LOC.targets) do
    if kindset[t.kind] then targets[#targets + 1] = t end
  end
  log("loc: " .. tostring(#targets) .. " targets")

  -- data[id] = {kind=, text={field={culture=str}}}; order keeps output stable.
  local data, order = {}, {}
  local orig = current_culture()

  for _, culture in ipairs(cultures) do
    if not set_culture(culture) then
      log("loc: SetCurrentCulture failed for " .. culture .. " (skipped)")
    else
      for _, t in ipairs(targets) do
        local cdo = StaticFindObject("/Script/Angelscript.Default__" .. t.id)
        if cdo and cdo:IsValid() then
          for _, field in ipairs(LOC.fields_by_kind[t.kind] or {}) do
            local s = read_ftext(cdo, field)
            if s then
              local rec = data[t.id]
              if not rec then rec = {kind = t.kind, text = {}}; data[t.id] = rec; order[#order + 1] = t.id end
              local fmap = rec.text[field]
              if not fmap then fmap = {}; rec.text[field] = fmap end
              fmap[culture] = s
            end
          end
        end
      end
    end
  end

  if orig then set_culture(orig) end

  local parts = {}
  for _, id in ipairs(order) do
    local rec = data[id]
    local fparts = {}
    for field, cmap in pairs(rec.text) do
      local cparts = {}
      for _, culture in ipairs(cultures) do
        if cmap[culture] then
          cparts[#cparts + 1] = string.format('"%s":"%s"', json_escape(culture), json_escape(cmap[culture]))
        end
      end
      fparts[#fparts + 1] = string.format('"%s":{%s}', json_escape(field), table.concat(cparts, ","))
    end
    parts[#parts + 1] = string.format('"%s":{"kind":"%s","text":{%s}}',
      json_escape(id), json_escape(rec.kind), table.concat(fparts, ","))
  end
  local cset = {}
  for _, c in ipairs(cultures) do cset[#cset + 1] = string.format('"%s"', json_escape(c)) end
  local json = string.format('{"cultures":[%s],"entries":{%s}}',
    table.concat(cset, ","), table.concat(parts, ","))

  local fh = io.open(LOC_OUT, "w")
  if fh then
    fh:write(json); fh:close()
    log("loc: wrote " .. tostring(#order) .. " entries -> " .. LOC_OUT)
  else
    log("loc: FAILED to open " .. LOC_OUT .. " for writing")
  end
  return #order
end

-- ====================== console command + auto =====================

-- "all"/empty -> nil (use config default); else split "a,b,c" into a list.
local function parse_csv(s)
  if not s or s == "" or s == "all" then return nil end
  local t = {}
  for w in s:gmatch("[^,]+") do t[#t + 1] = w end
  return t
end

-- `gore-dump <stats|loc|all> [item,npc,knowledge] [en,de,...]`
RegisterConsoleCommandHandler("gore-dump", function(_, Parameters, Ar)
  local function out(m)
    if Ar then pcall(function() Ar:Log(m) end) end
    log(m)
  end
  local sub = string.lower(Parameters[1] or "all")
  if sub == "stats" then
    out("stats: wrote " .. tostring(dump_stats()) .. " classes")
  elseif sub == "loc" then
    local kinds = parse_csv(Parameters[2]) or CONFIG.loc.kinds
    local cultures = parse_csv(Parameters[3]) or CONFIG.loc.cultures
    out("loc: wrote " .. tostring(dump_loc(kinds, cultures)) .. " entries")
  elseif sub == "all" then
    dump_stats()
    dump_loc(CONFIG.loc.kinds, CONFIG.loc.cultures)
    out("all: done")
  else
    out("usage: gore-dump <stats|loc|all> [item,npc,knowledge] [en,de,...]")
  end
  return true
end)

do
  local found = discover_cultures()
  if #found > 0 then log("cultures available: " .. table.concat(found, ", ")) end
end

if CONFIG.auto and CONFIG.auto.enabled then
  log("loaded; auto-dump in " .. tostring(CONFIG.auto.delay_ms)
    .. "ms (console: `gore-dump <stats|loc|all>`)")
  ExecuteWithDelay(CONFIG.auto.delay_ms, function()
    if CONFIG.auto.stats then dump_stats() end
    if CONFIG.auto.loc then dump_loc(CONFIG.loc.kinds, CONFIG.loc.cultures) end
  end)
else
  log("loaded; auto-dump disabled (console: `gore-dump <stats|loc|all>`)")
end
