-- gore-dump (generated by gore-cli) — do not edit by hand.
-- Reads each item CDO's current field values and writes gore_game_data.json,
-- which `gore-cli sync` ingests to give the GUI real default values.
local SCHEMA = require("items")
local OUT_FILE = "gore_game_data.json"
local DELAY_MS = 15000

local function json_escape(s)
  return (s:gsub('[%z\1-\31\\"]', function(c)
    local map = {['"']='\\"', ['\\']='\\\\', ['\n']='\\n', ['\r']='\\r', ['\t']='\\t'}
    return map[c] or string.format('\\u%04x', string.byte(c))
  end))
end

-- Encode a read value as JSON, typed by the field. Returns nil when the value
-- is missing or the wrong Lua type (the field is then emitted without a default).
local function value_json(field_type, v)
  if field_type == "bool" then
    if type(v) == "boolean" then return v and "true" or "false" end
    return nil
  end
  if type(v) ~= "number" then return nil end
  -- JSON has no inf/nan; skip non-finite values so the file stays valid JSON
  -- (the field is then emitted without a default -> GUI shows a placeholder).
  if v ~= v or v == math.huge or v == -math.huge then return nil end
  if field_type == "int" or field_type == "enum" then
    return string.format("%d", math.floor(v + 0.5))
  end
  return string.format("%.17g", v) -- float: round-trips a double
end

local function dump()
  local classes = {}
  for _, cls in ipairs(SCHEMA) do
    local cdo = StaticFindObject("/Script/Angelscript.Default__" .. cls.id)
    if cdo and cdo:IsValid() then
      local fields = {}
      for _, f in ipairs(cls.fields) do
        local ok, raw = pcall(function() return cdo[f.name] end)
        local parts = {
          string.format('"name":"%s"', json_escape(f.name)),
          string.format('"type":"%s"', json_escape(f.type)),
        }
        if f.enum_values then
          local evs = {}
          for _, e in ipairs(f.enum_values) do
            evs[#evs + 1] = string.format('"%s"', json_escape(e))
          end
          parts[#parts + 1] = '"enum_values":[' .. table.concat(evs, ",") .. ']'
        end
        if f.enum_value_ints then
          local ivs = {}
          for _, n in ipairs(f.enum_value_ints) do
            ivs[#ivs + 1] = string.format("%d", n)
          end
          parts[#parts + 1] = '"enum_value_ints":[' .. table.concat(ivs, ",") .. ']'
        end
        local dj = ok and value_json(f.type, raw) or nil
        if dj then parts[#parts + 1] = '"default":' .. dj end
        fields[#fields + 1] = "{" .. table.concat(parts, ",") .. "}"
      end
      classes[#classes + 1] = string.format(
        '"%s":{"fields":[%s]}', json_escape(cls.id), table.concat(fields, ","))
    else
      print("[gore-dump] CDO not found (skipped): " .. cls.id .. "\n")
    end
  end
  local json = '{"classes":{' .. table.concat(classes, ",") .. '}}'
  local fh = io.open(OUT_FILE, "w")
  if fh then
    fh:write(json)
    fh:close()
    print("[gore-dump] wrote " .. tostring(#classes) .. " classes -> " .. OUT_FILE .. "\n")
  else
    print("[gore-dump] FAILED to open " .. OUT_FILE .. " for writing\n")
  end
end

print("[gore-dump] loaded; dumping item CDOs in " .. tostring(DELAY_MS) .. "ms\n")
ExecuteWithDelay(DELAY_MS, dump)
