-- gore-dump (generated by gore-cli) — do not edit by hand.
-- Live CDO reader. Writes gore_game_data.json (item stats) and gore_loc.json
-- (localized FText names/descriptions, all cultures). Triggered by config.lua
-- on launch and/or the `gore-dump` console command.
local CONFIG = require("config")
local STATS_SCHEMA = require("items")
local LOC = require("loc_targets")
local STATS_OUT = "gore_game_data.json"
local LOC_OUT = "gore_loc.json"
local INTL_CDO = "/Script/Engine.Default__KismetInternationalizationLibrary"

local function log(msg) print("[gore-dump] " .. tostring(msg) .. "\n") end

local function json_escape(s)
  return (s:gsub('[%z\1-\31\\"]', function(c)
    local map = {['"']='\\"', ['\\']='\\\\', ['\n']='\\n', ['\r']='\\r', ['\t']='\\t'}
    return map[c] or string.format('\\u%04x', string.byte(c))
  end))
end

-- ============================ stats dump ============================

-- Encode a read value as JSON, typed by the field. Returns nil when the value
-- is missing or the wrong Lua type (the field is then emitted without a default).
local function value_json(field_type, v)
  if field_type == "bool" then
    if type(v) == "boolean" then return v and "true" or "false" end
    return nil
  end
  if type(v) ~= "number" then return nil end
  -- JSON has no inf/nan; skip non-finite values so the file stays valid JSON
  -- (the field is then emitted without a default -> GUI shows a placeholder).
  if v ~= v or v == math.huge or v == -math.huge then return nil end
  if field_type == "int" or field_type == "enum" then
    return string.format("%d", math.floor(v + 0.5))
  end
  return string.format("%.17g", v) -- float: round-trips a double
end

local function dump_stats()
  local classes = {}
  for _, cls in ipairs(STATS_SCHEMA) do
    local cdo = StaticFindObject("/Script/Angelscript.Default__" .. cls.id)
    if cdo and cdo:IsValid() then
      local fields = {}
      for _, f in ipairs(cls.fields) do
        local ok, raw = pcall(function() return cdo[f.name] end)
        local parts = {
          string.format('"name":"%s"', json_escape(f.name)),
          string.format('"type":"%s"', json_escape(f.type)),
        }
        if f.enum_values then
          local evs = {}
          for _, e in ipairs(f.enum_values) do
            evs[#evs + 1] = string.format('"%s"', json_escape(e))
          end
          parts[#parts + 1] = '"enum_values":[' .. table.concat(evs, ",") .. ']'
        end
        if f.enum_value_ints then
          local ivs = {}
          for _, n in ipairs(f.enum_value_ints) do
            ivs[#ivs + 1] = string.format("%d", n)
          end
          parts[#parts + 1] = '"enum_value_ints":[' .. table.concat(ivs, ",") .. ']'
        end
        local dj = ok and value_json(f.type, raw) or nil
        if dj then parts[#parts + 1] = '"default":' .. dj end
        fields[#fields + 1] = "{" .. table.concat(parts, ",") .. "}"
      end
      classes[#classes + 1] = string.format(
        '"%s":{"fields":[%s]}', json_escape(cls.id), table.concat(fields, ","))
    else
      log("stats: CDO not found (skipped): " .. cls.id)
    end
  end
  local json = '{"classes":{' .. table.concat(classes, ",") .. '}}'
  local fh = io.open(STATS_OUT, "w")
  if fh then
    fh:write(json); fh:close()
    log("stats: wrote " .. tostring(#classes) .. " classes -> " .. STATS_OUT)
  else
    log("stats: FAILED to open " .. STATS_OUT .. " for writing")
  end
  return #classes
end

-- ============================ loc dump =============================

local function intl() return StaticFindObject(INTL_CDO) end

local function to_str(v)
  if type(v) == "string" then return v end
  if v == nil then return nil end
  local ok, s = pcall(function() return v:ToString() end)
  if ok and type(s) == "string" then return s end
  return nil
end

-- The game's text (Alkimia loc) follows the engine *language*, not the culture
-- (a run showed culture=en-US while text rendered German). Read/write language
-- first; fall back to culture for older builds.
local function current_culture()
  local o = intl(); if not o then return nil end
  for _, fn in ipairs({"GetCurrentLanguage", "GetCurrentCulture"}) do
    local ok, c = pcall(function() return o[fn](o) end)
    if ok then
      local s = to_str(c)
      if s and s ~= "" then return s end
    end
  end
  return nil
end

local function set_culture(c)
  local o = intl(); if not o then return false end
  -- Fire every lever; whichever the build honors takes effect (don't stop at
  -- the first that merely doesn't error — it may be a silent no-op).
  local any = false
  for _, fn in ipairs({"SetCurrentLanguageAndLocale", "SetCurrentLanguage", "SetCurrentCulture"}) do
    if pcall(function() o[fn](o, c, false) end) then any = true end
  end
  return any
end

-- Best-effort enumerate the cultures the game ships (Game + Additional).
local function discover_cultures()
  local out, o = {}, intl()
  if not o then return out end
  local ok, arr = pcall(function() return o:GetLocalizedCultures(true, false, false, true) end)
  if ok and arr then
    pcall(function()
      arr:ForEach(function(_, elem)
        local s
        local got = pcall(function() s = to_str(elem:get()) end)
        if not got or not s then s = to_str(elem) end
        if type(s) == "string" and s ~= "" then out[#out + 1] = s end
      end)
    end)
  end
  return out
end

local function read_ftext(cdo, field)
  local ok, val = pcall(function() return cdo[field] end)
  if not ok then return nil end
  local s = to_str(val)
  if s and s ~= "" then return s end
  return nil
end

-- Broad UE culture codes to probe when cultures = "all". GetLocalizedCultures'
-- TArray return is unreliable through UE4SS, so we discover by switching to each
-- candidate and checking it sticks + yields distinct text.
local CANDIDATE_CULTURES = {
  "en", "de", "fr", "it", "es", "es-419", "pl", "ru", "pt-BR", "pt-PT",
  "zh-Hans", "zh-Hant", "ja", "ko", "tr", "uk", "cs", "hu", "nl",
}

local function culture_eq(a, b)
  if not a or not b then return false end
  a, b = string.lower(a), string.lower(b)
  return a == b or string.sub(a, 1, #b) == b or string.sub(b, 1, #a) == a
end

-- Signature of a culture = the m_Name of the first few item CDOs. Cultures that
-- fall back to the same text (i.e. no real translation) share a signature and
-- collapse to the first; genuine translations differ and are kept.
local function culture_signature()
  local s, n = {}, 0
  for _, t in ipairs(LOC.targets) do
    if t.kind == "item" then
      local cdo = StaticFindObject("/Script/Angelscript.Default__" .. t.id)
      if cdo and cdo:IsValid() then
        local v = read_ftext(cdo, "m_Name")
        if v then s[#s + 1] = v; n = n + 1 end
      end
      if n >= 8 then break end
    end
  end
  return table.concat(s, "|")
end

local function probe_cultures()
  local orig = current_culture()
  local seen, out = {}, {}
  for _, c in ipairs(CANDIDATE_CULTURES) do
    if set_culture(c) and culture_eq(current_culture(), c) then
      local sig = culture_signature()
      if sig ~= "" and not seen[sig] then
        seen[sig] = c
        out[#out + 1] = c
      end
    end
  end
  if orig then set_culture(orig) end
  return out
end

local function resolve_cultures(want)
  if type(want) == "table" then return want end
  local d = discover_cultures()
  if #d == 0 then d = probe_cultures() end
  return d
end

local function dump_loc(kinds, cultures_want)
  local kindset = {}
  for _, k in ipairs(kinds or {"item", "npc", "knowledge"}) do kindset[k] = true end

  local cultures = resolve_cultures(cultures_want)
  if #cultures == 0 then
    log('loc: no cultures resolved. Set loc.cultures = {"en","de",...} in config.lua. Aborting.')
    return 0
  end
  log("loc: cultures = " .. table.concat(cultures, ", "))

  local targets = {}
  for _, t in ipairs(LOC.targets) do
    if kindset[t.kind] then targets[#targets + 1] = t end
  end
  log("loc: " .. tostring(#targets) .. " targets")

  -- data[id] = {kind=, text={field={culture=str}}}; order keeps output stable.
  local data, order = {}, {}
  local orig = current_culture()

  for _, culture in ipairs(cultures) do
    if not set_culture(culture) then
      log("loc: SetCurrentCulture failed for " .. culture .. " (skipped)")
    else
      for _, t in ipairs(targets) do
        local cdo = StaticFindObject("/Script/Angelscript.Default__" .. t.id)
        if cdo and cdo:IsValid() then
          for _, field in ipairs(LOC.fields_by_kind[t.kind] or {}) do
            local s = read_ftext(cdo, field)
            if s then
              local rec = data[t.id]
              if not rec then rec = {kind = t.kind, text = {}}; data[t.id] = rec; order[#order + 1] = t.id end
              local fmap = rec.text[field]
              if not fmap then fmap = {}; rec.text[field] = fmap end
              fmap[culture] = s
            end
          end
        end
      end
    end
  end

  if orig then set_culture(orig) end

  local parts = {}
  for _, id in ipairs(order) do
    local rec = data[id]
    local fparts = {}
    for field, cmap in pairs(rec.text) do
      local cparts = {}
      for _, culture in ipairs(cultures) do
        if cmap[culture] then
          cparts[#cparts + 1] = string.format('"%s":"%s"', json_escape(culture), json_escape(cmap[culture]))
        end
      end
      fparts[#fparts + 1] = string.format('"%s":{%s}', json_escape(field), table.concat(cparts, ","))
    end
    parts[#parts + 1] = string.format('"%s":{"kind":"%s","text":{%s}}',
      json_escape(id), json_escape(rec.kind), table.concat(fparts, ","))
  end
  local cset = {}
  for _, c in ipairs(cultures) do cset[#cset + 1] = string.format('"%s"', json_escape(c)) end
  local json = string.format('{"cultures":[%s],"entries":{%s}}',
    table.concat(cset, ","), table.concat(parts, ","))

  local fh = io.open(LOC_OUT, "w")
  if fh then
    fh:write(json); fh:close()
    log("loc: wrote " .. tostring(#order) .. " entries -> " .. LOC_OUT)
  else
    log("loc: FAILED to open " .. LOC_OUT .. " for writing")
  end
  return #order
end

-- ====================== console command + auto =====================

-- "all"/empty -> nil (use config default); else split "a,b,c" into a list.
local function parse_csv(s)
  if not s or s == "" or s == "all" then return nil end
  local t = {}
  for w in s:gmatch("[^,]+") do t[#t + 1] = w end
  return t
end

-- `gore-dump <stats|loc|all> [item,npc,knowledge] [en,de,...]`
RegisterConsoleCommandHandler("gore-dump", function(_, Parameters, Ar)
  local function out(m)
    if Ar then pcall(function() Ar:Log(m) end) end
    log(m)
  end
  local sub = string.lower(Parameters[1] or "all")
  if sub == "stats" then
    out("stats: wrote " .. tostring(dump_stats()) .. " classes")
  elseif sub == "loc" then
    local kinds = parse_csv(Parameters[2]) or CONFIG.loc.kinds
    local cultures = parse_csv(Parameters[3]) or CONFIG.loc.cultures
    out("loc: wrote " .. tostring(dump_loc(kinds, cultures)) .. " entries")
  elseif sub == "all" then
    dump_stats()
    dump_loc(CONFIG.loc.kinds, CONFIG.loc.cultures)
    out("all: done")
  else
    out("usage: gore-dump <stats|loc|all> [item,npc,knowledge] [en,de,...]")
  end
  return true
end)

do
  local o = intl()
  if o then
    local function try(fn)
      local ok, v = pcall(function() return o[fn](o) end)
      return ok and to_str(v) or "?"
    end
    log("language = " .. try("GetCurrentLanguage") .. ", culture = " .. try("GetCurrentCulture"))
  end
  local found = discover_cultures()
  if #found > 0 then log("GetLocalizedCultures: " .. table.concat(found, ", ")) end
end

if CONFIG.auto and CONFIG.auto.enabled then
  log("loaded; auto-dump in " .. tostring(CONFIG.auto.delay_ms)
    .. "ms (console: `gore-dump <stats|loc|all>`)")
  ExecuteWithDelay(CONFIG.auto.delay_ms, function()
    if CONFIG.auto.stats then dump_stats() end
    if CONFIG.auto.loc then dump_loc(CONFIG.loc.kinds, CONFIG.loc.cultures) end
  end)
else
  log("loaded; auto-dump disabled (console: `gore-dump <stats|loc|all>`)")
end
