name: gore_manager
description: "gore-manager: Gothic 1 Remake Mod Manager"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  ffi: ^2.1.4
  file_selector: ^1.0.3
  flutter_riverpod: ^3.2.1
  path: ^1.9.0
  state_notifier: ^1.0.0
  window_manager: ^0.5.1
  auto_updater:
    git:
      url: https://github.com/dh0er/auto_updater.git
      path: packages/auto_updater
      ref: swiftpm-support

dependency_overrides:
  auto_updater_windows:
    git:
      url: https://github.com/dh0er/auto_updater.git
      ref: swiftpm-support
      path: packages/auto_updater_windows
  auto_updater_macos:
    git:
      url: https://github.com/dh0er/auto_updater.git
      ref: swiftpm-support
      path: packages/auto_updater_macos
  auto_updater_platform_interface:
    git:
      url: https://github.com/dh0er/auto_updater.git
      ref: swiftpm-support
      path: packages/auto_updater_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
