-- gore-dump (generated by gore) — do not edit by hand.
-- Reads each item CDO's current field values and writes gore_game_data.json,
-- which `gore sync` ingests to give the GUI real default values.
-- Also recovers the FMOD bank encryption key (gore_fmod_key.json) so gore can
-- open the game's encrypted .bank audio files.
local SCHEMA = require("items")
local OUT_FILE = "gore_game_data.json"
local FMOD_OUT_FILE = "gore_fmod_key.json"
local DELAY_MS = 15000

local function json_escape(s)
  return (s:gsub('[%z\1-\31\\"]', function(c)
    local map = {['"']='\\"', ['\\']='\\\\', ['\n']='\\n', ['\r']='\\r', ['\t']='\\t'}
    return map[c] or string.format('\\u%04x', string.byte(c))
  end))
end

-- Encode a read value as JSON, typed by the field. Returns nil when the value
-- is missing or the wrong Lua type (the field is then emitted without a default).
local function value_json(field_type, v)
  if field_type == "bool" then
    if type(v) == "boolean" then return v and "true" or "false" end
    return nil
  end
  if type(v) ~= "number" then return nil end
  -- JSON has no inf/nan; skip non-finite values so the file stays valid JSON
  -- (the field is then emitted without a default -> GUI shows a placeholder).
  if v ~= v or v == math.huge or v == -math.huge then return nil end
  if field_type == "int" or field_type == "enum" then
    return string.format("%d", math.floor(v + 0.5))
  end
  return string.format("%.17g", v) -- float: round-trips a double
end

local function dump()
  local classes = {}
  for _, cls in ipairs(SCHEMA) do
    local cdo = StaticFindObject("/Script/Angelscript.Default__" .. cls.id)
    if cdo and cdo:IsValid() then
      local fields = {}
      for _, f in ipairs(cls.fields) do
        local ok, raw = pcall(function() return cdo[f.name] end)
        local parts = {
          string.format('"name":"%s"', json_escape(f.name)),
          string.format('"type":"%s"', json_escape(f.type)),
        }
        if f.enum_values then
          local evs = {}
          for _, e in ipairs(f.enum_values) do
            evs[#evs + 1] = string.format('"%s"', json_escape(e))
          end
          parts[#parts + 1] = '"enum_values":[' .. table.concat(evs, ",") .. ']'
        end
        if f.enum_value_ints then
          local ivs = {}
          for _, n in ipairs(f.enum_value_ints) do
            ivs[#ivs + 1] = string.format("%d", n)
          end
          parts[#parts + 1] = '"enum_value_ints":[' .. table.concat(ivs, ",") .. ']'
        end
        local dj = ok and value_json(f.type, raw) or nil
        if dj then parts[#parts + 1] = '"default":' .. dj end
        fields[#fields + 1] = "{" .. table.concat(parts, ",") .. "}"
      end
      classes[#classes + 1] = string.format(
        '"%s":{"fields":[%s]}', json_escape(cls.id), table.concat(fields, ","))
    else
      print("[gore-dump] CDO not found (skipped): " .. cls.id .. "\n")
    end
  end
  local json = '{"classes":{' .. table.concat(classes, ",") .. '}}'
  local fh = io.open(OUT_FILE, "w")
  if fh then
    fh:write(json)
    fh:close()
    print("[gore-dump] wrote " .. tostring(#classes) .. " classes -> " .. OUT_FILE .. "\n")
  else
    print("[gore-dump] FAILED to open " .. OUT_FILE .. " for writing\n")
  end
end

-- Read a string UPROPERTY off an object, returning nil if absent. UE4SS exposes
-- an FStrProperty as an FString userdata (not a Lua string), so call :ToString().
local function read_str(obj, name)
  local ok, v = pcall(function() return obj[name] end)
  if not ok then return nil end
  if type(v) == "string" then return v end
  if type(v) == "userdata" then
    local ok2, s = pcall(function() return v:ToString() end)
    if ok2 and type(s) == "string" then return s end
  end
  return nil
end

-- Recover the FMOD Studio bank encryption key from the live UFMODSettings CDO.
-- The UE FMOD plugin loads the bank key (a config FString) into its default
-- object at startup; reading it yields the key the runtime feeds to FMOD, which
-- is what gore needs to decrypt/re-encrypt the .bank files. The property name
-- varies by plugin fork (this game uses `StudioBankKey`), so try the known
-- candidates. Written to a separate file, independent of the item dump.
local function dump_fmod_key()
  local cdo = StaticFindObject("/Script/FMODStudio.Default__FMODSettings")
  local found = cdo and cdo:IsValid()
  local parts = { string.format('"found":%s', found and "true" or "false") }
  if found then
    local key = read_str(cdo, "StudioBankKey") or read_str(cdo, "EncryptionKey")
    if key ~= nil then
      parts[#parts + 1] = string.format('"encryption_key":"%s"', json_escape(key))
    end
    -- MasterBankName confirms we read the right settings object (expect "Master").
    local mb = read_str(cdo, "MasterBankName")
    if mb ~= nil then
      parts[#parts + 1] = string.format('"master_bank_name":"%s"', json_escape(mb))
    end
  else
    print("[gore-dump] FMODSettings CDO not found (FMOD key skipped)\n")
  end
  local json = "{" .. table.concat(parts, ",") .. "}"
  local fh = io.open(FMOD_OUT_FILE, "w")
  if fh then
    fh:write(json)
    fh:close()
    print("[gore-dump] wrote FMOD key info -> " .. FMOD_OUT_FILE .. "\n")
  else
    print("[gore-dump] FAILED to open " .. FMOD_OUT_FILE .. " for writing\n")
  end
end

print("[gore-dump] loaded; dumping item CDOs + FMOD key in " .. tostring(DELAY_MS) .. "ms\n")
ExecuteWithDelay(DELAY_MS, function()
  dump()
  dump_fmod_key()
end)
