//! `gore-cli dump-mod` — generate the **gore-dump** UE4SS Lua mod.
//!
//! The mod reads live CDO values in-game and writes two files:
//!   * `gore_game_data.json` — item stat defaults (the shape `gore-cli sync`
//!     ingests), giving the GUI the real per-field defaults only the running
//!     game knows.
//!   * `gore_loc.json` — localized `FText` names/descriptions for items, NPCs
//!     and dialog knowledge, in every shipped culture. Consumed by both
//!     gore-save and gore-mod to show real in-game names.
//!
//! Both dumps run against bundled allow-lists (`items.lua`, `loc_targets.lua`)
//! via the proven `StaticFindObject(Default__<id>)[field]` path — no fragile
//! reflection. They are triggered by `config.lua` on launch and/or the
//! `gore-dump` UE4SS console command. New items/fields from a game patch need
//! the catalogs/model regenerated before they appear here.

use anyhow::{Context, Result};
use gore_core::{catalog::parse_catalog, gen::lua_escape};
use serde::Deserialize;
use std::{fs, path::PathBuf};

use crate::cmd::gui_model::GuiModel;

/// FText field names read per target kind. These are inherited from C++ base
/// classes (`UGothicObjectDefinition::m_Name`, `UG1RDialogTopic::Caption`, ...),
/// so they are read by name through the inheritance chain — `ForEachProperty`
/// only sees leaf-declared props and would miss them.
const ITEM_FIELDS: &[&str] = &["m_Name", "m_Description"];
const NPC_FIELDS: &[&str] = &["m_Name", "m_CharacterName"];
const KNOWLEDGE_FIELDS: &[&str] = &["Caption", "InitialForcedLine", "m_Name"];

/// Default `config.lua`. Written fresh on every generation; users tune the copy
/// deployed into the game's `Mods/gore-dump/Scripts/` directory.
const CONFIG_LUA: &str = r#"-- gore-dump config — safe to edit your deployed copy.
return {
  -- Auto-dump when the game finishes loading (main menu is enough).
  auto = {
    enabled  = true,
    delay_ms = 15000,
    stats    = true,   -- write gore_game_data.json (item stat defaults)
    loc      = true,   -- write gore_loc.json (localized names, all cultures)
  },
  -- Loc dump scope.
  loc = {
    kinds    = {"item", "npc", "knowledge"},
    -- "all" = every culture the game ships (auto-discovered). Or pin a list,
    -- e.g. {"en", "de", "fr"} — useful if culture auto-switch misbehaves.
    cultures = "all",
  },
}
"#;

/// Fixed runtime. Reads CDO values against the bundled `items.lua` (stats) and
/// `loc_targets.lua` (localized text) schemas. See module docs.
const MAIN_LUA: &str = r#"-- gore-dump (generated by gore-cli) — do not edit by hand.
-- Live CDO reader. Writes gore_game_data.json (item stats) and gore_loc.json
-- (localized FText names/descriptions, all cultures). Triggered by config.lua
-- on launch and/or the `gore-dump` console command.
local CONFIG = require("config")
local STATS_SCHEMA = require("items")
local LOC = require("loc_targets")
local STATS_OUT = "gore_game_data.json"
local LOC_OUT = "gore_loc.json"
local INTL_CDO = "/Script/Engine.Default__KismetInternationalizationLibrary"

local function log(msg) print("[gore-dump] " .. tostring(msg) .. "\n") end

local function json_escape(s)
  return (s:gsub('[%z\1-\31\\"]', function(c)
    local map = {['"']='\\"', ['\\']='\\\\', ['\n']='\\n', ['\r']='\\r', ['\t']='\\t'}
    return map[c] or string.format('\\u%04x', string.byte(c))
  end))
end

-- ============================ stats dump ============================

-- Encode a read value as JSON, typed by the field. Returns nil when the value
-- is missing or the wrong Lua type (the field is then emitted without a default).
local function value_json(field_type, v)
  if field_type == "bool" then
    if type(v) == "boolean" then return v and "true" or "false" end
    return nil
  end
  if type(v) ~= "number" then return nil end
  -- JSON has no inf/nan; skip non-finite values so the file stays valid JSON
  -- (the field is then emitted without a default -> GUI shows a placeholder).
  if v ~= v or v == math.huge or v == -math.huge then return nil end
  if field_type == "int" or field_type == "enum" then
    return string.format("%d", math.floor(v + 0.5))
  end
  return string.format("%.17g", v) -- float: round-trips a double
end

local function dump_stats()
  local classes = {}
  for _, cls in ipairs(STATS_SCHEMA) do
    local cdo = StaticFindObject("/Script/Angelscript.Default__" .. cls.id)
    if cdo and cdo:IsValid() then
      local fields = {}
      for _, f in ipairs(cls.fields) do
        local ok, raw = pcall(function() return cdo[f.name] end)
        local parts = {
          string.format('"name":"%s"', json_escape(f.name)),
          string.format('"type":"%s"', json_escape(f.type)),
        }
        if f.enum_values then
          local evs = {}
          for _, e in ipairs(f.enum_values) do
            evs[#evs + 1] = string.format('"%s"', json_escape(e))
          end
          parts[#parts + 1] = '"enum_values":[' .. table.concat(evs, ",") .. ']'
        end
        if f.enum_value_ints then
          local ivs = {}
          for _, n in ipairs(f.enum_value_ints) do
            ivs[#ivs + 1] = string.format("%d", n)
          end
          parts[#parts + 1] = '"enum_value_ints":[' .. table.concat(ivs, ",") .. ']'
        end
        local dj = ok and value_json(f.type, raw) or nil
        if dj then parts[#parts + 1] = '"default":' .. dj end
        fields[#fields + 1] = "{" .. table.concat(parts, ",") .. "}"
      end
      classes[#classes + 1] = string.format(
        '"%s":{"fields":[%s]}', json_escape(cls.id), table.concat(fields, ","))
    else
      log("stats: CDO not found (skipped): " .. cls.id)
    end
  end
  local json = '{"classes":{' .. table.concat(classes, ",") .. '}}'
  local fh = io.open(STATS_OUT, "w")
  if fh then
    fh:write(json); fh:close()
    log("stats: wrote " .. tostring(#classes) .. " classes -> " .. STATS_OUT)
  else
    log("stats: FAILED to open " .. STATS_OUT .. " for writing")
  end
  return #classes
end

-- ============================ loc dump =============================

local function intl() return StaticFindObject(INTL_CDO) end

local function to_str(v)
  if type(v) == "string" then return v end
  if v == nil then return nil end
  local ok, s = pcall(function() return v:ToString() end)
  if ok and type(s) == "string" then return s end
  return nil
end

local function current_culture()
  local o = intl(); if not o then return nil end
  local ok, c = pcall(function() return o:GetCurrentCulture() end)
  if ok then return to_str(c) end
  return nil
end

local function set_culture(c)
  local o = intl(); if not o then return false end
  return (pcall(function() o:SetCurrentCulture(c, false) end))
end

-- Best-effort enumerate the cultures the game ships (Game + Additional).
local function discover_cultures()
  local out, o = {}, intl()
  if not o then return out end
  local ok, arr = pcall(function() return o:GetLocalizedCultures(true, false, false, true) end)
  if ok and arr then
    pcall(function()
      arr:ForEach(function(_, elem)
        local s
        local got = pcall(function() s = to_str(elem:get()) end)
        if not got or not s then s = to_str(elem) end
        if type(s) == "string" and s ~= "" then out[#out + 1] = s end
      end)
    end)
  end
  return out
end

local function read_ftext(cdo, field)
  local ok, val = pcall(function() return cdo[field] end)
  if not ok then return nil end
  local s = to_str(val)
  if s and s ~= "" then return s end
  return nil
end

local function resolve_cultures(want)
  if type(want) == "table" then return want end
  return discover_cultures()
end

local function dump_loc(kinds, cultures_want)
  local kindset = {}
  for _, k in ipairs(kinds or {"item", "npc", "knowledge"}) do kindset[k] = true end

  local cultures = resolve_cultures(cultures_want)
  if #cultures == 0 then
    log('loc: no cultures resolved. Set loc.cultures = {"en","de",...} in config.lua. Aborting.')
    return 0
  end
  log("loc: cultures = " .. table.concat(cultures, ", "))

  local targets = {}
  for _, t in ipairs(LOC.targets) do
    if kindset[t.kind] then targets[#targets + 1] = t end
  end
  log("loc: " .. tostring(#targets) .. " targets")

  -- data[id] = {kind=, text={field={culture=str}}}; order keeps output stable.
  local data, order = {}, {}
  local orig = current_culture()

  for _, culture in ipairs(cultures) do
    if not set_culture(culture) then
      log("loc: SetCurrentCulture failed for " .. culture .. " (skipped)")
    else
      for _, t in ipairs(targets) do
        local cdo = StaticFindObject("/Script/Angelscript.Default__" .. t.id)
        if cdo and cdo:IsValid() then
          for _, field in ipairs(LOC.fields_by_kind[t.kind] or {}) do
            local s = read_ftext(cdo, field)
            if s then
              local rec = data[t.id]
              if not rec then rec = {kind = t.kind, text = {}}; data[t.id] = rec; order[#order + 1] = t.id end
              local fmap = rec.text[field]
              if not fmap then fmap = {}; rec.text[field] = fmap end
              fmap[culture] = s
            end
          end
        end
      end
    end
  end

  if orig then set_culture(orig) end

  local parts = {}
  for _, id in ipairs(order) do
    local rec = data[id]
    local fparts = {}
    for field, cmap in pairs(rec.text) do
      local cparts = {}
      for _, culture in ipairs(cultures) do
        if cmap[culture] then
          cparts[#cparts + 1] = string.format('"%s":"%s"', json_escape(culture), json_escape(cmap[culture]))
        end
      end
      fparts[#fparts + 1] = string.format('"%s":{%s}', json_escape(field), table.concat(cparts, ","))
    end
    parts[#parts + 1] = string.format('"%s":{"kind":"%s","text":{%s}}',
      json_escape(id), json_escape(rec.kind), table.concat(fparts, ","))
  end
  local cset = {}
  for _, c in ipairs(cultures) do cset[#cset + 1] = string.format('"%s"', json_escape(c)) end
  local json = string.format('{"cultures":[%s],"entries":{%s}}',
    table.concat(cset, ","), table.concat(parts, ","))

  local fh = io.open(LOC_OUT, "w")
  if fh then
    fh:write(json); fh:close()
    log("loc: wrote " .. tostring(#order) .. " entries -> " .. LOC_OUT)
  else
    log("loc: FAILED to open " .. LOC_OUT .. " for writing")
  end
  return #order
end

-- ====================== console command + auto =====================

-- "all"/empty -> nil (use config default); else split "a,b,c" into a list.
local function parse_csv(s)
  if not s or s == "" or s == "all" then return nil end
  local t = {}
  for w in s:gmatch("[^,]+") do t[#t + 1] = w end
  return t
end

-- `gore-dump <stats|loc|all> [item,npc,knowledge] [en,de,...]`
RegisterConsoleCommandHandler("gore-dump", function(_, Parameters, Ar)
  local function out(m)
    if Ar then pcall(function() Ar:Log(m) end) end
    log(m)
  end
  local sub = string.lower(Parameters[1] or "all")
  if sub == "stats" then
    out("stats: wrote " .. tostring(dump_stats()) .. " classes")
  elseif sub == "loc" then
    local kinds = parse_csv(Parameters[2]) or CONFIG.loc.kinds
    local cultures = parse_csv(Parameters[3]) or CONFIG.loc.cultures
    out("loc: wrote " .. tostring(dump_loc(kinds, cultures)) .. " entries")
  elseif sub == "all" then
    dump_stats()
    dump_loc(CONFIG.loc.kinds, CONFIG.loc.cultures)
    out("all: done")
  else
    out("usage: gore-dump <stats|loc|all> [item,npc,knowledge] [en,de,...]")
  end
  return true
end)

do
  local found = discover_cultures()
  if #found > 0 then log("cultures available: " .. table.concat(found, ", ")) end
end

if CONFIG.auto and CONFIG.auto.enabled then
  log("loaded; auto-dump in " .. tostring(CONFIG.auto.delay_ms)
    .. "ms (console: `gore-dump <stats|loc|all>`)")
  ExecuteWithDelay(CONFIG.auto.delay_ms, function()
    if CONFIG.auto.stats then dump_stats() end
    if CONFIG.auto.loc then dump_loc(CONFIG.loc.kinds, CONFIG.loc.cultures) end
  end)
else
  log("loaded; auto-dump disabled (console: `gore-dump <stats|loc|all>`)")
end
"#;

const README: &str = r#"# gore-dump

UE4SS Lua mod that reads live CDO values and writes two files:

- `gore_game_data.json` — item stat defaults; `gore-cli sync` ingests it to
  refresh the gore-mod editor with real defaults.
- `gore_loc.json` — localized item/NPC/dialog names + descriptions in every
  shipped culture; ingested into the loc catalogs both gore-save and gore-mod use.

## Use

1. Copy this `gore-dump/` folder into `<game>/Binaries/Win64/ue4ss/Mods/`.
2. Make sure UE4SS lists it (it ships with an empty `enabled.txt`).
3. (Optional) edit `Scripts/config.lua` to choose what auto-dumps and which
   cultures/kinds the loc dump covers.
4. Launch the game, reach the main menu (or load a save), wait ~15s for the
   auto-dump. Both JSONs land in the game's working dir (usually
   `Binaries/Win64/`). Watch the UE4SS console for paths and the discovered
   culture list.
5. Re-dump on demand from the UE4SS console without relaunching:
   - `gore-dump stats`            — stats only
   - `gore-dump loc`              — loc, config scope
   - `gore-dump loc item en,de`   — only items, only EN+DE
   - `gore-dump all`              — both
6. Feed the outputs back:
   - `gore-cli sync --dump gore_game_data.json --catalog item_catalog.json -o model.json`
   - (loc ingest: see `gore-cli` loc command)

If `gore-dump loc` reports "no cultures resolved", pin the list in `config.lua`
(`cultures = {"en","de",...}`) using the codes the console logs at load.

Regenerate this mod (`gore-cli dump-mod`) after the item/NPC/knowledge sets
change so the bundled allow-lists stay current.
"#;

#[derive(Deserialize)]
struct NpcCatalogEntry {
    /// AngelScript class, e.g. `CharacterDefinition_Human_OC_STT_Diego`.
    class: String,
}

#[derive(Deserialize)]
struct KnowledgeCatalogEntry {
    /// AngelScript class, e.g. `Topic_...` / `Info_...` / `Choice12345`.
    id: String,
}

pub fn run(
    model_path: PathBuf,
    catalog_path: PathBuf,
    npc_catalog: Option<PathBuf>,
    knowledge_catalog: Option<PathBuf>,
    out: PathBuf,
) -> Result<()> {
    let model_json = fs::read_to_string(&model_path)
        .with_context(|| format!("reading model '{}'", model_path.display()))?;
    let model: GuiModel = serde_json::from_str(&model_json).context("parsing model.json")?;

    let catalog_json = fs::read_to_string(&catalog_path)
        .with_context(|| format!("reading catalog '{}'", catalog_path.display()))?;
    let catalog = parse_catalog(&catalog_json).context("parsing item_catalog.json")?;

    let items_lua = render_items_lua(&model, catalog.iter().map(|e| e.id.as_str()));

    let npc_classes: Vec<String> = match &npc_catalog {
        Some(p) => {
            let json = fs::read_to_string(p)
                .with_context(|| format!("reading npc catalog '{}'", p.display()))?;
            let entries: Vec<NpcCatalogEntry> =
                serde_json::from_str(&json).context("parsing npc_catalog.json")?;
            entries.into_iter().map(|e| e.class).collect()
        }
        None => Vec::new(),
    };
    let knowledge_ids: Vec<String> = match &knowledge_catalog {
        Some(p) => {
            let json = fs::read_to_string(p)
                .with_context(|| format!("reading knowledge catalog '{}'", p.display()))?;
            let entries: Vec<KnowledgeCatalogEntry> =
                serde_json::from_str(&json).context("parsing knowledge_catalog.json")?;
            entries.into_iter().map(|e| e.id).collect()
        }
        None => Vec::new(),
    };

    let loc_targets_lua = render_loc_targets_lua(
        catalog.iter().map(|e| e.id.as_str()),
        npc_classes.iter().map(String::as_str),
        knowledge_ids.iter().map(String::as_str),
    );

    let mod_dir = out.join("gore-dump");
    let scripts = mod_dir.join("Scripts");
    fs::create_dir_all(&scripts)
        .with_context(|| format!("creating '{}'", scripts.display()))?;
    fs::write(mod_dir.join("enabled.txt"), "")?;
    fs::write(mod_dir.join("README.md"), README)?;
    fs::write(scripts.join("main.lua"), MAIN_LUA)?;
    fs::write(scripts.join("config.lua"), CONFIG_LUA)?;
    fs::write(scripts.join("items.lua"), &items_lua)?;
    fs::write(scripts.join("loc_targets.lua"), &loc_targets_lua)?;

    let stat_count = items_lua.matches("id=").count();
    let loc_count = catalog.len() + npc_classes.len() + knowledge_ids.len();
    println!(
        "Wrote gore-dump mod ({stat_count} stat classes, {loc_count} loc targets) -> {}",
        mod_dir.display()
    );
    Ok(())
}

/// Render the `items.lua` table: `return { {id="..", fields={ {name=..,type=..,
/// enum_values={..}} }}, .. }`, restricted to catalog ids present in the model.
fn render_items_lua<'a>(model: &GuiModel, catalog_ids: impl Iterator<Item = &'a str>) -> String {
    let mut out = String::from("-- gore-dump item/field schema (generated by gore-cli)\nreturn {\n");
    for id in catalog_ids {
        let Some(class) = model.classes.get(id) else {
            continue;
        };
        out.push_str(&format!("  {{id=\"{}\", fields={{\n", lua_escape(id)));
        for f in &class.fields {
            out.push_str(&format!(
                "    {{name=\"{}\", type=\"{}\"",
                lua_escape(&f.name),
                lua_escape(&f.field_type)
            ));
            if !f.enum_values.is_empty() {
                let members: Vec<String> = f
                    .enum_values
                    .iter()
                    .map(|m| format!("\"{}\"", lua_escape(m)))
                    .collect();
                out.push_str(&format!(", enum_values={{{}}}", members.join(", ")));
            }
            if !f.enum_value_ints.is_empty() {
                let ints: Vec<String> = f.enum_value_ints.iter().map(|v| v.to_string()).collect();
                out.push_str(&format!(", enum_value_ints={{{}}}", ints.join(", ")));
            }
            out.push_str("},\n");
        }
        out.push_str("  }},\n");
    }
    out.push_str("}\n");
    out
}

/// Render `loc_targets.lua`: per-kind FText field lists plus a flat target list.
/// The mod looks each id up at `/Script/Angelscript.Default__<id>`.
fn render_loc_targets_lua<'a>(
    item_ids: impl Iterator<Item = &'a str>,
    npc_classes: impl Iterator<Item = &'a str>,
    knowledge_ids: impl Iterator<Item = &'a str>,
) -> String {
    fn field_list(fields: &[&str]) -> String {
        fields
            .iter()
            .map(|f| format!("\"{}\"", lua_escape(f)))
            .collect::<Vec<_>>()
            .join(", ")
    }

    let mut out = String::from("-- gore-dump loc targets (generated by gore-cli) — do not edit by hand.\n");
    out.push_str("return {\n  fields_by_kind = {\n");
    out.push_str(&format!("    item = {{{}}},\n", field_list(ITEM_FIELDS)));
    out.push_str(&format!("    npc = {{{}}},\n", field_list(NPC_FIELDS)));
    out.push_str(&format!("    knowledge = {{{}}},\n", field_list(KNOWLEDGE_FIELDS)));
    out.push_str("  },\n  targets = {\n");
    for id in item_ids {
        out.push_str(&format!("    {{kind=\"item\", id=\"{}\"}},\n", lua_escape(id)));
    }
    for cls in npc_classes {
        out.push_str(&format!("    {{kind=\"npc\", id=\"{}\"}},\n", lua_escape(cls)));
    }
    for id in knowledge_ids {
        out.push_str(&format!("    {{kind=\"knowledge\", id=\"{}\"}},\n", lua_escape(id)));
    }
    out.push_str("  },\n}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn model() -> GuiModel {
        serde_json::from_value(json!({
            "classes": {
                "ItFo_Apple": {"fields": [
                    {"name": "m_Value", "type": "int"},
                    {"name": "m_Quality", "type": "enum", "enum_values": ["Low", "High"], "enum_value_ints": [0, 5]}
                ]},
                "NotInCatalog": {"fields": [{"name": "x", "type": "int"}]}
            }
        }))
        .unwrap()
    }

    #[test]
    fn renders_catalog_items_with_fields_and_enums() {
        let lua = render_items_lua(&model(), ["ItFo_Apple"].into_iter());
        assert!(lua.contains(r#"{id="ItFo_Apple", fields={"#));
        assert!(lua.contains(r#"{name="m_Value", type="int"},"#));
        assert!(lua.contains(
            r#"{name="m_Quality", type="enum", enum_values={"Low", "High"}, enum_value_ints={0, 5}},"#
        ));
        // valid Lua table delimiters
        assert!(lua.trim_end().ends_with('}'));
    }

    #[test]
    fn skips_classes_absent_from_catalog() {
        let lua = render_items_lua(&model(), ["ItFo_Apple"].into_iter());
        assert!(!lua.contains("NotInCatalog"));
    }

    #[test]
    fn main_lua_uses_the_proven_cdo_path_and_writes_json() {
        assert!(MAIN_LUA.contains(r#"StaticFindObject("/Script/Angelscript.Default__" .. cls.id)"#));
        assert!(MAIN_LUA.contains("gore_game_data.json"));
        assert!(MAIN_LUA.contains("ExecuteWithDelay"));
    }

    #[test]
    fn main_lua_emits_enum_backing_values() {
        // The in-game writer must copy enum_value_ints so sync can validate the
        // CDO's backing-value default against the real discriminants.
        assert!(MAIN_LUA.contains("f.enum_value_ints"));
        assert!(MAIN_LUA.contains(r#""enum_value_ints":["#));
    }

    #[test]
    fn main_lua_skips_non_finite_values() {
        // inf/nan are not valid JSON; the dumper must drop them.
        assert!(MAIN_LUA.contains("v == math.huge"));
        assert!(MAIN_LUA.contains("v ~= v"));
    }

    #[test]
    fn main_lua_registers_gore_dump_console_command() {
        assert!(MAIN_LUA.contains(r#"RegisterConsoleCommandHandler("gore-dump""#));
        // loc dump switches culture and resolves FText to a string
        assert!(MAIN_LUA.contains("SetCurrentCulture"));
        assert!(MAIN_LUA.contains("gore_loc.json"));
    }

    #[test]
    fn loc_targets_groups_kinds_with_field_lists() {
        let lua = render_loc_targets_lua(
            ["ItFo_Apple"].into_iter(),
            ["CharacterDefinition_Human_Diego"].into_iter(),
            ["Choice123"].into_iter(),
        );
        assert!(lua.contains(r#"item = {"m_Name", "m_Description"}"#));
        assert!(lua.contains(r#"npc = {"m_Name", "m_CharacterName"}"#));
        assert!(lua.contains(r#"{kind="item", id="ItFo_Apple"}"#));
        assert!(lua.contains(r#"{kind="npc", id="CharacterDefinition_Human_Diego"}"#));
        assert!(lua.contains(r#"{kind="knowledge", id="Choice123"}"#));
        assert!(lua.trim_end().ends_with('}'));
    }
}
