//! `gore-cli dump-mod` — generate the **gore-dump** UE4SS Lua mod.
//!
//! The mod reads live CDO values in-game and writes two files:
//!   * `gore_game_data.json` — item stat defaults (the shape `gore-cli sync`
//!     ingests), giving the GUI the real per-field defaults only the running
//!     game knows.
//!   * `gore_loc_<lang>.json` — localized `FText` names/descriptions for items,
//!     NPCs and dialog knowledge in the language the options menu is set to.
//!     The engine language/culture API does not drive the Alkimia loc, so this
//!     is a manual pass per language; `gore-cli` merges the files. Consumed by
//!     both gore-save and gore-mod to show real in-game names.
//!
//! Both dumps run against bundled allow-lists (`items.lua`, `loc_targets.lua`)
//! via the proven `StaticFindObject(Default__<id>)[field]` path — no fragile
//! reflection. They are triggered by `config.lua` on launch and/or the
//! `gore-dump` UE4SS console command. New items/fields from a game patch need
//! the catalogs/model regenerated before they appear here.

use anyhow::{Context, Result};
use gore_core::{catalog::parse_catalog, gen::lua_escape};
use serde::Deserialize;
use std::{fs, path::PathBuf};

use crate::cmd::gui_model::GuiModel;

/// FText field names read per target kind. These are inherited from C++ base
/// classes (`UGothicObjectDefinition::m_Name`, `UG1RDialogTopic::Caption`, ...),
/// so they are read by name through the inheritance chain — `ForEachProperty`
/// only sees leaf-declared props and would miss them.
const ITEM_FIELDS: &[&str] = &["m_Name", "m_Description"];
const NPC_FIELDS: &[&str] = &["m_Name", "m_CharacterName"];
const KNOWLEDGE_FIELDS: &[&str] = &["Caption", "InitialForcedLine", "m_Name"];

/// Default `config.lua`. Written fresh on every generation; users tune the copy
/// deployed into the game's `Mods/gore-dump/Scripts/` directory.
const CONFIG_LUA: &str = r#"-- gore-dump config — safe to edit your deployed copy.
return {
  -- Auto stats-dump when the game finishes loading (main menu is enough).
  auto = {
    enabled  = true,
    delay_ms = 15000,
    stats    = true,   -- write gore_game_data.json (item stat defaults)
  },
  -- Default kinds for the loc dump (override per call: `gore-dump loc de item`).
  -- The loc dump is manual: the engine language does not drive the Alkimia text,
  -- so set the language in the options menu, then run `gore-dump loc <lang>`.
  loc = {
    kinds = {"item", "npc", "knowledge"},
  },
}
"#;

/// Fixed runtime. Reads CDO values against the bundled `items.lua` (stats) and
/// `loc_targets.lua` (localized text) schemas. See module docs.
const MAIN_LUA: &str = r#"-- gore-dump (generated by gore-cli) — do not edit by hand.
-- Live CDO reader. Writes gore_game_data.json (item stats) and gore_loc_<lang>.json
-- (localized FText names/descriptions for the language the options menu is set
-- to). Triggered by config.lua on launch and/or the `gore-dump` console command.
local CONFIG = require("config")
local STATS_SCHEMA = require("items")
local LOC = require("loc_targets")
local STATS_OUT = "gore_game_data.json"
local INTL_CDO = "/Script/Engine.Default__KismetInternationalizationLibrary"

local function log(msg) print("[gore-dump] " .. tostring(msg) .. "\n") end

local function json_escape(s)
  return (s:gsub('[%z\1-\31\\"]', function(c)
    local map = {['"']='\\"', ['\\']='\\\\', ['\n']='\\n', ['\r']='\\r', ['\t']='\\t'}
    return map[c] or string.format('\\u%04x', string.byte(c))
  end))
end

-- ============================ stats dump ============================

-- Encode a read value as JSON, typed by the field. Returns nil when the value
-- is missing or the wrong Lua type (the field is then emitted without a default).
local function value_json(field_type, v)
  if field_type == "bool" then
    if type(v) == "boolean" then return v and "true" or "false" end
    return nil
  end
  if type(v) ~= "number" then return nil end
  -- JSON has no inf/nan; skip non-finite values so the file stays valid JSON
  -- (the field is then emitted without a default -> GUI shows a placeholder).
  if v ~= v or v == math.huge or v == -math.huge then return nil end
  if field_type == "int" or field_type == "enum" then
    return string.format("%d", math.floor(v + 0.5))
  end
  return string.format("%.17g", v) -- float: round-trips a double
end

local function dump_stats()
  local classes = {}
  for _, cls in ipairs(STATS_SCHEMA) do
    local cdo = StaticFindObject("/Script/Angelscript.Default__" .. cls.id)
    if cdo and cdo:IsValid() then
      local fields = {}
      for _, f in ipairs(cls.fields) do
        local ok, raw = pcall(function() return cdo[f.name] end)
        local parts = {
          string.format('"name":"%s"', json_escape(f.name)),
          string.format('"type":"%s"', json_escape(f.type)),
        }
        if f.enum_values then
          local evs = {}
          for _, e in ipairs(f.enum_values) do
            evs[#evs + 1] = string.format('"%s"', json_escape(e))
          end
          parts[#parts + 1] = '"enum_values":[' .. table.concat(evs, ",") .. ']'
        end
        if f.enum_value_ints then
          local ivs = {}
          for _, n in ipairs(f.enum_value_ints) do
            ivs[#ivs + 1] = string.format("%d", n)
          end
          parts[#parts + 1] = '"enum_value_ints":[' .. table.concat(ivs, ",") .. ']'
        end
        local dj = ok and value_json(f.type, raw) or nil
        if dj then parts[#parts + 1] = '"default":' .. dj end
        fields[#fields + 1] = "{" .. table.concat(parts, ",") .. "}"
      end
      classes[#classes + 1] = string.format(
        '"%s":{"fields":[%s]}', json_escape(cls.id), table.concat(fields, ","))
    else
      log("stats: CDO not found (skipped): " .. cls.id)
    end
  end
  local json = '{"classes":{' .. table.concat(classes, ",") .. '}}'
  local fh = io.open(STATS_OUT, "w")
  if fh then
    fh:write(json); fh:close()
    log("stats: wrote " .. tostring(#classes) .. " classes -> " .. STATS_OUT)
  else
    log("stats: FAILED to open " .. STATS_OUT .. " for writing")
  end
  return #classes
end

-- ============================ loc dump =============================

local function intl() return StaticFindObject(INTL_CDO) end

local function to_str(v)
  if type(v) == "string" then return v end
  if v == nil then return nil end
  local ok, s = pcall(function() return v:ToString() end)
  if ok and type(s) == "string" then return s end
  return nil
end

-- The game's text (Alkimia loc) follows the engine *language*, not the culture
-- (a run showed culture=en-US while text rendered German). Read/write language
-- first; fall back to culture for older builds.
local function current_culture()
  local o = intl(); if not o then return nil end
  for _, fn in ipairs({"GetCurrentLanguage", "GetCurrentCulture"}) do
    local ok, c = pcall(function() return o[fn](o) end)
    if ok then
      local s = to_str(c)
      if s and s ~= "" then return s end
    end
  end
  return nil
end

local function read_ftext(cdo, field)
  local ok, val = pcall(function() return cdo[field] end)
  if not ok then return nil end
  local s = to_str(val)
  if s and s ~= "" then return s end
  return nil
end

-- Filename-safe form of a language label (zh-Hans, pt-BR -> kept; junk dropped).
local function safe_label(lang)
  return (tostring(lang):gsub("[^%w%-_]", ""))
end

-- Dump the localized text the game currently holds, tagged with `lang`. The
-- engine culture/language API does NOT drive the Alkimia loc (verified in-game:
-- culture en-US while text was German), so there is no programmatic switch — the
-- caller sets the language in the game's options menu, then runs this per
-- language. Each call writes gore_loc_<lang>.json; `gore-cli` merges them.
-- NPC CharacterDefinition CDOs only exist once a save is loaded, so run this
-- from inside a loaded game, not the main menu, to capture kind=npc.
local function dump_loc(lang, kinds)
  local label = safe_label(lang)
  if label == "" then
    log("loc: missing language label. Usage: gore-dump loc <lang> [item,npc,knowledge]")
    return 0
  end

  local kindset = {}
  for _, k in ipairs(kinds or {"item", "npc", "knowledge"}) do kindset[k] = true end

  local cur = current_culture()
  log("loc: dumping language '" .. label .. "' (engine reports " .. tostring(cur) .. ")")

  -- NPC names are not baked into the CharacterDefinition CDO (m_Name is empty);
  -- they resolve via the Alkimia loc subsystem keyed by the unique name
  -- (GetText("OC_STT_Diego") -> "Diego"). GetText is the only subsystem call
  -- proven crash-safe in-game (the TArray/TMap getters and the language-set
  -- mutators crash), so we use just that, in the current menu language.
  local locsub = FindFirstOf("AlkimiaLocalizationSubsystem")
  local function loc_get(id)
    if not (locsub and id and id ~= "") then return nil end
    local ok, v = pcall(function() return locsub:GetText(id) end)
    if not ok then return nil end
    local s = to_str(v)
    if s and s ~= "" then return s end
    return nil
  end

  -- per-kind diagnostics: distinguish "CDO not loaded" from "found but no text".
  local total, found, textful = {}, {}, {}

  local parts, n = {}, 0
  for _, t in ipairs(LOC.targets) do
    if kindset[t.kind] then
      total[t.kind] = (total[t.kind] or 0) + 1
      local cdo = StaticFindObject("/Script/Angelscript.Default__" .. t.id)
      if cdo and cdo:IsValid() then
        found[t.kind] = (found[t.kind] or 0) + 1
        local fparts = {}
        if t.kind == "npc" then
          -- name via subsystem(m_UniqueName); description via subsystem too.
          local uid
          local ok, raw = pcall(function() return cdo.m_UniqueName end)
          if ok then uid = to_str(raw) end
          local nm = loc_get(uid)
          if nm then
            fparts[#fparts + 1] = string.format('"m_Name":"%s"', json_escape(nm))
          end
        else
          for _, field in ipairs(LOC.fields_by_kind[t.kind] or {}) do
            local s = read_ftext(cdo, field)
            if s then
              fparts[#fparts + 1] = string.format('"%s":"%s"', json_escape(field), json_escape(s))
            end
          end
        end
        if #fparts > 0 then
          textful[t.kind] = (textful[t.kind] or 0) + 1
          parts[#parts + 1] = string.format('"%s":{"kind":"%s","text":{%s}}',
            json_escape(t.id), json_escape(t.kind), table.concat(fparts, ","))
          n = n + 1
        end
      end
    end
  end

  for _, k in ipairs({"item", "npc", "knowledge"}) do
    if total[k] then
      log(string.format("loc: %s: %d/%d CDOs found, %d with text",
        k, found[k] or 0, total[k], textful[k] or 0))
    end
  end

  local json = string.format('{"language":"%s","entries":{%s}}',
    json_escape(label), table.concat(parts, ","))
  local out_file = "gore_loc_" .. label .. ".json"
  local fh = io.open(out_file, "w")
  if fh then
    fh:write(json); fh:close()
    log("loc: wrote " .. tostring(n) .. " entries -> " .. out_file)
  else
    log("loc: FAILED to open " .. out_file .. " for writing")
  end
  return n
end

-- ====================== console command + auto =====================

-- "all"/empty -> nil (use config default kinds); else split "a,b,c" into a list.
local function parse_csv(s)
  if not s or s == "" or s == "all" then return nil end
  local t = {}
  for w in s:gmatch("[^,]+") do t[#t + 1] = w end
  return t
end

-- Diagnostic: inspect one CDO's candidate name fields. Reports found/empty/value
-- for each, to learn where a kind's display name actually lives.
local PROBE_FIELDS = {
  "m_Name", "m_Description", "m_UniqueName", "m_CharacterName",
  "CharacterName", "m_DisplayName", "Caption", "NameText",
}
local function probe_cdo(class, out)
  if not class or class == "" then
    out("probe: usage: gore-dump probe <ClassName>  (e.g. CharacterDefinition_Human_OC_STT_Diego)")
    return
  end
  local cdo = StaticFindObject("/Script/Angelscript.Default__" .. class)
  if not (cdo and cdo:IsValid()) then
    out("probe: CDO NOT FOUND/loaded: " .. class)
    return
  end
  out("probe: " .. class .. " found. fields:")
  for _, field in ipairs(PROBE_FIELDS) do
    local ok, val = pcall(function() return cdo[field] end)
    if not ok then
      out("  " .. field .. " = <no such field>")
    elseif val == nil then
      out("  " .. field .. " = <nil>")
    else
      local s = to_str(val)
      out("  " .. field .. " = " .. (s == nil and "<not text>" or (s == "" and "<empty>" or '"' .. s .. '"')))
    end
  end
end

-- Probe the Alkimia loc subsystem: language-set names + whether it can read text
-- by id/language directly (which would let one run cover every language).
local function locapi_probe(arg, out)
  local sub = FindFirstOf("AlkimiaLocalizationSubsystem")
  if not (sub and sub:IsValid()) then
    out("locapi: AlkimiaLocalizationSubsystem NOT found")
    return
  end
  out("locapi: subsystem found")

  -- WARNING: pcall does NOT catch native access violations. The TArray/TMap
  -- field iterators and the language-set mutators (SetActiveDisplayLanguageSet /
  -- ReloadLocalization) AV-crash the game, so this probe only uses GetText
  -- (proven safe) and a single FName field read. GetTextAsString is tried only
  -- when you pass an explicit language id: `gore-dump locapi <langId>`.
  local ok, active = pcall(function() return sub.ActiveDisplayLanguageSet end)
  out("  ActiveDisplayLanguageSet = " .. tostring(ok and to_str(active) or "<err>"))

  for _, id in ipairs({"OC_STT_Diego", "OC_STT_Gorn_699"}) do
    local g = pcall(function() return sub:GetText(id) end)
    local v = g and to_str(sub:GetText(id)) or "<err>"
    out("  GetText('" .. id .. "') = " .. tostring(v))
  end

  if arg and arg ~= "" then
    local ok2, v = pcall(function() return sub:GetTextAsString("OC_STT_Diego", arg) end)
    out("  GetTextAsString('OC_STT_Diego','" .. arg .. "') = " .. (ok2 and tostring(to_str(v) or v) or "<err/crash-risk>"))
  end
end

-- gore-dump stats
-- gore-dump loc <lang> [item,npc,knowledge]   (set the menu language first)
-- gore-dump all <lang> [item,npc,knowledge]
-- gore-dump probe <ClassName>                 (inspect one CDO's name fields)
-- gore-dump locapi [langSet]                  (probe the Alkimia loc subsystem)
RegisterConsoleCommandHandler("gore-dump", function(_, Parameters, Ar)
  local function out(m)
    if Ar then pcall(function() Ar:Log(m) end) end
    log(m)
  end
  local sub = string.lower(Parameters[1] or "")
  if sub == "stats" then
    out("stats: wrote " .. tostring(dump_stats()) .. " classes")
  elseif sub == "loc" then
    local kinds = parse_csv(Parameters[3]) or CONFIG.loc.kinds
    out("loc: wrote " .. tostring(dump_loc(Parameters[2], kinds)) .. " entries")
  elseif sub == "all" then
    dump_stats()
    local kinds = parse_csv(Parameters[3]) or CONFIG.loc.kinds
    dump_loc(Parameters[2], kinds)
    out("all: done")
  elseif sub == "probe" then
    probe_cdo(Parameters[2], out)
  elseif sub == "locapi" then
    locapi_probe(Parameters[2], out)
  else
    out("usage: gore-dump <stats | loc <lang> | all <lang> | probe <Class> | locapi [set]> [item,npc,knowledge]")
  end
  return true
end)

do
  local o = intl()
  if o then
    local function try(fn)
      local ok, v = pcall(function() return o[fn](o) end)
      return ok and to_str(v) or "?"
    end
    -- Diagnostic only: the engine language/culture does NOT drive the Alkimia
    -- loc, so this is just FYI — the dumped text follows the options-menu language.
    log("engine language = " .. try("GetCurrentLanguage") .. ", culture = " .. try("GetCurrentCulture"))
  end
end

if CONFIG.auto and CONFIG.auto.enabled and CONFIG.auto.stats then
  log("loaded; auto stats-dump in " .. tostring(CONFIG.auto.delay_ms)
    .. "ms. Loc: set the menu language, then `gore-dump loc <lang>` (from a loaded save for NPCs).")
  ExecuteWithDelay(CONFIG.auto.delay_ms, function() dump_stats() end)
else
  log("loaded. Loc: set the menu language, then `gore-dump loc <lang>` (from a loaded save for NPCs).")
end
"#;

const README: &str = r#"# gore-dump

UE4SS Lua mod that reads live CDO values and writes:

- `gore_game_data.json` — item stat defaults; `gore-cli sync` ingests it to
  refresh the gore-mod editor with real defaults.
- `gore_loc_<lang>.json` — localized item/NPC/dialog names + descriptions for the
  language the game is currently set to. One file per language; `gore-cli` merges
  them into the loc catalogs both gore-save and gore-mod use.

## Use

1. Copy this `gore-dump/` folder into `<game>/Binaries/Win64/ue4ss/Mods/`.
2. Make sure UE4SS lists it (it ships with an empty `enabled.txt`).
3. Launch the game and wait ~15s — the stats dump (`gore_game_data.json`) runs
   automatically and lands in the game's working dir (usually `Binaries/Win64/`).

### Localized names (manual, one pass per language)

The engine language/culture API does **not** drive the Alkimia localization, so
there is no programmatic switch. Instead, per language:

1. Set the language in the game's **options menu**.
2. **Load a save** (NPC `CharacterDefinition` CDOs only exist in a loaded game;
   from the main menu kind=npc comes back empty).
3. In the UE4SS console run `gore-dump loc <lang>`, e.g. `gore-dump loc de`.
   The `<lang>` is just a label for the output file — use it consistently
   (`de en pl ru fr it es ja zh-Hans pt-BR`).
4. Repeat for each language. Each run writes `gore_loc_<lang>.json`.

Scope a run with a kinds list: `gore-dump loc de item,npc` (default: all three).

The loc dump blocks the game thread for up to ~80s with all kinds; items-only is
a few seconds.

## Feed the outputs back

- `gore-cli sync --dump gore_game_data.json --catalog item_catalog.json -o model.json`
- loc merge: `gore-cli` loc command over the `gore_loc_*.json` files.

Regenerate this mod (`gore-cli dump-mod`) after the item/NPC/knowledge sets
change so the bundled allow-lists stay current.
"#;

#[derive(Deserialize)]
struct NpcCatalogEntry {
    /// AngelScript class, e.g. `CharacterDefinition_Human_OC_STT_Diego`.
    class: String,
}

#[derive(Deserialize)]
struct KnowledgeCatalogEntry {
    /// AngelScript class, e.g. `Topic_...` / `Info_...` / `Choice12345`.
    id: String,
}

pub fn run(
    model_path: PathBuf,
    catalog_path: PathBuf,
    npc_catalog: Option<PathBuf>,
    knowledge_catalog: Option<PathBuf>,
    out: PathBuf,
) -> Result<()> {
    let model_json = fs::read_to_string(&model_path)
        .with_context(|| format!("reading model '{}'", model_path.display()))?;
    let model: GuiModel = serde_json::from_str(&model_json).context("parsing model.json")?;

    let catalog_json = fs::read_to_string(&catalog_path)
        .with_context(|| format!("reading catalog '{}'", catalog_path.display()))?;
    let catalog = parse_catalog(&catalog_json).context("parsing item_catalog.json")?;

    let items_lua = render_items_lua(&model, catalog.iter().map(|e| e.id.as_str()));

    let npc_classes: Vec<String> = match &npc_catalog {
        Some(p) => {
            let json = fs::read_to_string(p)
                .with_context(|| format!("reading npc catalog '{}'", p.display()))?;
            let entries: Vec<NpcCatalogEntry> =
                serde_json::from_str(&json).context("parsing npc_catalog.json")?;
            entries.into_iter().map(|e| e.class).collect()
        }
        None => Vec::new(),
    };
    let knowledge_ids: Vec<String> = match &knowledge_catalog {
        Some(p) => {
            let json = fs::read_to_string(p)
                .with_context(|| format!("reading knowledge catalog '{}'", p.display()))?;
            let entries: Vec<KnowledgeCatalogEntry> =
                serde_json::from_str(&json).context("parsing knowledge_catalog.json")?;
            entries.into_iter().map(|e| e.id).collect()
        }
        None => Vec::new(),
    };

    let loc_targets_lua = render_loc_targets_lua(
        catalog.iter().map(|e| e.id.as_str()),
        npc_classes.iter().map(String::as_str),
        knowledge_ids.iter().map(String::as_str),
    );

    let mod_dir = out.join("gore-dump");
    let scripts = mod_dir.join("Scripts");
    fs::create_dir_all(&scripts)
        .with_context(|| format!("creating '{}'", scripts.display()))?;
    fs::write(mod_dir.join("enabled.txt"), "")?;
    fs::write(mod_dir.join("README.md"), README)?;
    fs::write(scripts.join("main.lua"), MAIN_LUA)?;
    fs::write(scripts.join("config.lua"), CONFIG_LUA)?;
    fs::write(scripts.join("items.lua"), &items_lua)?;
    fs::write(scripts.join("loc_targets.lua"), &loc_targets_lua)?;

    let stat_count = items_lua.matches("id=").count();
    let loc_count = catalog.len() + npc_classes.len() + knowledge_ids.len();
    println!(
        "Wrote gore-dump mod ({stat_count} stat classes, {loc_count} loc targets) -> {}",
        mod_dir.display()
    );
    Ok(())
}

/// Render the `items.lua` table: `return { {id="..", fields={ {name=..,type=..,
/// enum_values={..}} }}, .. }`, restricted to catalog ids present in the model.
fn render_items_lua<'a>(model: &GuiModel, catalog_ids: impl Iterator<Item = &'a str>) -> String {
    let mut out = String::from("-- gore-dump item/field schema (generated by gore-cli)\nreturn {\n");
    for id in catalog_ids {
        let Some(class) = model.classes.get(id) else {
            continue;
        };
        out.push_str(&format!("  {{id=\"{}\", fields={{\n", lua_escape(id)));
        for f in &class.fields {
            out.push_str(&format!(
                "    {{name=\"{}\", type=\"{}\"",
                lua_escape(&f.name),
                lua_escape(&f.field_type)
            ));
            if !f.enum_values.is_empty() {
                let members: Vec<String> = f
                    .enum_values
                    .iter()
                    .map(|m| format!("\"{}\"", lua_escape(m)))
                    .collect();
                out.push_str(&format!(", enum_values={{{}}}", members.join(", ")));
            }
            if !f.enum_value_ints.is_empty() {
                let ints: Vec<String> = f.enum_value_ints.iter().map(|v| v.to_string()).collect();
                out.push_str(&format!(", enum_value_ints={{{}}}", ints.join(", ")));
            }
            out.push_str("},\n");
        }
        out.push_str("  }},\n");
    }
    out.push_str("}\n");
    out
}

/// Render `loc_targets.lua`: per-kind FText field lists plus a flat target list.
/// The mod looks each id up at `/Script/Angelscript.Default__<id>`.
fn render_loc_targets_lua<'a>(
    item_ids: impl Iterator<Item = &'a str>,
    npc_classes: impl Iterator<Item = &'a str>,
    knowledge_ids: impl Iterator<Item = &'a str>,
) -> String {
    fn field_list(fields: &[&str]) -> String {
        fields
            .iter()
            .map(|f| format!("\"{}\"", lua_escape(f)))
            .collect::<Vec<_>>()
            .join(", ")
    }

    let mut out = String::from("-- gore-dump loc targets (generated by gore-cli) — do not edit by hand.\n");
    out.push_str("return {\n  fields_by_kind = {\n");
    out.push_str(&format!("    item = {{{}}},\n", field_list(ITEM_FIELDS)));
    out.push_str(&format!("    npc = {{{}}},\n", field_list(NPC_FIELDS)));
    out.push_str(&format!("    knowledge = {{{}}},\n", field_list(KNOWLEDGE_FIELDS)));
    out.push_str("  },\n  targets = {\n");
    for id in item_ids {
        out.push_str(&format!("    {{kind=\"item\", id=\"{}\"}},\n", lua_escape(id)));
    }
    for cls in npc_classes {
        out.push_str(&format!("    {{kind=\"npc\", id=\"{}\"}},\n", lua_escape(cls)));
    }
    for id in knowledge_ids {
        out.push_str(&format!("    {{kind=\"knowledge\", id=\"{}\"}},\n", lua_escape(id)));
    }
    out.push_str("  },\n}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn model() -> GuiModel {
        serde_json::from_value(json!({
            "classes": {
                "ItFo_Apple": {"fields": [
                    {"name": "m_Value", "type": "int"},
                    {"name": "m_Quality", "type": "enum", "enum_values": ["Low", "High"], "enum_value_ints": [0, 5]}
                ]},
                "NotInCatalog": {"fields": [{"name": "x", "type": "int"}]}
            }
        }))
        .unwrap()
    }

    #[test]
    fn renders_catalog_items_with_fields_and_enums() {
        let lua = render_items_lua(&model(), ["ItFo_Apple"].into_iter());
        assert!(lua.contains(r#"{id="ItFo_Apple", fields={"#));
        assert!(lua.contains(r#"{name="m_Value", type="int"},"#));
        assert!(lua.contains(
            r#"{name="m_Quality", type="enum", enum_values={"Low", "High"}, enum_value_ints={0, 5}},"#
        ));
        // valid Lua table delimiters
        assert!(lua.trim_end().ends_with('}'));
    }

    #[test]
    fn skips_classes_absent_from_catalog() {
        let lua = render_items_lua(&model(), ["ItFo_Apple"].into_iter());
        assert!(!lua.contains("NotInCatalog"));
    }

    #[test]
    fn main_lua_uses_the_proven_cdo_path_and_writes_json() {
        assert!(MAIN_LUA.contains(r#"StaticFindObject("/Script/Angelscript.Default__" .. cls.id)"#));
        assert!(MAIN_LUA.contains("gore_game_data.json"));
        assert!(MAIN_LUA.contains("ExecuteWithDelay"));
    }

    #[test]
    fn main_lua_emits_enum_backing_values() {
        // The in-game writer must copy enum_value_ints so sync can validate the
        // CDO's backing-value default against the real discriminants.
        assert!(MAIN_LUA.contains("f.enum_value_ints"));
        assert!(MAIN_LUA.contains(r#""enum_value_ints":["#));
    }

    #[test]
    fn main_lua_skips_non_finite_values() {
        // inf/nan are not valid JSON; the dumper must drop them.
        assert!(MAIN_LUA.contains("v == math.huge"));
        assert!(MAIN_LUA.contains("v ~= v"));
    }

    #[test]
    fn main_lua_registers_gore_dump_console_command() {
        assert!(MAIN_LUA.contains(r#"RegisterConsoleCommandHandler("gore-dump""#));
        // loc dump resolves FText to a string and writes a per-language file
        assert!(MAIN_LUA.contains(":ToString()"));
        assert!(MAIN_LUA.contains(r#""gore_loc_" .. label .. ".json""#));
    }

    #[test]
    fn main_lua_loc_is_manual_per_language_no_engine_switch() {
        // The engine language/culture does not drive the Alkimia loc, so the mod
        // must NOT try to switch it — it tags the dump with a caller label and
        // reads whatever the options menu language currently is.
        assert!(MAIN_LUA.contains("dump_loc(Parameters[2], kinds)"));
        assert!(MAIN_LUA.contains("safe_label"));
        assert!(!MAIN_LUA.contains("SetCurrentCulture"));
        assert!(!MAIN_LUA.contains("SetCurrentLanguage"));
    }

    #[test]
    fn loc_targets_groups_kinds_with_field_lists() {
        let lua = render_loc_targets_lua(
            ["ItFo_Apple"].into_iter(),
            ["CharacterDefinition_Human_Diego"].into_iter(),
            ["Choice123"].into_iter(),
        );
        assert!(lua.contains(r#"item = {"m_Name", "m_Description"}"#));
        assert!(lua.contains(r#"npc = {"m_Name", "m_CharacterName"}"#));
        assert!(lua.contains(r#"{kind="item", id="ItFo_Apple"}"#));
        assert!(lua.contains(r#"{kind="npc", id="CharacterDefinition_Human_Diego"}"#));
        assert!(lua.contains(r#"{kind="knowledge", id="Choice123"}"#));
        assert!(lua.trim_end().ends_with('}'));
    }
}
