use anyhow::{Context, Result};
use std::{fs, path::PathBuf};

pub fn run(mod_name: String, mods_dir: PathBuf) -> Result<()> {
    let mod_dir = mods_dir.join(&mod_name);
    let scripts_dir = mod_dir.join("Scripts");
    fs::create_dir_all(&scripts_dir)
        .with_context(|| format!("creating '{}'", scripts_dir.display()))?;

    // enabled.txt — UE4SS requires this file to load the mod
    fs::write(mod_dir.join("enabled.txt"), "")
        .context("writing enabled.txt")?;

    // main.lua — template with CDO pattern
    let main_lua = format!(
        r#"-- {name} — generated by gore-cli scaffold
-- Edit this file to apply CDO overrides at game load.
--
-- Example pattern (proven working):
--   local cdo = StaticFindObject("/Script/Angelscript.Default__ItFo_Apple")
--   if cdo and cdo:IsValid() then
--     local before = cdo.m_Value
--     cdo.m_Value = 500
--     print(string.format("[{name}] ItFo_Apple.m_Value %s -> %s\n",
--       tostring(before), tostring(cdo.m_Value)))
--   end
--
-- Use `gore-cli stubs` to generate LuaLS type stubs for autocomplete.
-- Require stubs: (add to your .luarc.json: {{ "workspace.library": ["path/to/stubs"] }})

local function apply()
  -- TODO: add your CDO overrides here
end

apply()
"#,
        name = mod_name
    );
    fs::write(scripts_dir.join("main.lua"), main_lua)
        .context("writing main.lua")?;

    println!("Created mod scaffold -> {}", mod_dir.display());
    Ok(())
}
