use anyhow::{Context, Result};
use std::{fs, path::PathBuf};

use crate::cmd::validate_mod_name;

pub fn run(mod_name: String, mods_dir: PathBuf) -> Result<()> {
    validate_mod_name(&mod_name)
        .with_context(|| format!("invalid mod name '{mod_name}'"))?;
    let mod_dir = mods_dir.join(&mod_name);
    let scripts_dir = mod_dir.join("Scripts");
    fs::create_dir_all(&scripts_dir)
        .with_context(|| format!("creating '{}'", scripts_dir.display()))?;

    // enabled.txt — UE4SS requires this file to load the mod
    fs::write(mod_dir.join("enabled.txt"), "")
        .context("writing enabled.txt")?;

    // main.lua — template with CDO pattern
    let main_lua = format!(
        r#"-- {name} — generated by gore-cli scaffold
-- Edit this file to apply CDO overrides at game load.
--
-- Example pattern (proven working):
--   local cdo = StaticFindObject("/Script/Angelscript.Default__ItFo_Apple")
--   if cdo and cdo:IsValid() then
--     local before = cdo.m_Value
--     cdo.m_Value = 500
--     print(string.format("[{name}] ItFo_Apple.m_Value %s -> %s\n",
--       tostring(before), tostring(cdo.m_Value)))
--   end
--
-- Use `gore-cli stubs` to generate LuaLS type stubs for autocomplete.
-- Require stubs: (add to your .luarc.json: {{ "workspace.library": ["path/to/stubs"] }})

-- gore-lua SDK loader (require + robust loadfile fallback)
local ok, gore = pcall(require, "gorelib")
if not ok or not gore then
    local f = loadfile("ue4ss/Mods/shared/gorelib/gorelib.lua")
    if f then gore = f() end
end
-- use gore.* helpers below; see `gorehelp` in-game or projects/gore-lua/README.md

local function apply()
  -- TODO: add your CDO overrides here
end

apply()
"#,
        name = mod_name
    );
    fs::write(scripts_dir.join("main.lua"), main_lua)
        .context("writing main.lua")?;

    println!("Created mod scaffold -> {}", mod_dir.display());
    Ok(())
}
