import 'dart:convert';

import '../core/mod_ffi.dart';

/// Immutable identity projected from one newly-created empty revision-3 project.
final class Revision3ProjectBootstrapIdentity {
  const Revision3ProjectBootstrapIdentity._({
    required this.projectId,
    required this.revision,
    required this.name,
    required this.version,
    required this.author,
    required this.authoringLocales,
  });

  final String projectId;
  final int revision;
  final String name;
  final String version;
  final String author;
  final List<String> authoringLocales;
}

/// Exact executable-generation facts copied from the trusted Story catalog.
final class Revision3ProjectBootstrapTarget {
  const Revision3ProjectBootstrapTarget._({
    required this.edition,
    required this.executableByteLength,
    required this.executableSha256,
  });

  final String edition;
  final int executableByteLength;
  final String executableSha256;
}

/// Canonical empty managed-project document plus facts a creator must verify
/// after the managed store reopens it.
///
/// This helper is filesystem-free. It does not build, deploy, or runtime-qualify
/// the project.
final class Revision3ProjectBootstrap {
  const Revision3ProjectBootstrap._({
    required this.canonicalProjectJson,
    required this.identity,
    required this.target,
  });

  static const int format = 2;
  static const int schemaRevision = 3;
  static const int initialRevision = 0;
  static const int maxNameUtf8Bytes = 256;
  static const int maxVersionUtf8Bytes = 128;
  static const int maxAuthorUtf8Bytes = 256;
  static const int maxAuthoringLocales = 64;

  /// Creates one deterministic, byte-canonical empty revision-3 document.
  ///
  /// [projectId] must already have been generated by a cryptographically secure
  /// caller. This boundary verifies only its canonical non-zero 128-bit shape.
  factory Revision3ProjectBootstrap.create({
    required AuthoringStoryCatalogGeneration generation,
    required String projectId,
    required String name,
    required String version,
    required String author,
    Iterable<String> authoringLocales = const <String>[],
  }) {
    _requireProjectId(projectId);
    _requireMetadata(name, maxNameUtf8Bytes, 'project name');
    _requireMetadata(version, maxVersionUtf8Bytes, 'project version');
    _requireMetadata(author, maxAuthorUtf8Bytes, 'project author');
    final locales = _canonicalLocales(authoringLocales);
    final target = _validatedTarget(generation);
    final identity = Revision3ProjectBootstrapIdentity._(
      projectId: projectId,
      revision: initialRevision,
      name: name,
      version: version,
      author: author,
      authoringLocales: locales,
    );
    final canonicalProjectJson = jsonEncode(<String, Object?>{
      'format': format,
      'schema_revision': schemaRevision,
      'project_id': identity.projectId,
      'revision': identity.revision,
      'meta': <String, Object?>{
        'name': identity.name,
        'version': identity.version,
        'author': identity.author,
      },
      'target': <String, Object?>{
        'executable': <String, Object?>{
          'byte_len': target.executableByteLength,
          'sha256': target.executableSha256,
        },
      },
      'authoring_locales': identity.authoringLocales,
      'entities': <String, Object?>{},
      'asset_store': <String, Object?>{'assets': <String, Object?>{}},
    });
    return Revision3ProjectBootstrap._(
      canonicalProjectJson: canonicalProjectJson,
      identity: identity,
      target: target,
    );
  }

  final String canonicalProjectJson;
  final Revision3ProjectBootstrapIdentity identity;
  final Revision3ProjectBootstrapTarget target;
}

final RegExp _projectIdPattern = RegExp(r'^[0-9a-f]{32}$');
final RegExp _sha256Pattern = RegExp(r'^[0-9a-f]{64}$');
const String _zeroSha256 =
    '0000000000000000000000000000000000000000000000000000000000000000';

typedef _SupportedStoryGeneration = ({
  String edition,
  int executableByteLength,
  String executableSha256,
  int shippingCacheByteLength,
  String shippingCacheSha256,
  int bindsCacheByteLength,
  String bindsCacheSha256,
});

const List<_SupportedStoryGeneration> _supportedStoryGenerations = [
  (
    edition: 'g1r-steam',
    executableByteLength: 171698176,
    executableSha256:
        'f406f969d3e73b6e58ea6e7aa10df7380318d97e7974d3be6e5a01183a4524f5',
    shippingCacheByteLength: 123394250,
    shippingCacheSha256:
        '1018f1cfe6b99a650eecb33afb96752d691d2088ead27808971b812f04ecb4c2',
    bindsCacheByteLength: 5903938,
    bindsCacheSha256:
        '46e6629ad5cacc112b9922d48a1aa948f40572d7285705b981c3eca3dc615fea',
  ),
  (
    edition: 'g1r-steam',
    executableByteLength: 171704320,
    executableSha256:
        'b52cd0453ad03987b833f7f26d09a2075109f18d653b8d4ff95271c857139e5d',
    shippingCacheByteLength: 123394250,
    shippingCacheSha256:
        '757d8624f0c7480f63cc14a1ba2d7e43f461a529064b0c0cfbf523a54639e385',
    bindsCacheByteLength: 5903938,
    bindsCacheSha256:
        '46e6629ad5cacc112b9922d48a1aa948f40572d7285705b981c3eca3dc615fea',
  ),
  (
    edition: 'g1r-steam',
    executableByteLength: 171787776,
    executableSha256:
        'ab2c8d9e286a437bc5343748faf40959a77e9dc7c542ff9361f1ffaeca5c811c',
    shippingCacheByteLength: 124352336,
    shippingCacheSha256:
        '36124f1cdd4caae555423581aa40631af0ac80d5cef42528382739f932b0e728',
    bindsCacheByteLength: 5908587,
    bindsCacheSha256:
        '854f58a695d0170144957f085c1e8c0f9ef40b271e35e90f79ffbccff8d999c5',
  ),
  (
    edition: 'g1r-steam',
    executableByteLength: 171792384,
    executableSha256:
        '824fbc94f2ac7f45927a0754605666c37af862d66156a15f8bf6813759d9e8e0',
    shippingCacheByteLength: 124459412,
    shippingCacheSha256:
        '7a18f954e32af30fc24ae3a66ea35d3b5cb98560c8f5083c7846fc9ce1d77511',
    bindsCacheByteLength: 5908985,
    bindsCacheSha256:
        'aa73402c11d4007035a2df32c55e50086a6d9c5b6da8619cdfcb4df53f02cea2',
  ),
];

void _requireProjectId(String value) {
  if (value.length != 32 ||
      !_projectIdPattern.hasMatch(value) ||
      value == '00000000000000000000000000000000') {
    throw const FormatException(
      'ProjectId must be one non-zero lowercase 128-bit identifier',
    );
  }
}

void _requireMetadata(String value, int maxBytes, String context) {
  if (value.isEmpty || value.trim() != value) {
    throw FormatException('$context must be non-empty and trimmed');
  }
  _boundedUtf8Length(value, maxBytes, context);
  for (final rune in value.runes) {
    if (rune < 0x20 || (rune >= 0x7f && rune <= 0x9f)) {
      throw FormatException('$context contains a control character');
    }
  }
}

List<String> _canonicalLocales(Iterable<String> values) {
  final locales = <String>[];
  final seen = <String>{};
  for (final value in values) {
    if (locales.length >= Revision3ProjectBootstrap.maxAuthoringLocales) {
      throw const FormatException(
        'authoring locale count exceeds its 64-entry limit',
      );
    }
    _requireCanonicalLocale(value);
    if (!seen.add(value)) {
      throw FormatException('duplicate authoring locale: $value');
    }
    locales.add(value);
  }
  locales.sort();
  return List<String>.unmodifiable(locales);
}

Revision3ProjectBootstrapTarget _validatedTarget(
  AuthoringStoryCatalogGeneration generation,
) {
  final executable = generation.executable;
  if (generation.edition.isEmpty ||
      generation.edition.trim() != generation.edition ||
      executable.byteLength <= 0 ||
      executable.byteLength > 0x7fffffffffffffff ||
      executable.sha256.length != 64 ||
      !_sha256Pattern.hasMatch(executable.sha256) ||
      executable.sha256 == _zeroSha256) {
    throw const FormatException(
      'Story catalog generation has an invalid executable seal',
    );
  }
  final supported = _supportedStoryGenerations.any(
    (candidate) =>
        generation.edition == candidate.edition &&
        executable.byteLength == candidate.executableByteLength &&
        executable.sha256 == candidate.executableSha256 &&
        generation.shippingCache.byteLength ==
            candidate.shippingCacheByteLength &&
        generation.shippingCache.sha256 == candidate.shippingCacheSha256 &&
        generation.bindsCache.byteLength == candidate.bindsCacheByteLength &&
        generation.bindsCache.sha256 == candidate.bindsCacheSha256,
  );
  if (!supported) {
    throw const FormatException(
      'Story catalog generation is not an exact supported generation triple',
    );
  }
  return Revision3ProjectBootstrapTarget._(
    edition: generation.edition,
    executableByteLength: executable.byteLength,
    executableSha256: executable.sha256,
  );
}

void _requireCanonicalLocale(String value) {
  if (value.isEmpty || value.length > 35 || !value.codeUnits.every(_isAscii)) {
    throw FormatException('authoring locale is not bounded ASCII: $value');
  }
  final segments = value.split('-');
  final language = segments.first;
  if (language.length < 2 || language.length > 8 || !_allAsciiLower(language)) {
    throw FormatException('authoring locale has an invalid language: $value');
  }
  final canonical = StringBuffer(language);
  for (var index = 1; index < segments.length; index++) {
    final segment = segments[index];
    if (segment.isEmpty ||
        segment.length > 8 ||
        !_allAsciiAlphanumeric(segment)) {
      throw FormatException('authoring locale has an invalid segment: $value');
    }
    canonical.write('-');
    if (segment.length == 4 && _allAsciiAlphabetic(segment)) {
      canonical.write(
        '${segment[0].toUpperCase()}${segment.substring(1).toLowerCase()}',
      );
    } else if (segment.length == 2 && _allAsciiAlphabetic(segment)) {
      canonical.write(segment.toUpperCase());
    } else {
      canonical.write(segment.toLowerCase());
    }
  }
  if (canonical.toString() != value) {
    throw FormatException('authoring locale is not canonical: $value');
  }
}

bool _isAscii(int unit) => unit <= 0x7f;

bool _allAsciiLower(String value) =>
    value.codeUnits.every((unit) => unit >= 0x61 && unit <= 0x7a);

bool _allAsciiAlphabetic(String value) => value.codeUnits.every(
  (unit) => (unit >= 0x41 && unit <= 0x5a) || (unit >= 0x61 && unit <= 0x7a),
);

bool _allAsciiAlphanumeric(String value) => value.codeUnits.every(
  (unit) =>
      (unit >= 0x30 && unit <= 0x39) ||
      (unit >= 0x41 && unit <= 0x5a) ||
      (unit >= 0x61 && unit <= 0x7a),
);

int _boundedUtf8Length(String value, int maxBytes, String context) {
  var length = 0;
  for (var index = 0; index < value.length; index++) {
    final unit = value.codeUnitAt(index);
    final int width;
    if (unit <= 0x7f) {
      width = 1;
    } else if (unit <= 0x7ff) {
      width = 2;
    } else if (unit >= 0xd800 && unit <= 0xdbff) {
      if (index + 1 >= value.length) {
        throw FormatException('$context contains malformed UTF-16');
      }
      final low = value.codeUnitAt(index + 1);
      if (low < 0xdc00 || low > 0xdfff) {
        throw FormatException('$context contains malformed UTF-16');
      }
      index++;
      width = 4;
    } else if (unit >= 0xdc00 && unit <= 0xdfff) {
      throw FormatException('$context contains malformed UTF-16');
    } else {
      width = 3;
    }
    length += width;
    if (length > maxBytes) {
      throw FormatException('$context exceeds its $maxBytes-byte limit');
    }
  }
  return length;
}
