//! `gore doctor` — one read-only pass over the setup that says what is installed and what is
//! wrong with it.
//!
//! # Why this exists
//!
//! Every other command in this CLI answers a question about the one thing it was pointed at.
//! Nothing answered "what is my setup". A tester who built a working item override, deployed it,
//! and then saw nothing in the game had to open PowerShell and walk the install by hand before he
//! found the cause — UE4SS was not installed. No command would have told him: `gore mod deploy`
//! creates `ue4ss\Mods\` itself when it is missing, so a deploy that reports success proves the
//! files were written and nothing else. His verdict on the toolkit was "for building, yes; for
//! repairing, no", and that is the gap this command closes.
//!
//! # Reuse, not a second opinion
//!
//! Every check here answers with the same helper the command it diagnoses uses: the game root
//! through [`gore_loc::config::game_root`] (so the reported root is the one every other command
//! resolves), the install layout through [`gore_mod::resolve_game_paths`], the `~mods` folder
//! through [`gore_tex::container::mods_dir`], the deployment through
//! [`gore_mod::mgr::status::status`] (what `gore mgr status` prints), the install-mutation lock
//! and gore-as recovery artifacts through [`gore_as::compile::probe_install_compile_state`] (what
//! deploy and `as compile` consult before they refuse), and the localized-text catalog through
//! [`gore_loc::loc_store::status`] (what `gore loc status` prints). A doctor that disagreed with
//! the commands it diagnoses would be worse than no doctor at all.
//!
//! Nothing in this module writes, creates, or removes anything.

use anyhow::Result;
use serde::Serialize;
use std::path::{Path, PathBuf};

use gore_as::compile::{
    InstallCompileGameProcessDisposition, InstallCompileStateDisposition, InstallCompileStateProbe,
};
use gore_loc::loc_store::LocMeta;
use gore_mod::mgr::status::ManagerStatus;
use gore_mod::GamePaths;

/// Width of the verdict column; `problem` is the longest word plus one space.
const VERDICT_WIDTH: usize = 8;
/// Width of the check-title column.
const TITLE_WIDTH: usize = 14;

/// How many names an enumerating check PRINTS before it says how many more there are. A doctor
/// that dumps 300 pak files at someone is a doctor nobody reads to the end of.
///
/// Applied at print time only: `--json` carries every item, because a cap is a decision about a
/// person's screen and an "… and 10 more" string is not something a caller can parse.
const MAX_LISTED: usize = 12;

/// First line of every `main.lua` [`gore_modgen::gen::gen_lua`] writes, and therefore the only
/// evidence on disk that a UE4SS mod folder holds GORE-generated overrides rather than somebody
/// else's Lua. Matched as a prefix, stopping before the em dash, so the marker stays ASCII.
/// `gen_lua_still_writes_the_marker_this_module_looks_for` pins it to the generator.
const GENERATED_MARKER: &str = "-- Generated by gore-cli";

/// How much of a `main.lua` is read to look for [`GENERATED_MARKER`]. A mod folder can hold
/// anything, and this check is a diagnosis, not a reason to pull an arbitrary file into memory.
const MARKER_PROBE_BYTES: usize = 128;

/// What one check found, ordered from "nothing to do" to "this is the fault".
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
enum Verdict {
    /// Checked, and there is nothing to do about it.
    Ok,
    /// True and worth knowing, but not a fault: the game left running, a mod that is merely
    /// disabled, a catalog extracted from another install.
    Note,
    /// A reason a mod would silently do nothing, or a mess somebody has to clean up.
    Problem,
    /// Not answerable, because something this check reads is not there. Always accompanied by the
    /// check that reported the missing thing.
    Skipped,
}

impl Verdict {
    fn label(self) -> &'static str {
        match self {
            Verdict::Ok => "ok",
            Verdict::Note => "note",
            Verdict::Problem => "problem",
            Verdict::Skipped => "skipped",
        }
    }
}

/// One line of the report: what was looked at, what was found, and — when something is wrong —
/// what to do about it.
#[derive(Serialize)]
struct Check {
    /// Stable key for `--json`. Never renamed once shipped: a caller greps for it.
    id: &'static str,
    /// Column heading in the human report.
    title: &'static str,
    verdict: Verdict,
    /// One line, the finding itself.
    detail: String,
    /// Enumerated evidence (mod folders, leftover files), printed indented under `detail`.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    items: Vec<String>,
    /// What to do next. Present exactly when the verdict is not `ok`, so a reader can act on the
    /// report without leaving it to look a command up.
    #[serde(skip_serializing_if = "Option::is_none")]
    fix: Option<String>,
}

impl Check {
    fn new(id: &'static str, title: &'static str, verdict: Verdict, detail: impl Into<String>) -> Self {
        Self {
            id,
            title,
            verdict,
            detail: detail.into(),
            items: Vec::new(),
            fix: None,
        }
    }

    fn with_items(mut self, items: Vec<String>) -> Self {
        self.items = items;
        self
    }

    fn with_fix(mut self, fix: impl Into<String>) -> Self {
        self.fix = Some(fix.into());
        self
    }
}

/// The whole report. The counts are at the top level so a `--json` caller can gate on them without
/// walking `checks`.
#[derive(Serialize)]
struct Report {
    /// Resolved install root, absent when nothing resolved.
    #[serde(skip_serializing_if = "Option::is_none")]
    game_root: Option<String>,
    /// Where that root came from: `--game`, `config`, or `auto-detect`.
    game_source: &'static str,
    ok: usize,
    note: usize,
    problem: usize,
    skipped: usize,
    checks: Vec<Check>,
}

impl Report {
    fn new(game_root: Option<&Path>, game_source: &'static str, checks: Vec<Check>) -> Self {
        let count = |want: Verdict| checks.iter().filter(|c| c.verdict == want).count();
        Self {
            game_root: game_root.map(|p| p.display().to_string()),
            game_source,
            ok: count(Verdict::Ok),
            note: count(Verdict::Note),
            problem: count(Verdict::Problem),
            skipped: count(Verdict::Skipped),
            checks,
        }
    }
}

/// `gore doctor` exits 0 whenever it produced a report, however bad the news in it.
///
/// The alternative — non-zero as soon as any check is a problem — was rejected because of who runs
/// this command. It is reached by somebody whose mod did nothing, often through a wrapper, a GUI,
/// or an agent that reads a non-zero exit as "the command failed". Conflating "the doctor found
/// that UE4SS is missing" with "the doctor could not run" is precisely the confusion this command
/// exists to remove, and it would also make `gore doctor` fail on a perfectly healthy day, because
/// a game left running is worth a line and is not a fault. A caller that wants to gate on the
/// findings reads `--json`: every check carries its own verdict and the top level carries the
/// counts. The one non-zero exit is a doctor that could not write its own report.
pub fn run(game: Option<PathBuf>, json: bool) -> Result<()> {
    let report = collect(game.as_deref());
    if json {
        println!("{}", serde_json::to_string_pretty(&report)?);
    } else {
        print_report(&report);
    }
    Ok(())
}

/// Run every check. Ordered the way somebody debugs: where is the game, is it the right game, can
/// anything run a mod at all, what is deployed, what is left over, what is in the way.
fn collect(explicit: Option<&Path>) -> Report {
    let cfg = gore_loc::config::load();
    let source = game_path_source(explicit.is_some(), cfg.game_path.as_deref());
    let resolved = gore_loc::config::game_root(explicit.map(Path::to_path_buf)).ok();

    let mut checks = vec![check_game_path(explicit, cfg.game_path.as_deref(), resolved.as_deref())];

    // A root that resolved to nothing on disk is no more inspectable than one that did not
    // resolve, and running the rest against it would restate the same single cause as four more
    // problems — burying the one line that says what to fix.
    let Some(root) = resolved.filter(|root| root.is_dir()) else {
        // Every remaining check reads the install. Say so once per check rather than dropping
        // them: a report that silently shrinks looks like a report that found less to say.
        for (id, title) in SKIPPED_WITHOUT_INSTALL {
            checks.push(Check::new(
                id,
                title,
                Verdict::Skipped,
                "no install to look at",
            ));
        }
        return Report::new(None, source, checks);
    };

    let gp = gore_mod::resolve_game_paths(&root);
    // One probe answers two checks — the running game and the leftover locks/journals — and
    // enumerating the process list twice could disagree with itself between the two lines.
    let probe = gore_as::compile::probe_install_compile_state(&gp.root);
    let record_present = gore_mod::deploy_record_path(&gp.root).is_file();

    checks.push(check_install(&gp));
    checks.push(check_ue4ss(&gp));
    checks.push(check_ue4ss_mods(&gp));
    checks.push(check_deployment(
        &gp,
        &gore_mod::mgr::paths::library_dir(),
        &gore_mod::mgr::paths::loadout_path(),
    ));
    checks.push(check_mods_folder(&gp));
    checks.push(check_leftovers(&gp, &probe, record_present));
    checks.push(check_game_process(&probe));
    checks.push(check_loc_catalog(
        gore_loc::loc_store::status(),
        gp.lcache.as_deref(),
    ));

    Report::new(Some(&gp.root), source, checks)
}

/// The checks that cannot run without a resolved install, in report order. Kept next to `collect`
/// so a check added below is either listed here or is a check that never reads the game.
const SKIPPED_WITHOUT_INSTALL: &[(&str, &str)] = &[
    ("install", "install"),
    ("ue4ss", "UE4SS"),
    ("ue4ss_mods", "UE4SS mods"),
    ("deployment", "deployment"),
    ("mods_folder", "~mods"),
    ("leftovers", "leftovers"),
    ("game_process", "game process"),
    ("loc_catalog", "loc catalog"),
];

/// Where the resolved game root came from, in `gore config list`'s own words plus the one source
/// that command cannot have (an explicit `--game`).
///
/// Pure, and deliberately a copy of nothing: both this and `config list` treat a blank or
/// whitespace-only `game_path` as unset because [`gore_loc::config::game_root`] does, so a config
/// file holding `""` is reported as auto-detected rather than as configured. A doctor that named a
/// different source than `gore config list` would send someone to edit the wrong thing.
fn game_path_source(explicit: bool, configured: Option<&str>) -> &'static str {
    if explicit {
        "--game"
    } else if configured.is_some_and(|value| !value.trim().is_empty()) {
        "config"
    } else {
        "auto-detect"
    }
}

fn check_game_path(
    explicit: Option<&Path>,
    configured: Option<&str>,
    resolved: Option<&Path>,
) -> Check {
    let mut items = vec![format!(
        "config file: {}",
        gore_loc::config::config_path().display()
    )];
    if let Some(value) = configured {
        items.push(format!("game-path = {value}"));
    }
    let source = game_path_source(explicit.is_some(), configured);

    let Some(root) = resolved else {
        return Check::new(
            "game_path",
            "game path",
            Verdict::Problem,
            "no game path set, and no Steam install was auto-detected",
        )
        .with_items(items)
        .with_fix(
            "run 'gore config detect' to find a Steam install, or \
             'gore config set game-path <path>' to name it yourself",
        );
    };

    if !root.is_dir() {
        return Check::new(
            "game_path",
            "game path",
            Verdict::Problem,
            format!("{} (source: {source}) does not exist", root.display()),
        )
        .with_items(items)
        .with_fix(
            "the path resolved but there is no directory there — the game moved, or the drive is \
             not mounted. Set it again with 'gore config set game-path <path>'",
        );
    }

    Check::new(
        "game_path",
        "game path",
        Verdict::Ok,
        format!("{} (source: {source})", root.display()),
    )
    .with_items(items)
}

/// Does the resolved root actually hold a Gothic 1 Remake install?
///
/// The four entries below are the ones the rest of the toolkit resolves against: the shipping
/// executable, the pak folder that carries `~mods`, the localization cache folder, and the script
/// folder. `resolve_game_paths` builds all of them off `<root>\G1R`, so this joins the same child
/// rather than counting ancestors off one of its fields.
fn check_install(gp: &GamePaths) -> Check {
    let g1r = gp.root.join("G1R");
    let required: [(&str, PathBuf, bool); 4] = [
        (
            r"G1R\Binaries\Win64\G1R-Win64-Shipping.exe",
            gp.executable.clone(),
            false,
        ),
        (r"G1R\Content\Paks", g1r.join("Content").join("Paks"), true),
        (r"G1R\Story\Cache", g1r.join("Story").join("Cache"), true),
        (r"G1R\Script", g1r.join("Script"), true),
    ];

    let missing: Vec<String> = required
        .iter()
        .filter(|(_, path, want_dir)| {
            if *want_dir {
                !path.is_dir()
            } else {
                !path.is_file()
            }
        })
        .map(|(label, _, _)| (*label).to_string())
        .collect();

    if missing.is_empty() {
        return Check::new(
            "install",
            "install",
            Verdict::Ok,
            "looks like Gothic 1 Remake (executable, Paks, Story\\Cache and Script all present)",
        );
    }

    // The executable is the one entry whose absence means "this is not the game"; the others can
    // be missing from a partial or verifying install, which is a different sentence.
    let exe_missing = missing.iter().any(|m| m.ends_with(".exe"));
    let detail = if exe_missing {
        format!(
            "does not look like a Gothic 1 Remake install (missing: {})",
            missing.join(", ")
        )
    } else {
        format!("install is incomplete (missing: {})", missing.join(", "))
    };
    Check::new("install", "install", Verdict::Problem, detail).with_fix(if exe_missing {
        "point GORE at the folder that CONTAINS G1R\\, not at G1R\\ itself or a Steam library: \
         'gore config set game-path <path>' (or 'gore config detect')"
    } else {
        "verify the game files in Steam; commands that read these folders will fail until they \
         are back"
    })
}

/// `<install>\G1R\Binaries\Win64\ue4ss` and its parts.
///
/// This is the check the whole command was written for. Item and stat overrides are Lua that only
/// UE4SS runs, GORE does not install it, and `gore mod deploy` creates the `Mods\` directory
/// itself — so the presence of `Mods\` proves a deploy happened, never that anything will load
/// what it put there.
fn check_ue4ss(gp: &GamePaths) -> Check {
    let ue4ss = ue4ss_dir(gp);
    let dll = ue4ss.join("UE4SS.dll");
    let mods = &gp.ue4ss_mods;

    if !ue4ss.is_dir() {
        return Check::new(
            "ue4ss",
            "UE4SS",
            Verdict::Problem,
            format!("not installed: there is no {}", ue4ss.display()),
        )
        .with_fix(
            "item and stat overrides are Lua, and UE4SS is the loader that runs it — without it a \
             deployed override mod sits in the install doing nothing and no command reports a \
             problem. Install UE4SS into that folder; GORE does not ship or install it. See the \
             UE4SS section of docs\\guide\\getting-started.md",
        );
    }

    if !dll.is_file() {
        // The folder without the DLL is the shape `gore mod deploy` leaves behind on an install
        // that never had UE4SS: it creates ue4ss\Mods\ to put the mod in, and nothing else.
        return Check::new(
            "ue4ss",
            "UE4SS",
            Verdict::Problem,
            format!(
                "{} exists but has no UE4SS.dll, so nothing loads the mods in it",
                ue4ss.display()
            ),
        )
        .with_items(vec![format!(
            "Mods\\: {}",
            if mods.is_dir() {
                "present (a gore deploy creates it, so this proves nothing about UE4SS)"
            } else {
                "not there"
            }
            .to_string()
        )])
        .with_fix(
            "install UE4SS into that folder (UE4SS.dll, UE4SS-settings.ini and Mods\\ sit beside \
             each other). See the UE4SS section of docs\\guide\\getting-started.md",
        );
    }

    let mut items = vec![format!("UE4SS.dll: {}", dll.display())];
    let settings = ue4ss.join("UE4SS-settings.ini");
    if !settings.is_file() {
        items.push("UE4SS-settings.ini: not there".to_string());
    }
    let log = ue4ss.join("UE4SS.log");
    if log.is_file() {
        // The only machine-readable evidence that an override actually applied, and the first
        // thing to read when a mod is deployed and the game shows nothing.
        items.push(format!("UE4SS.log: {}", log.display()));
    }

    if !mods.is_dir() {
        return Check::new(
            "ue4ss",
            "UE4SS",
            Verdict::Note,
            format!("installed, but there is no {} yet", mods.display()),
        )
        .with_items(items)
        .with_fix("'gore mod deploy' and 'gore gen -o <mods dir>' both create it");
    }

    Check::new(
        "ue4ss",
        "UE4SS",
        Verdict::Ok,
        format!("installed at {}", ue4ss.display()),
    )
    .with_items(items)
}

/// One UE4SS mod folder as this report sees it.
struct Ue4ssMod {
    name: String,
    /// UE4SS loads a folder because an `enabled.txt` sits in it; that empty file is the switch.
    enabled: bool,
    /// Its `Scripts\main.lua` starts with [`GENERATED_MARKER`], so GORE wrote it.
    generated: bool,
}

/// What is in `ue4ss\Mods\`, and which of it will run.
///
/// The case worth catching here happened during the blind tests: a mod folder left enabled from an
/// earlier session competes with the new one for the same class default. Both apply, the later
/// loader wins, nothing anywhere says so, and the value in the game is the one nobody asked for.
/// Only GORE-generated folders are counted for that warning — UE4SS ships enabled mods of its own,
/// and warning about those would fire on every healthy install.
fn check_ue4ss_mods(gp: &GamePaths) -> Check {
    let mods = &gp.ue4ss_mods;
    if !mods.is_dir() {
        return Check::new(
            "ue4ss_mods",
            "UE4SS mods",
            Verdict::Skipped,
            format!("no {}", mods.display()),
        );
    }

    // A folder that exists and cannot be read is reported as unread. "No mod folders" is the answer
    // that hides a competing override mod, which is the thing this check is for.
    let found = match read_ue4ss_mods(mods) {
        Ok(found) => found,
        Err(error) => {
            return Check::new(
                "ue4ss_mods",
                "UE4SS mods",
                Verdict::Problem,
                format!("could not inspect the UE4SS mod folder: {error}"),
            )
            .with_fix("run the same command from a shell that can read the install")
        }
    };
    if found.is_empty() {
        return Check::new(
            "ue4ss_mods",
            "UE4SS mods",
            Verdict::Ok,
            "no mod folders in ue4ss\\Mods",
        );
    }

    let enabled = found.iter().filter(|m| m.enabled).count();
    let items = found
        .iter()
        .map(|m| {
            format!(
                "{} [{}]{}",
                m.name,
                if m.enabled { "enabled" } else { "disabled" },
                if m.generated { " gore override" } else { "" }
            )
        })
        .collect();

    let competing: Vec<&Ue4ssMod> = found
        .iter()
        .filter(|m| m.enabled && m.generated)
        .collect();
    let detail = format!("{} mod folder(s), {enabled} enabled", found.len());

    if competing.len() > 1 {
        let names: Vec<&str> = competing.iter().map(|m| m.name.as_str()).collect();
        return Check::new("ue4ss_mods", "UE4SS mods", Verdict::Problem, detail)
            .with_items(items)
            .with_fix(format!(
                "{} GORE-generated override mods are enabled at once ({}). If two of them set the \
                 same class default, the one UE4SS loads last wins and neither the log nor the \
                 game says which. Delete the folder you are not using, or delete its enabled.txt",
                competing.len(),
                names.join(", ")
            ));
    }

    Check::new("ue4ss_mods", "UE4SS mods", Verdict::Ok, detail).with_items(items)
}

/// Directories under `Mods\`, sorted, with `shared` left out: that is the gore-lua SDK namespace
/// `gore deploy-shared` installs for other mods to `require`, not a mod, and it has no enabled.txt
/// by design.
///
/// A directory that cannot be read is reported rather than counted as empty. "No mod folders" is
/// exactly the answer that hides a competing override mod, and this check exists to find those.
fn read_ue4ss_mods(mods: &Path) -> Result<Vec<Ue4ssMod>, String> {
    let entries = std::fs::read_dir(mods)
        .map_err(|error| format!("{} could not be read: {error}", mods.display()))?;
    let entries = entries
        .collect::<std::io::Result<Vec<_>>>()
        .map_err(|error| format!("{} could not be read: {error}", mods.display()))?;
    let mut found: Vec<Ue4ssMod> = Vec::new();
    for entry in entries {
        if !entry.path().is_dir() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.eq_ignore_ascii_case("shared") {
            continue;
        }
        let dir = entry.path();
        found.push(Ue4ssMod {
            enabled: dir.join("enabled.txt").is_file(),
            // Propagated rather than defaulted: a marker that cannot be read is not a mod that
            // carries no overrides, and treating it as one is how a competing generated override
            // would disappear from a report whose whole job is to find it.
            generated: is_generated_override_mod(&dir)?,
            name,
        });
    }
    // Enabled first, then by name. A UE4SS install carries a couple of dozen folders and the
    // listing is capped, so plain alphabetical order would spend the whole cap on the disabled
    // stock mods and cut off the handful that actually run — which is the only part anyone asked
    // about.
    found.sort_by_key(|m| (!m.enabled, m.name.to_lowercase()));
    Ok(found)
}

/// Was this mod folder's `Scripts\main.lua` written by `gore gen` / `gore mod build`?
/// `Ok(false)` means the file was read and carries no marker. `Err` means it could not be read,
/// which is not the same answer: reporting it as "not generated" is how two competing generated
/// overrides and one unreadable marker came back as a clean verdict.
fn is_generated_override_mod(dir: &Path) -> Result<bool, String> {
    use std::io::Read;
    let marker = dir.join("Scripts").join("main.lua");
    let mut file = match std::fs::File::open(&marker) {
        Ok(file) => file,
        // No `main.lua` at all is a real answer: this folder holds no generated overrides.
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(false),
        Err(error) => return Err(format!("{} could not be read: {error}", marker.display())),
    };
    let mut head = [0u8; MARKER_PROBE_BYTES];
    let read = file
        .read(&mut head)
        .map_err(|error| format!("{} could not be read: {error}", marker.display()))?;
    Ok(String::from_utf8_lossy(&head[..read]).starts_with(GENERATED_MARKER))
}

/// Is anything deployed, and is it still what was deployed?
///
/// This is `gore mgr status`, called the same way with the same shared library and loadout, so the
/// two never say different things about the same install. It reads and hashes the files the record
/// claims, which is why it is the slowest line in the report — and why it can report the case a
/// bare "a record exists" could not: a Steam update or integrity verify that quietly put the
/// pristine file back underneath a deployment that still looks active.
fn check_deployment(gp: &GamePaths, library: &Path, loadout_path: &Path) -> Check {
    let record = gore_mod::deploy_record_path(&gp.root);
    let items = vec![
        format!("record:  {}", record.display()),
        format!("library: {}", library.display()),
        format!("loadout: {}", loadout_path.display()),
    ];

    let target = match gore_mod::mgr::loadout::load(loadout_path) {
        Ok(loadout) => loadout,
        Err(error) => {
            return Check::new(
                "deployment",
                "deployment",
                Verdict::Problem,
                format!("the manager loadout could not be read: {error}"),
            )
            .with_items(items)
            .with_fix(format!(
                "delete or repair {} — every 'gore mgr' command reads it first",
                loadout_path.display()
            ));
        }
    };

    match gore_mod::mgr::status::status(&gp.root, library, &target) {
        Ok(ManagerStatus::NothingDeployed) => Check::new(
            "deployment",
            "deployment",
            Verdict::Ok,
            "nothing is deployed (no deploy record in the install)",
        )
        .with_items(items),
        Ok(ManagerStatus::StudioDeployActive { mod_name }) => Check::new(
            "deployment",
            "deployment",
            Verdict::Ok,
            format!("one bundle is deployed: {mod_name}"),
        )
        .with_items(items),
        Ok(ManagerStatus::InSync { loadout }) => Check::new(
            "deployment",
            "deployment",
            Verdict::Ok,
            format!(
                "the manager loadout is deployed and in sync ({} mod(s))",
                loadout.len()
            ),
        )
        .with_items(items),
        Ok(ManagerStatus::ChangesPending { deployed, target }) => Check::new(
            "deployment",
            "deployment",
            Verdict::Note,
            format!(
                "{} mod(s) are deployed but the loadout now names {} — the game does not have \
                 your latest change",
                deployed.len(),
                target.len()
            ),
        )
        .with_items(items)
        .with_fix("run 'gore mgr apply' to put the current loadout into the game"),
        Ok(ManagerStatus::GameUpdated { drifted }) => Check::new(
            "deployment",
            "deployment",
            Verdict::Problem,
            format!(
                "{} deployed file(s) were changed outside GORE — a Steam update or an integrity \
                 verify has put the game's own version back",
                drifted.len()
            ),
        )
        .with_items(drifted.clone())
        .with_fix(
            "this is the case where the tool reported success and the game shows nothing. Run \
             'gore mgr apply' (or re-deploy the bundle) to rebuild against the refreshed files",
        ),
        Ok(ManagerStatus::RecoveryRequired) => Check::new(
            "deployment",
            "deployment",
            Verdict::Problem,
            "a previous deploy was interrupted and the install is half-changed",
        )
        .with_items(items)
        .with_fix(
            "run 'gore mgr reset' (or 'gore mod undeploy') to restore the game before deploying \
             anything else",
        ),
        Err(error) => Check::new(
            "deployment",
            "deployment",
            Verdict::Problem,
            format!("the deploy record could not be read: {error}"),
        )
        .with_items(items),
    }
}

/// What is mounted from the game's additive override folder.
///
/// Texture and DataAsset mods leave a Zen triplet here instead of patching a game file, so this is
/// the only place they are visible, and a triplet from a deployment that was undeployed by hand
/// would still be mounted.
fn check_mods_folder(gp: &GamePaths) -> Check {
    let dir = gore_tex::container::mods_dir(&gp.root);
    if !dir.is_dir() {
        return Check::new(
            "mods_folder",
            "~mods",
            Verdict::Ok,
            format!("no {} (nothing additive is mounted)", dir.display()),
        );
    }
    let mut names = match file_names(&dir) {
        Ok(names) => names,
        Err(error) => {
            return Check::new(
                "mods_folder",
                "~mods",
                Verdict::Problem,
                format!("could not inspect the additive mod folder: {error}"),
            )
        }
    };
    names.sort_by_key(|name| name.to_lowercase());
    if names.is_empty() {
        return Check::new(
            "mods_folder",
            "~mods",
            Verdict::Ok,
            format!("{} is empty", dir.display()),
        );
    }
    Check::new(
        "mods_folder",
        "~mods",
        Verdict::Ok,
        format!("{} file(s) mounted from {}", names.len(), dir.display()),
    )
    .with_items(names)
}

/// Things in the install that should not still be there.
///
/// Two sources, because they are left by two different kinds of interruption: the install-mutation
/// lock, the gore-as compile lock, its recovery journal and its cache/JIT/proxy backups come from
/// [`gore_as::compile::probe_install_compile_state`] — the same probe deploy and `as compile`
/// consult before they refuse to start — and the `*.gore-bak` snapshots come from a scan of the
/// four folders this toolkit edits in place. A `*.gore-bak` is normal while something is deployed;
/// with no deploy record it means a game file is still modified and its pristine copy is sitting
/// next to it, which is exactly the state "I undeployed and the game still looks wrong" describes.
fn check_leftovers(
    gp: &GamePaths,
    probe: &InstallCompileStateProbe,
    record_present: bool,
) -> Check {
    let mut items: Vec<String> = probe
        .artifacts
        .iter()
        .map(|artifact| format!("{:?}: {}", artifact.kind, artifact.path))
        .collect();
    let artifact_count = items.len();

    // Same posture as the probe's own InspectionFailed below: a directory that cannot be read is
    // reported as unread, never as clean. This check exists to find leftovers, so answering "none"
    // because the scan failed is the one wrong answer it can give.
    let backups = match find_backups(gp) {
        Ok(backups) => backups,
        Err(error) => {
            return Check::new(
                "leftovers",
                "leftovers",
                Verdict::Problem,
                format!("could not scan for leftover backups: {error}"),
            )
            .with_items(items)
            .with_fix("run the same command from a shell that can read the install")
        }
    };
    let orphan_backups = !record_present && !backups.is_empty();
    items.extend(backups.iter().cloned());

    if probe.disposition == InstallCompileStateDisposition::InspectionFailed {
        // The probe fails closed; say which part it could not read rather than reporting a clean
        // install it never managed to look at.
        let why = probe
            .issues
            .first()
            .map(|issue| issue.message.clone())
            .unwrap_or_else(|| "the probe did not say".into());
        return Check::new(
            "leftovers",
            "leftovers",
            Verdict::Note,
            format!("the install could not be inspected in full: {why}"),
        )
        .with_items(items)
        .with_fix("run the same command from a shell that can read the install");
    }

    if artifact_count == 0 && backups.is_empty() {
        return Check::new(
            "leftovers",
            "leftovers",
            Verdict::Ok,
            "no locks, journals or leftover backups in the install",
        );
    }

    if artifact_count > 0 {
        return Check::new(
            "leftovers",
            "leftovers",
            Verdict::Problem,
            format!(
                "{artifact_count} lock/recovery artifact(s) are still in the install, so deploy \
                 and 'as compile' will refuse to start"
            ),
        )
        .with_items(items)
        .with_fix(
            "a GORE process was interrupted. Make sure none is running, then run \
             'gore mod undeploy' (or 'gore mgr reset') to finish the transaction it left open",
        );
    }

    if orphan_backups {
        return Check::new(
            "leftovers",
            "leftovers",
            Verdict::Note,
            format!(
                "{} *.gore-bak backup(s) with no deployment to belong to — a game file is \
                 probably still modified",
                backups.len()
            ),
        )
        .with_items(items)
        .with_fix(
            "these are the pristine bytes of files edited in place. Restore a bank with \
             'gore audio restore --bank <bank>', or re-run 'gore mod undeploy' if a deployment \
             was removed by hand",
        );
    }

    Check::new(
        "leftovers",
        "leftovers",
        Verdict::Ok,
        format!(
            "{} *.gore-bak backup(s), which is what an active deployment looks like",
            backups.len()
        ),
    )
    .with_items(items)
}

/// Is the game open right now?
fn check_game_process(probe: &InstallCompileStateProbe) -> Check {
    match probe.game_process {
        InstallCompileGameProcessDisposition::NotRunning => Check::new(
            "game_process",
            "game process",
            Verdict::Ok,
            "G1R-Win64-Shipping.exe is not running",
        ),
        InstallCompileGameProcessDisposition::Running => Check::new(
            "game_process",
            "game process",
            Verdict::Note,
            "G1R-Win64-Shipping.exe is running",
        )
        .with_fix(
            "deploy, undeploy and 'as compile' refuse to change an installation while the game \
             holds it open. Close the game before any of them",
        ),
        InstallCompileGameProcessDisposition::InspectionFailed => Check::new(
            "game_process",
            "game process",
            Verdict::Note,
            "could not tell whether the game is running",
        )
        .with_fix(
            "deploy and undeploy fail closed on this too, so they will refuse until the process \
             list can be read",
        ),
    }
}

/// Does the shared localized-text catalog still describe the installed `.lcache`?
///
/// `gore loc status` reports the source path and size the catalog was extracted from, and that can
/// disagree with the cache in the install — most often because `gore loc import` re-encrypted the
/// cache afterwards, which changes its size. Nothing breaks, but every tool that turns a text id
/// into text is then reading the text the game no longer has, which reads exactly like an edit
/// that did not take.
fn check_loc_catalog(meta: Option<LocMeta>, installed: Option<&Path>) -> Check {
    let Some(meta) = meta else {
        return Check::new(
            "loc_catalog",
            "loc catalog",
            Verdict::Note,
            "no localized-text catalog has been extracted",
        )
        .with_fix(
            "run 'gore loc extract' — the save editor, Mod Studio and 'gore loc' all read that \
             one shared catalog",
        );
    };

    let summary = format!(
        "{} ids in {} language(s)",
        meta.id_count,
        meta.languages.len()
    );
    let items = vec![
        format!("catalog: {}", meta.catalog_path),
        format!("source:  {} ({} bytes)", meta.source_path, meta.source_bytes),
    ];

    let Some(installed) = installed else {
        return Check::new(
            "loc_catalog",
            "loc catalog",
            Verdict::Note,
            format!("{summary}, but this install has no AlkimiaLocalization .lcache to compare it against"),
        )
        .with_items(items);
    };

    if !same_path(Path::new(&meta.source_path), installed) {
        return Check::new(
            "loc_catalog",
            "loc catalog",
            Verdict::Note,
            format!("{summary}, extracted from a different file than this install's cache"),
        )
        .with_items(
            items
                .into_iter()
                .chain([format!("installed: {}", installed.display())])
                .collect(),
        )
        .with_fix(
            "the catalog describes another install. Run 'gore loc extract' to re-extract from the \
             one you are pointed at",
        );
    }

    // Length alone cannot prove currency: `gore loc import` re-encrypts in place, and replacing a
    // string with one that encodes to the same number of bytes leaves the file exactly as long as
    // it was. The catalog carries no content hash to compare against — adding one would change the
    // shared format that Mod Studio and the save editor also read — so the modification time is the
    // second signal, and an unchanged length with an untouched mtime is reported as what it is:
    // nothing that looks changed, rather than proof of a match.
    let modified_after_extraction = |m: &std::fs::Metadata| {
        m.modified()
            .ok()
            .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
            .is_some_and(|since| since.as_secs() > meta.extracted_at)
    };

    match std::fs::metadata(installed) {
        Ok(m) if m.len() == meta.source_bytes && modified_after_extraction(&m) => Check::new(
            "loc_catalog",
            "loc catalog",
            Verdict::Problem,
            format!(
                "{summary}, but the installed cache has been written since the extraction — it is \
                 the same length, so what changed is its contents"
            ),
        )
        .with_items(items)
        .with_fix(
            "'gore loc import' re-encrypts the cache in place and can leave its length unchanged. \
             Run 'gore loc extract' so the shared catalog describes the text that is installed",
        ),
        Ok(m) if m.len() == meta.source_bytes => Check::new(
            "loc_catalog",
            "loc catalog",
            Verdict::Ok,
            format!("{summary}; the installed cache is unchanged in size and mtime since then"),
        )
        .with_items(items),
        Ok(m) => {
            let live = m.len();
            Check::new(
            "loc_catalog",
            "loc catalog",
            Verdict::Problem,
            format!(
                "{summary}, but stale: extracted from {} bytes and the installed cache is now \
                 {live}",
                meta.source_bytes
            ),
        )
        .with_items(items)
        .with_fix(
            "the cache changed after the extraction — 'gore loc import' re-encrypts it in place, \
             and a game update replaces it. Run 'gore loc extract' so the shared catalog describes \
             the file that is actually installed",
        )
        }
        Err(error) => Check::new(
            "loc_catalog",
            "loc catalog",
            Verdict::Note,
            format!("{summary}, but the installed cache could not be read: {error}"),
        )
        .with_items(items),
    }
}

/// `resolve_game_paths` always builds `…\Binaries\Win64\ue4ss\Mods`, so the parent is the `ue4ss`
/// folder. The fallback keeps this total instead of panicking on a shape that cannot occur.
fn ue4ss_dir(gp: &GamePaths) -> PathBuf {
    gp.ue4ss_mods
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| gp.ue4ss_mods.clone())
}

/// The four folders this toolkit edits a game file in place in, each of which leaves the pristine
/// bytes in a `<file>.gore-bak` sibling: the localization cache, the FMOD banks, the voice-over
/// archives and the AngelScript cache. Scanning these rather than the whole install keeps the
/// check cheap, and a `.gore-bak` anywhere else was not written by this CLI.
fn find_backups(gp: &GamePaths) -> Result<Vec<String>, String> {
    let g1r = gp.root.join("G1R");
    let dirs = [
        g1r.join("Story").join("Cache"),
        gp.fmod_desktop.clone(),
        gp.voice_over.clone(),
        g1r.join("Script"),
    ];
    let mut found: Vec<String> = Vec::new();
    for dir in &dirs {
        for name in file_names(dir)? {
            if name.ends_with(".gore-bak") {
                found.push(dir.join(name).display().to_string());
            }
        }
    }
    found.sort();
    Ok(found)
}

/// Plain file names directly in `dir`.
///
/// A directory that is not there has no files, and that is an answer. A directory that is there and
/// cannot be read is not an answer, and used to be reported as one: swallowing the error returned an
/// empty vector, which `~mods` read as "empty" and the backup scan read as "nothing left over". A
/// doctor that says `ok` because it could not look is worse than one that says nothing, and the
/// installs where this happens — permissions, a half-mounted drive, I/O errors — are exactly the
/// ones it exists for. Per-entry failures count the same way; a directory half-read is not a
/// directory read.
fn file_names(dir: &Path) -> Result<Vec<String>, String> {
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(error) => return Err(format!("{} could not be read: {error}", dir.display())),
    };
    let mut names = Vec::new();
    for entry in entries {
        let entry = entry
            .map_err(|error| format!("{} could not be read: {error}", dir.display()))?;
        if entry.path().is_file() {
            names.push(entry.file_name().to_string_lossy().into_owned());
        }
    }
    Ok(names)
}


/// Windows path identity is case-insensitive, which is the same reason `semantic_install_root`
/// compares its `G1R` component with `eq_ignore_ascii_case`. Compared lexically: both sides here
/// are already absolute paths this process resolved, and canonicalizing would introduce the
/// `\\?\` verbatim prefix that the rest of the toolkit avoids.
fn same_path(a: &Path, b: &Path) -> bool {
    a.as_os_str()
        .to_string_lossy()
        .eq_ignore_ascii_case(&b.as_os_str().to_string_lossy())
}

fn print_report(report: &Report) {
    for check in &report.checks {
        println!(
            "{:<VERDICT_WIDTH$}{:<TITLE_WIDTH$}{}",
            check.verdict.label(),
            check.title,
            check.detail
        );
        let indent = " ".repeat(VERDICT_WIDTH + TITLE_WIDTH);
        for item in check.items.iter().take(MAX_LISTED) {
            println!("{indent}{item}");
        }
        // The same marker `location list` appends to a clipped listing, so one learned habit
        // covers both. `--json` is not clipped; this is a decision about a screen.
        if check.items.len() > MAX_LISTED {
            println!("{indent}… and {} more", check.items.len() - MAX_LISTED);
        }
        if let Some(fix) = &check.fix {
            println!("{indent}fix: {fix}");
        }
    }
    println!();
    println!(
        "{} check(s): {} ok, {} note, {} problem, {} skipped",
        report.checks.len(),
        report.ok,
        report.note,
        report.problem,
        report.skipped
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use gore_modgen::gen::{gen_lua, MetaConfig, OverridesConfig, OverrideValue, SingleOverride};

    /// A GamePaths for a fixture tree, built the way every command builds it.
    fn paths(root: &Path) -> GamePaths {
        gore_mod::resolve_game_paths(root)
    }

    fn make_install(root: &Path) {
        for dir in [
            root.join("G1R").join("Binaries").join("Win64"),
            root.join("G1R").join("Content").join("Paks"),
            root.join("G1R").join("Story").join("Cache"),
            root.join("G1R").join("Script"),
        ] {
            std::fs::create_dir_all(dir).unwrap();
        }
        std::fs::write(
            root.join("G1R")
                .join("Binaries")
                .join("Win64")
                .join("G1R-Win64-Shipping.exe"),
            b"exe",
        )
        .unwrap();
    }

    #[test]
    fn a_blank_configured_game_path_is_reported_as_auto_detect_not_as_config() {
        // `game_root` treats "" and "   " as unset, so auto-detect is what actually answered.
        // Reporting "config" would send someone to edit a value that had no effect — and it would
        // make `gore doctor` and `gore config list` disagree about the same file.
        assert_eq!(game_path_source(false, Some("")), "auto-detect");
        assert_eq!(game_path_source(false, Some("   ")), "auto-detect");
        assert_eq!(game_path_source(false, None), "auto-detect");
        assert_eq!(game_path_source(false, Some(r"D:\Games\G1R")), "config");
        // An explicit --game beats both, exactly as `game_root`'s precedence does.
        assert_eq!(game_path_source(true, Some(r"D:\Games\G1R")), "--game");
        assert_eq!(game_path_source(true, None), "--game");
    }

    #[test]
    fn a_mods_directory_without_the_dll_is_a_problem_not_a_ue4ss_install() {
        // The exact shape `gore mod deploy` leaves on an install that never had UE4SS: it creates
        // ue4ss\Mods\ to put the mod in. That is the deploy which "reported success" while the
        // game showed nothing, so the doctor must not read the directory as evidence of a loader.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);
        let gp = paths(root);
        std::fs::create_dir_all(&gp.ue4ss_mods).unwrap();

        let check = check_ue4ss(&gp);
        assert_eq!(check.verdict, Verdict::Problem);
        assert!(check.detail.contains("no UE4SS.dll"), "{}", check.detail);
        assert!(check.fix.unwrap().contains("install UE4SS"));
    }

    #[test]
    fn a_missing_ue4ss_folder_says_overrides_will_never_run() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);

        let check = check_ue4ss(&paths(root));
        assert_eq!(check.verdict, Verdict::Problem);
        assert!(check.detail.contains("not installed"), "{}", check.detail);
        // The point of the check is the consequence, not the missing file.
        assert!(check.fix.unwrap().contains("doing nothing"));
    }

    #[test]
    fn a_complete_ue4ss_install_is_ok() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);
        let gp = paths(root);
        std::fs::create_dir_all(&gp.ue4ss_mods).unwrap();
        let ue4ss = ue4ss_dir(&gp);
        std::fs::write(ue4ss.join("UE4SS.dll"), b"dll").unwrap();
        std::fs::write(ue4ss.join("UE4SS-settings.ini"), b"[]").unwrap();

        let check = check_ue4ss(&gp);
        assert_eq!(check.verdict, Verdict::Ok);
        assert!(check.fix.is_none());
    }

    /// Write a UE4SS mod folder; `generated` decides whether its main.lua carries the marker.
    fn make_mod(mods: &Path, name: &str, enabled: bool, generated: bool) {
        let dir = mods.join(name);
        std::fs::create_dir_all(dir.join("Scripts")).unwrap();
        if enabled {
            std::fs::write(dir.join("enabled.txt"), b"").unwrap();
        }
        let lua = if generated {
            gen_lua(&OverridesConfig {
                meta: MetaConfig {
                    name: name.to_string(),
                    delay_ms: 0,
                },
                overrides: vec![SingleOverride {
                    module: "Angelscript".into(),
                    class: "ItFo_Apple".into(),
                    field: "m_Value".into(),
                    value: OverrideValue::Int(500),
                }],
            })
        } else {
            "-- hand written\n".to_string()
        };
        std::fs::write(dir.join("Scripts").join("main.lua"), lua).unwrap();
    }

    #[test]
    fn two_enabled_generated_override_mods_are_reported_as_competing() {
        // This happened during the blind tests: a mod folder left enabled from an earlier session
        // set the same class default as the new one. Both applied, the last loaded won, and the
        // value in the game was the one nobody asked for with nothing anywhere reporting it.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);
        let gp = paths(root);
        std::fs::create_dir_all(&gp.ue4ss_mods).unwrap();
        make_mod(&gp.ue4ss_mods, "OldBalance", true, true);
        make_mod(&gp.ue4ss_mods, "NewBalance", true, true);

        let check = check_ue4ss_mods(&gp);
        assert_eq!(check.verdict, Verdict::Problem);
        let fix = check.fix.unwrap();
        assert!(fix.contains("OldBalance") && fix.contains("NewBalance"), "{fix}");
    }

    #[test]
    fn stock_ue4ss_mods_do_not_trigger_the_competing_override_warning() {
        // UE4SS ships enabled mods of its own, and gore-lua's `shared/` namespace lives in the
        // same directory. Warning about those would fire on every healthy install and teach people
        // to ignore the line that matters.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);
        let gp = paths(root);
        std::fs::create_dir_all(gp.ue4ss_mods.join("shared").join("gore-lua")).unwrap();
        make_mod(&gp.ue4ss_mods, "BPModLoaderMod", true, false);
        make_mod(&gp.ue4ss_mods, "ConsoleEnablerMod", true, false);
        make_mod(&gp.ue4ss_mods, "MyBalanceMod", true, true);

        let check = check_ue4ss_mods(&gp);
        assert_eq!(check.verdict, Verdict::Ok);
        assert_eq!(check.detail, "3 mod folder(s), 3 enabled");
        // `shared` is the SDK namespace, not a mod, so it is not one of the three.
        assert!(!check.items.iter().any(|item| item.starts_with("shared")));
        assert!(check
            .items
            .iter()
            .any(|item| item == "MyBalanceMod [enabled] gore override"));
    }

    #[test]
    fn a_disabled_mod_folder_is_listed_as_disabled_rather_than_ignored() {
        // "I deployed it and nothing happened" is also what a folder without enabled.txt looks
        // like, so the report has to show the switch rather than only the folders it counts.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);
        let gp = paths(root);
        std::fs::create_dir_all(&gp.ue4ss_mods).unwrap();
        make_mod(&gp.ue4ss_mods, "MyBalanceMod", false, true);

        let check = check_ue4ss_mods(&gp);
        assert_eq!(check.detail, "1 mod folder(s), 0 enabled");
        assert_eq!(check.items, ["MyBalanceMod [disabled] gore override"]);
    }

    #[test]
    fn the_mod_listing_shows_the_enabled_folders_before_the_cap_can_cut_them() {
        // A real UE4SS install has ~22 folders, nearly all of them disabled stock mods, and the
        // listing is capped. Alphabetical order spent the whole cap on mods that do not run and
        // truncated the ones that do — the exact opposite of what the reader is looking for.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);
        let gp = paths(root);
        std::fs::create_dir_all(&gp.ue4ss_mods).unwrap();
        make_mod(&gp.ue4ss_mods, "AaaDisabled", false, false);
        make_mod(&gp.ue4ss_mods, "ZzzEnabled", true, false);

        let listed = read_ue4ss_mods(&gp.ue4ss_mods).expect("the fixture directory is readable");
        assert_eq!(listed[0].name, "ZzzEnabled");
        assert_eq!(listed[1].name, "AaaDisabled");
    }

    #[test]
    fn gen_lua_still_writes_the_marker_this_module_looks_for() {
        // The "gore override" label is read off the generated file's first line. If the generator
        // ever stops writing it, the competing-override warning silently stops firing — so the
        // coupling is pinned here rather than left to be discovered in a bug report.
        let lua = gen_lua(&OverridesConfig {
            meta: MetaConfig {
                name: "MyBalanceMod".into(),
                delay_ms: 0,
            },
            overrides: Vec::new(),
        });
        assert!(lua.starts_with(GENERATED_MARKER), "{}", &lua[..40.min(lua.len())]);
    }

    #[test]
    fn an_install_missing_its_executable_says_it_is_not_the_game() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::create_dir_all(root.join("G1R")).unwrap();

        let check = check_install(&paths(root));
        assert_eq!(check.verdict, Verdict::Problem);
        assert!(
            check.detail.contains("does not look like"),
            "{}",
            check.detail
        );
        // The commonest cause is pointing at G1R\ itself, so the fix names it.
        assert!(check.fix.unwrap().contains("CONTAINS G1R"));
    }

    #[test]
    fn a_complete_install_is_ok_and_a_partial_one_is_incomplete_not_wrong_game() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);
        assert_eq!(check_install(&paths(root)).verdict, Verdict::Ok);

        // Executable present, one folder gone: an install that is being verified, not the wrong
        // directory — a different sentence and a different fix.
        std::fs::remove_dir_all(root.join("G1R").join("Script")).unwrap();
        let check = check_install(&paths(root));
        assert_eq!(check.verdict, Verdict::Problem);
        assert!(check.detail.starts_with("install is incomplete"), "{}", check.detail);
    }

    /// Build a probe against a fixture tree while STATING whether the game runs, so the result
    /// never depends on whether the developer has Gothic open while the suite runs.
    fn probe(root: &Path, running: bool) -> InstallCompileStateProbe {
        gore_as::compile::probe_install_compile_state_with_stated_game_process(root, || Ok(running))
    }

    #[test]
    fn a_leftover_install_mutation_lock_is_reported_with_the_command_that_clears_it() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);
        std::fs::write(root.join(".gore-install-mutation.lock"), b"{}").unwrap();

        let check = check_leftovers(&paths(root), &probe(root, false), false);
        assert_eq!(check.verdict, Verdict::Problem);
        assert!(check.detail.contains("refuse to start"), "{}", check.detail);
        assert!(check
            .items
            .iter()
            .any(|item| item.contains("InstallMutationLock")));
    }

    #[test]
    fn a_gore_bak_with_no_deploy_record_is_a_note_and_with_one_is_not() {
        // A `.gore-bak` beside a game file is normal while a deployment is active. With no record
        // it means the file is still modified and its pristine copy is sitting next to it, which
        // is what "I undeployed and the game still looks wrong" actually is.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);
        std::fs::write(
            root.join("G1R")
                .join("Story")
                .join("Cache")
                .join("AlkimiaLocalization_00000000.lcache.gore-bak"),
            b"pristine",
        )
        .unwrap();

        let orphaned = check_leftovers(&paths(root), &probe(root, false), false);
        assert_eq!(orphaned.verdict, Verdict::Note);
        assert!(orphaned.fix.unwrap().contains("gore audio restore"));

        let owned = check_leftovers(&paths(root), &probe(root, false), true);
        assert_eq!(owned.verdict, Verdict::Ok);
        assert!(owned.fix.is_none());
    }

    #[test]
    fn a_clean_install_has_no_leftovers_at_all() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);

        let check = check_leftovers(&paths(root), &probe(root, false), false);
        assert_eq!(check.verdict, Verdict::Ok);
        assert!(check.items.is_empty());
    }

    #[test]
    fn a_running_game_is_a_note_because_it_is_not_a_fault() {
        // Deploy and undeploy refuse while the game holds the install open, so this is worth a
        // line. It is not a problem: having the game open is not something anyone did wrong, and
        // the whole report must stay readable on a healthy day.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);

        let check = check_game_process(&probe(root, true));
        assert_eq!(check.verdict, Verdict::Note);
        assert!(check.fix.unwrap().contains("Close the game"));
        assert_eq!(check_game_process(&probe(root, false)).verdict, Verdict::Ok);
    }

    /// `extracted_at` comes from the source file rather than staying at zero, because that is
    /// the order reality has: `gore loc extract` reads a cache that already exists, so the file
    /// it read is never newer than the extraction. A fixture stuck at the epoch makes every file
    /// look rewritten since, which is the opposite of the fresh case these tests describe.
    fn meta(source: &Path, bytes: u64) -> LocMeta {
        let extracted_at = std::fs::metadata(source)
            .and_then(|m| m.modified())
            .ok()
            .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
            .map(|since| since.as_secs())
            .unwrap_or(0);
        LocMeta {
            source_path: source.display().to_string(),
            source_bytes: bytes,
            id_count: 43851,
            languages: vec!["german".into(), "english".into()],
            extracted_at,
            catalog_path: r"C:\Users\x\AppData\Local\gore\loc_catalog.json".into(),
        }
    }

    #[test]
    fn a_loc_catalog_whose_source_size_no_longer_matches_the_install_is_stale() {
        // `gore loc import` re-encrypts the cache in place, which changes its size. `gore loc
        // status` reports the size it extracted from and cannot know the file moved on; that
        // disagreement is the confusing case this line exists for.
        let dir = tempfile::tempdir().unwrap();
        let cache = dir.path().join("AlkimiaLocalization_00000000.lcache");
        std::fs::write(&cache, vec![0u8; 2048]).unwrap();

        let check = check_loc_catalog(Some(meta(&cache, 1024)), Some(&cache));
        assert_eq!(check.verdict, Verdict::Problem);
        assert!(check.detail.contains("stale"), "{}", check.detail);
        assert!(check.fix.unwrap().contains("gore loc extract"));

        let fresh = check_loc_catalog(Some(meta(&cache, 2048)), Some(&cache));
        assert_eq!(fresh.verdict, Verdict::Ok);
    }

    #[test]
    fn a_loc_catalog_whose_source_was_rewritten_at_the_same_length_is_stale_too() {
        // The case length alone cannot see: `gore loc import` re-encrypts in place, and a
        // replacement string that encodes to the same number of bytes leaves the file exactly as
        // long as it was. Caught through the modification time, because the catalog carries no
        // content hash and adding one would change a format Mod Studio and the save editor read.
        let dir = tempfile::tempdir().unwrap();
        let cache = dir.path().join("AlkimiaLocalization_00000000.lcache");
        std::fs::write(&cache, vec![0u8; 2048]).unwrap();

        // Extracted a minute before the rewrite that follows, and at the very same length.
        let mut before = meta(&cache, 2048);
        before.extracted_at = before.extracted_at.saturating_sub(60);
        std::fs::write(&cache, vec![1u8; 2048]).unwrap();

        let check = check_loc_catalog(Some(before), Some(&cache));
        assert_eq!(check.verdict, Verdict::Problem, "{}", check.detail);
        assert!(
            check.detail.contains("same length"),
            "the detail says why length did not catch it: {}",
            check.detail
        );
        assert!(check.fix.unwrap().contains("gore loc extract"));
    }

    #[test]
    fn a_loc_catalog_extracted_from_another_install_says_so_instead_of_claiming_staleness() {
        // Same size, different file: the catalog is not stale, it describes somewhere else. Two
        // different sentences, because the fix is the same command for two different reasons.
        let dir = tempfile::tempdir().unwrap();
        let here = dir.path().join("AlkimiaLocalization_00000000.lcache");
        let elsewhere = dir.path().join("other.lcache");
        std::fs::write(&here, vec![0u8; 64]).unwrap();

        let check = check_loc_catalog(Some(meta(&elsewhere, 64)), Some(&here));
        assert_eq!(check.verdict, Verdict::Note);
        assert!(check.detail.contains("different file"), "{}", check.detail);
    }

    #[test]
    fn no_extracted_catalog_names_the_command_that_makes_one() {
        let check = check_loc_catalog(None, None);
        assert_eq!(check.verdict, Verdict::Note);
        assert!(check.fix.unwrap().contains("gore loc extract"));
    }

    #[test]
    fn an_empty_mods_folder_and_a_populated_one_both_report_where_they_looked() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);
        let gp = paths(root);

        let none = check_mods_folder(&gp);
        assert_eq!(none.verdict, Verdict::Ok);
        assert!(none.detail.contains("nothing additive"), "{}", none.detail);

        let mods = gore_tex::container::mods_dir(&gp.root);
        std::fs::create_dir_all(&mods).unwrap();
        std::fs::write(mods.join("zzz_MyTextures_P.pak"), b"pak").unwrap();
        let some = check_mods_folder(&gp);
        assert_eq!(some.items, ["zzz_MyTextures_P.pak"]);
    }

    #[test]
    fn an_install_with_no_deployment_reports_that_rather_than_an_error() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);
        let library = dir.path().join("library");
        let loadout = dir.path().join("loadout.json");

        let check = check_deployment(&paths(root), &library, &loadout);
        assert_eq!(check.verdict, Verdict::Ok);
        assert!(check.detail.contains("nothing is deployed"), "{}", check.detail);
        // A reader who wants to look for themselves gets the three paths involved.
        assert_eq!(check.items.len(), 3);
    }

    #[test]
    fn a_report_with_no_install_still_names_every_check_it_could_not_run() {
        // A report that silently shrank would read as a report that found less to say. Each
        // skipped line stays, pointing back at the game-path line that explains why.
        let checks: Vec<Check> = SKIPPED_WITHOUT_INSTALL
            .iter()
            .map(|(id, title)| Check::new(id, title, Verdict::Skipped, "no install to look at"))
            .collect();
        let report = Report::new(None, "auto-detect", checks);
        assert_eq!(report.skipped, SKIPPED_WITHOUT_INSTALL.len());
        assert_eq!(report.problem, 0);
        assert!(report.game_root.is_none());
    }

    #[test]
    fn the_listing_cap_is_a_decision_about_a_screen_and_never_shortens_the_json() {
        // A real UE4SS Mods\ has more folders than the cap. Clipping the check's own `items` would
        // put a literal "… and 10 more" into the JSON array, which is neither a mod name nor
        // something a caller can parse — so the cap belongs to `print_report` alone.
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        make_install(root);
        let gp = paths(root);
        std::fs::create_dir_all(&gp.ue4ss_mods).unwrap();
        for n in 0..MAX_LISTED + 3 {
            make_mod(&gp.ue4ss_mods, &format!("Mod{n:02}"), false, false);
        }

        let check = check_ue4ss_mods(&gp);
        assert_eq!(check.items.len(), MAX_LISTED + 3);
        assert!(!check.items.iter().any(|item| item.contains("and 3 more")));
    }

    #[test]
    fn the_json_document_carries_stable_ids_and_the_counts_a_caller_gates_on() {
        // `--json` is the answer to "the exit code is always 0": a caller that wants to fail on a
        // finding reads these fields, so they are part of the contract and not incidental output.
        let report = Report::new(
            Some(Path::new(r"D:\Games\G1R")),
            "config",
            vec![
                Check::new("ue4ss", "UE4SS", Verdict::Problem, "not installed")
                    .with_fix("install it"),
                Check::new("game_process", "game process", Verdict::Ok, "not running"),
            ],
        );
        let json: serde_json::Value =
            serde_json::from_str(&serde_json::to_string(&report).unwrap()).unwrap();
        assert_eq!(json["problem"], 1);
        assert_eq!(json["ok"], 1);
        assert_eq!(json["game_source"], "config");
        assert_eq!(json["checks"][0]["id"], "ue4ss");
        assert_eq!(json["checks"][0]["verdict"], "problem");
        assert_eq!(json["checks"][0]["fix"], "install it");
        // An `ok` check carries no fix, so a caller never prints advice about a healthy line.
        assert!(json["checks"][1].get("fix").is_none());
    }
}
