//! `gore-cli dump-mod` — generate the **gore-dump** UE4SS Lua mod.
//!
//! The mod reads each item CDO's current field values in-game and writes a
//! `gore_game_data.json` (the same shape `gore-cli sync` ingests), giving the
//! GUI the real per-field defaults that only the running game knows.
//!
//! The mod is self-contained at runtime: it carries the item/field list
//! (`items.lua`, generated here from the model + catalog) and reads values via
//! the proven `StaticFindObject(Default__<id>)[field]` path — no fragile
//! reflection. Brand-new items/fields introduced by a game patch need the model
//! regenerated (`dump` + `gui-model`/`sync`) before they appear here.
//!
//! Localized names/descriptions are NOT dumped here — they live in the encrypted
//! AlkimiaLocalization `.lcache`, which `gore-cli loc` reads directly offline.

use anyhow::{Context, Result};
use gore_catalog::parse_catalog;
use gore_modgen::gen::lua_escape;
use std::{fs, path::PathBuf};

use crate::cmd::gui_model::GuiModel;

/// Fixed runtime that reads CDO values against the bundled `items.lua` schema
/// and writes `gore_game_data.json`. Item/field data comes from `items.lua`.
const MAIN_LUA: &str = r#"-- gore-dump (generated by gore-cli) — do not edit by hand.
-- Reads each item CDO's current field values and writes gore_game_data.json,
-- which `gore-cli sync` ingests to give the GUI real default values.
local SCHEMA = require("items")
local OUT_FILE = "gore_game_data.json"
local DELAY_MS = 15000

local function json_escape(s)
  return (s:gsub('[%z\1-\31\\"]', function(c)
    local map = {['"']='\\"', ['\\']='\\\\', ['\n']='\\n', ['\r']='\\r', ['\t']='\\t'}
    return map[c] or string.format('\\u%04x', string.byte(c))
  end))
end

-- Encode a read value as JSON, typed by the field. Returns nil when the value
-- is missing or the wrong Lua type (the field is then emitted without a default).
local function value_json(field_type, v)
  if field_type == "bool" then
    if type(v) == "boolean" then return v and "true" or "false" end
    return nil
  end
  if type(v) ~= "number" then return nil end
  -- JSON has no inf/nan; skip non-finite values so the file stays valid JSON
  -- (the field is then emitted without a default -> GUI shows a placeholder).
  if v ~= v or v == math.huge or v == -math.huge then return nil end
  if field_type == "int" or field_type == "enum" then
    return string.format("%d", math.floor(v + 0.5))
  end
  return string.format("%.17g", v) -- float: round-trips a double
end

local function dump()
  local classes = {}
  for _, cls in ipairs(SCHEMA) do
    local cdo = StaticFindObject("/Script/Angelscript.Default__" .. cls.id)
    if cdo and cdo:IsValid() then
      local fields = {}
      for _, f in ipairs(cls.fields) do
        local ok, raw = pcall(function() return cdo[f.name] end)
        local parts = {
          string.format('"name":"%s"', json_escape(f.name)),
          string.format('"type":"%s"', json_escape(f.type)),
        }
        if f.enum_values then
          local evs = {}
          for _, e in ipairs(f.enum_values) do
            evs[#evs + 1] = string.format('"%s"', json_escape(e))
          end
          parts[#parts + 1] = '"enum_values":[' .. table.concat(evs, ",") .. ']'
        end
        if f.enum_value_ints then
          local ivs = {}
          for _, n in ipairs(f.enum_value_ints) do
            ivs[#ivs + 1] = string.format("%d", n)
          end
          parts[#parts + 1] = '"enum_value_ints":[' .. table.concat(ivs, ",") .. ']'
        end
        local dj = ok and value_json(f.type, raw) or nil
        if dj then parts[#parts + 1] = '"default":' .. dj end
        fields[#fields + 1] = "{" .. table.concat(parts, ",") .. "}"
      end
      classes[#classes + 1] = string.format(
        '"%s":{"fields":[%s]}', json_escape(cls.id), table.concat(fields, ","))
    else
      print("[gore-dump] CDO not found (skipped): " .. cls.id .. "\n")
    end
  end
  local json = '{"classes":{' .. table.concat(classes, ",") .. '}}'
  local fh = io.open(OUT_FILE, "w")
  if fh then
    fh:write(json)
    fh:close()
    print("[gore-dump] wrote " .. tostring(#classes) .. " classes -> " .. OUT_FILE .. "\n")
  else
    print("[gore-dump] FAILED to open " .. OUT_FILE .. " for writing\n")
  end
end

print("[gore-dump] loaded; dumping item CDOs in " .. tostring(DELAY_MS) .. "ms\n")
ExecuteWithDelay(DELAY_MS, dump)
"#;

const README: &str = r#"# gore-dump

UE4SS Lua mod that reads the live default values of every catalog item and
writes `gore_game_data.json`, which `gore-cli sync` ingests to refresh the
gore-mod editor with real defaults.

## Use

1. Copy this `gore-dump/` folder into `<game>/Binaries/Win64/ue4ss/Mods/`.
2. Make sure UE4SS lists it (it ships with an empty `enabled.txt`).
3. Launch the game, load any save (or reach the main menu), wait ~15s.
4. `gore_game_data.json` is written to the game's working directory
   (usually `Binaries/Win64/`). Watch the UE4SS console for the path.
5. `gore-cli sync --dump gore_game_data.json --catalog item_catalog.json -o model.json`
   then rebuild/point gore-mod at the new model.

Regenerate this mod (`gore-cli dump-mod`) after the item set changes so
`items.lua` covers new classes/fields.

Localized names/descriptions are not produced here — use `gore-cli loc export`
to read them straight from the game's `.lcache`.
"#;

pub fn run(model_path: PathBuf, catalog_path: PathBuf, out: PathBuf) -> Result<()> {
    let model_json = fs::read_to_string(&model_path)
        .with_context(|| format!("reading model '{}'", model_path.display()))?;
    let model: GuiModel = serde_json::from_str(&model_json).context("parsing model.json")?;

    let catalog_json = fs::read_to_string(&catalog_path)
        .with_context(|| format!("reading catalog '{}'", catalog_path.display()))?;
    let catalog = parse_catalog(&catalog_json).context("parsing item_catalog.json")?;

    let items_lua = render_items_lua(&model, catalog.iter().map(|e| e.id.as_str()));

    let mod_dir = out.join("gore-dump");
    let scripts = mod_dir.join("Scripts");
    fs::create_dir_all(&scripts)
        .with_context(|| format!("creating '{}'", scripts.display()))?;
    fs::write(mod_dir.join("enabled.txt"), "")?;
    fs::write(mod_dir.join("README.md"), README)?;
    fs::write(scripts.join("main.lua"), MAIN_LUA)?;
    fs::write(scripts.join("items.lua"), &items_lua)?;

    let class_count = items_lua.matches("id=").count();
    println!(
        "Wrote gore-dump mod ({class_count} item classes) -> {}",
        mod_dir.display()
    );
    Ok(())
}

/// Render the `items.lua` table: `return { {id="..", fields={ {name=..,type=..,
/// enum_values={..}} }}, .. }`, restricted to catalog ids present in the model.
fn render_items_lua<'a>(model: &GuiModel, catalog_ids: impl Iterator<Item = &'a str>) -> String {
    let mut out = String::from("-- gore-dump item/field schema (generated by gore-cli)\nreturn {\n");
    for id in catalog_ids {
        let Some(class) = model.classes.get(id) else {
            continue;
        };
        out.push_str(&format!("  {{id=\"{}\", fields={{\n", lua_escape(id)));
        for f in &class.fields {
            out.push_str(&format!(
                "    {{name=\"{}\", type=\"{}\"",
                lua_escape(&f.name),
                lua_escape(&f.field_type)
            ));
            if !f.enum_values.is_empty() {
                let members: Vec<String> = f
                    .enum_values
                    .iter()
                    .map(|m| format!("\"{}\"", lua_escape(m)))
                    .collect();
                out.push_str(&format!(", enum_values={{{}}}", members.join(", ")));
            }
            if !f.enum_value_ints.is_empty() {
                let ints: Vec<String> = f.enum_value_ints.iter().map(|v| v.to_string()).collect();
                out.push_str(&format!(", enum_value_ints={{{}}}", ints.join(", ")));
            }
            out.push_str("},\n");
        }
        out.push_str("  }},\n");
    }
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn model() -> GuiModel {
        serde_json::from_value(json!({
            "classes": {
                "ItFo_Apple": {"fields": [
                    {"name": "m_Value", "type": "int"},
                    {"name": "m_Quality", "type": "enum", "enum_values": ["Low", "High"], "enum_value_ints": [0, 5]}
                ]},
                "NotInCatalog": {"fields": [{"name": "x", "type": "int"}]}
            }
        }))
        .unwrap()
    }

    #[test]
    fn renders_catalog_items_with_fields_and_enums() {
        let lua = render_items_lua(&model(), ["ItFo_Apple"].into_iter());
        assert!(lua.contains(r#"{id="ItFo_Apple", fields={"#));
        assert!(lua.contains(r#"{name="m_Value", type="int"},"#));
        assert!(lua.contains(
            r#"{name="m_Quality", type="enum", enum_values={"Low", "High"}, enum_value_ints={0, 5}},"#
        ));
        // valid Lua table delimiters
        assert!(lua.trim_end().ends_with('}'));
    }

    #[test]
    fn skips_classes_absent_from_catalog() {
        let lua = render_items_lua(&model(), ["ItFo_Apple"].into_iter());
        assert!(!lua.contains("NotInCatalog"));
    }

    #[test]
    fn main_lua_uses_the_proven_cdo_path_and_writes_json() {
        assert!(MAIN_LUA.contains(r#"StaticFindObject("/Script/Angelscript.Default__" .. cls.id)"#));
        assert!(MAIN_LUA.contains("gore_game_data.json"));
        assert!(MAIN_LUA.contains("ExecuteWithDelay"));
    }

    #[test]
    fn main_lua_emits_enum_backing_values() {
        // The in-game writer must copy enum_value_ints so sync can validate the
        // CDO's backing-value default against the real discriminants.
        assert!(MAIN_LUA.contains("f.enum_value_ints"));
        assert!(MAIN_LUA.contains(r#""enum_value_ints":["#));
    }

    #[test]
    fn main_lua_skips_non_finite_values() {
        // inf/nan are not valid JSON; the dumper must drop them.
        assert!(MAIN_LUA.contains("v == math.huge"));
        assert!(MAIN_LUA.contains("v ~= v"));
    }
}
