#pragma once

#include "gore_as_standalone/precompiled_data.hpp"
#include "gore_as_standalone/module_preprocessor.hpp"
#include "gore_as_standalone/registry_profile.hpp"

#include "angelscript.h"

#include <cstddef>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace gore::as::standalone {
class frontend_compile_runtime;
struct shipping_static_jit_candidates;
}

namespace gore::as::standalone::precompiled {

enum class engine_bridge_phase {
    none,
    preflight,
    request_build,
    prepare_engine,
    create_modules,
    create_types,
    parse_source,
    generate_source_types,
    create_globals_and_functions,
    generate_source_functions,
    layout_types,
    layout_source_functions,
    relocate_bytecode,
    compile_source_code,
    validate_template_instances,
    initialize_globals,
    export_module,
    cleanup,
};

struct engine_bridge_result {
    int code = asSUCCESS;
    engine_bridge_phase phase = engine_bridge_phase::none;
    std::size_t module_index = static_cast<std::size_t>(-1);
    std::string detail;
    bool is_compile_diagnostic = false;
    std::string diagnostic_source;
    std::uint32_t diagnostic_line = 0U;
    std::uint32_t diagnostic_column = 0U;

    [[nodiscard]] bool succeeded() const noexcept { return code >= 0; }
};

namespace detail {

// Internal source-projection step, declared here for focused structural tests.
engine_bridge_result rebase_projected_static_names(
    cache& projected,
    const std::unordered_map<std::size_t, std::size_t>& global_to_local);

} // namespace detail

// Current engine bridge checkpoint. It restores the generic fork-side portion
// of the three PrecompiledData apply stages: module imports/function-import
// declarations, script enums/classes/inheritance/layout, methods/constructors/
// destructors/behaviours, globals and initializers, plus type/function/global/
// property bytecode references. The complete cache is preflighted before the
// engine is mutated. Unreal shadow layouts and metadata, delegate/event tags,
// string-literal globals, statics/post-init hooks and profile registry replay
// remain intentionally fail-closed.
engine_bridge_result rehydrate_cache_checkpoint(
    asIScriptEngine& engine,
    const cache& input,
    std::vector<asIScriptModule*>& modules);

// Rebuild a final graph from a pristine cache plus source overlays under one
// RequestBuild/BuildCompleted session. A source module whose name is present
// in `base` replaces that cached module; any other source module is appended.
// Saved references are resolved by qualified identity after all replacement
// shells/declarations exist, never by copying cached engine ids.
engine_bridge_result compile_mixed_cache_checkpoint(
    asIScriptEngine& engine,
    const cache& base,
    const preprocessor_options& options,
    const lexical_preprocess_result& source,
    registry_runtime* registry,
    frontend_compile_runtime& frontend_runtime,
    bool initialize_source_globals,
    std::vector<asIScriptModule*>& modules,
    shipping_static_jit_candidates* static_jit_candidates = nullptr);

// Apply the Shipping StaticJIT analysis immediately before serialization, but
// only to the exact functions captured by the manager's stage-3 JIT callback.
// Functions generated by stage-4 template validation are intentionally absent.
engine_bridge_result apply_shipping_static_jit_checkpoint(
    const std::vector<asIScriptModule*>& modules,
    const shipping_static_jit_candidates& candidates);

struct shipping_static_jit_coverage {
    std::vector<std::string> base_module_names;
    std::vector<std::string> fully_analyzed_module_names;
    std::vector<std::pair<std::string, std::string>> retained_final_functions;
};

// Structurally project the Shipping StaticJIT boundary carried by a sealed
// base-cache graph. The graph is disposable: the probe applies the analysis to
// it, records modules already at that fixed point, and preserves pre-existing
// FINAL functions in partially analyzed modules by stable declaration identity.
// No executable identity or module-name allowlist participates in the decision.
engine_bridge_result derive_shipping_static_jit_module_coverage(
    const std::vector<asIScriptModule*>& base_modules,
    shipping_static_jit_coverage& coverage);

// Project the structurally derived base boundary onto a freshly compiled
// source graph and apply StaticJIT atomically. New modules follow the donor's
// normal stage-3 path. In partially analyzed base modules, a sealed FINAL
// identity is retained only when the fresh function still carries a generated,
// constructor or destructor role, or maps uniquely to a preprocessed UFUNCTION.
engine_bridge_result apply_shipping_static_jit_coverage_checkpoint(
    const std::vector<asIScriptModule*>& modules,
    const shipping_static_jit_candidates& candidates,
    const shipping_static_jit_coverage& coverage,
    const lexical_preprocess_result& source);

// Export one compiled module through the same generic fork-side subset.
// `module_key` is the outer UE FString key; `script_relative_filename`,
// `code_hash`, direct import ordering and the Unreal/preprocessor-only fields
// are authoritative preprocessing inputs absent from the generic engine
// object. Passing `reference_tables` enables reference-bearing records and
// stages all tail-table changes atomically with `output`.
engine_bridge_result export_module_checkpoint(
    asIScriptModule& module,
    const map_string& module_key,
    const archive_string& script_relative_filename,
    std::int64_t code_hash,
    precompiled_module& output,
    cache* reference_tables = nullptr);

// Exports every final mixed-graph module into one fresh, internally coherent
// reference-table namespace. Unchanged cache modules regain their exact
// descriptor-only metadata after structural order verification; source
// modules receive the preprocessor projection. The caller supplies the
// profile-qualified build identifier and newly generated output GUID.
engine_bridge_result export_mixed_graph_checkpoint(
    const cache& base,
    const lexical_preprocess_result& source,
    const std::vector<asIScriptModule*>& modules,
    const std::array<std::uint8_t, 16U>& data_guid,
    std::int32_t build_identifier,
    cache& output,
    registry_runtime& registry,
    bool mark_non_uproperty_properties_as_transient = false);

// Qualification-only projection of the newly compiled source modules. Production still receives
// and validates the complete mixed graph; this smaller cache mirrors the embedded compiler's
// per-run serialization so the two independent compilers can be compared exactly.
engine_bridge_result export_source_graph_checkpoint(
    const cache& base,
    const lexical_preprocess_result& source,
    const std::vector<asIScriptModule*>& modules,
    const std::array<std::uint8_t, 16U>& data_guid,
    std::int32_t build_identifier,
    cache& output,
    registry_runtime& registry,
    bool mark_non_uproperty_properties_as_transient = false);

} // namespace gore::as::standalone::precompiled
