[package]
name = "gore-asset"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
retoc = { path = "../../vendor/retoc" }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
tempfile = "3"
thiserror = "1"
usmap = { git = "https://github.com/trumank/jmap.git", rev = "909bce98a33e7d1932941404af7865514249f6be" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
serde_json = "1"
