import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:path/path.dart' as p;

/// Where the glossary artwork sits inside a game installation.
const _glossaryImageDirectory = 'Story/Conversation/images/Glossary';

/// The install folder the artwork can be read from, given a configured game
/// path.
///
/// The setting is not necessarily the root: the CLI accepts the executable
/// (`…/G1R/Binaries/Win64/G1R-Win64-Shipping.exe`) and any folder below the
/// install, so joining the raw setting would build `<exe>/G1R/Story/…` and find
/// nothing. Walks up to the folder that holds the story files, the way
/// `normalize_root` in `gore_loc::config` walks up to the one holding `G1R`.
///
/// Stricter than that one on purpose: the game keeps its savegames under
/// `%LOCALAPPDATA%/G1R`, so a bare `G1R` folder is not proof of an install and
/// would resolve any path under AppData to the wrong place. Returns the setting
/// unchanged when nothing along the way looks like an install — the caller
/// treats a path with no artwork behind it as "no portraits" either way.
String? normalizeGameRoot(String? gamePath) {
  final trimmed = gamePath?.trim();
  if (trimmed == null || trimmed.isEmpty) return null;
  var directory = Directory(trimmed);
  for (var i = 0; i < 8; i++) {
    if (Directory(
      p.join(directory.path, 'G1R', _glossaryImageDirectory.split('/').first),
    ).existsSync()) {
      return directory.path;
    }
    final parent = directory.parent;
    if (parent.path == directory.path) break;
    directory = parent;
  }
  return trimmed;
}

/// Which of a portrait's two sizes to read.
enum GlossaryImageSize {
  /// 100x84, for a list row.
  thumbnail('S'),

  /// 500x264, for a detail header.
  banner('M');

  const GlossaryImageSize(this.suffix);

  final String suffix;
}

/// The pencil portrait the game shows for one glossary entry.
///
/// These are NOT in the game's asset container: they are loose PNGs under
/// `G1R/Story/Conversation/images/Glossary/`, next to the localization cache
/// and the voice-over archives, so they are read straight off the user's
/// installation — no extraction, no cache.
///
/// The mapping from a document class to its file name comes from the class's
/// own `m_ThumbnailImage` default and is bundled as `assets/glossary_images.json`
/// (regenerated by `apps/save-editor/tools/build_glossary_images.py`).
@immutable
class GlossaryImageCatalog {
  GlossaryImageCatalog([
    this.byDocumentClass = const {},
    this.byArtworkName = const {},
  ]) : _byLowercasedArtwork = {
         for (final entry in byArtworkName.entries)
           entry.key.toLowerCase(): entry.value,
         for (final entry in byArtworkName.entries)
           _fold(entry.key): entry.value,
       },
       _byLowercasedClass = {
         for (final entry in byDocumentClass.entries)
           entry.key.toLowerCase(): entry.value,
       },
       _species = [
         for (final entry in byDocumentClass.entries)
           if (entry.value.kind == creatureKind)
             _Species(entry.key, _documentName(entry.key)),
       ];

  /// Document class name (without its `/Script/Angelscript.` prefix) -> artwork.
  final Map<String, GlossaryImageRef> byDocumentClass;

  /// Every artwork file in the installation, keyed by its own name. About
  /// thirty of them — Orik, Balam, Blade, SkeletonScout, ScavengerYoung — are
  /// drawn for characters and creatures no glossary document points at.
  final Map<String, GlossaryImageRef> byArtworkName;

  /// [byArtworkName] under both its lowercased and its folded key, so a save
  /// id may spell the name any way it likes.
  final Map<String, GlossaryImageRef> _byLowercasedArtwork;

  /// The same, lowercased: a save id's own capitalisation must not decide
  /// whether a creature finds its picture.
  final Map<String, GlossaryImageRef> _byLowercasedClass;

  /// One entry per creature species the glossary draws.
  final List<_Species> _species;

  /// The artwork folder for creatures.
  static const creatureKind = 'Creatures';

  /// The artwork folder for people.
  static const characterKind = 'Characters';

  /// A save id's trailing instance number, e.g. `_701` or `_300N`.
  static final RegExp _instanceNumber = RegExp(r'_\d+[Nn]?$');

  /// A leading camp or faction code, e.g. `NC`, `SLD`, `STT`.
  static final RegExp _factionCode = RegExp(r'^[A-Z]{2,4}$');

  GlossaryImageRef? _lookup(String documentClass) {
    final tail = _classTail(documentClass);
    return byDocumentClass[tail] ?? _byLowercasedClass[tail.toLowerCase()];
  }

  /// Absolute path of one entry's portrait, or null when the entry has none or
  /// no game installation is configured. The file is NOT checked for existence
  /// here; the widget's error builder covers a missing or unreadable one.
  String? pathFor({
    required String documentClass,
    required GlossaryImageSize size,
    String? gamePath,
  }) => pathForArtwork(
    image: _lookup(documentClass),
    size: size,
    gamePath: gamePath,
  );

  /// The same for an artwork resolved directly, without a document.
  String? pathForArtwork({
    required GlossaryImageRef? image,
    required GlossaryImageSize size,
    String? gamePath,
  }) {
    if (gamePath == null || gamePath.trim().isEmpty) return null;
    if (image == null) return null;
    return p.joinAll([
      gamePath,
      'G1R',
      ..._glossaryImageDirectory.split('/'),
      image.kind,
      'T_GlossaryImage_${image.name}_${size.suffix}.png',
    ]);
  }

  /// The artwork drawn for this character, matched by name.
  ///
  /// A save id carries its camp and faction in front and an instance number
  /// behind — `NC_SLD_Orik_701`, `OC_STT_Balam_324` — while the artwork is
  /// filed under the bare name. Only the short all-caps codes are dropped, so
  /// `Golem_Stone` is never mistaken for the man named Stone and `Lurker_Homer`
  /// never for Homer.
  ///
  /// [charactersOnly] refuses a creature's sketch, for a character the catalog
  /// already calls human: there is a man named Wolf.
  GlossaryImageRef? artworkFor(
    String characterId, {
    bool charactersOnly = false,
  }) {
    final base = characterId.trim().replaceFirst(_instanceNumber, '');
    if (base.isEmpty) return null;
    final segments = base.split('_');
    var first = 0;
    while (first < segments.length - 1 &&
        _factionCode.hasMatch(segments[first])) {
      first++;
    }
    for (var start = 0; start <= first; start++) {
      final candidate = segments.skip(start).join('_');
      final image =
          byArtworkName[candidate] ??
          _byLowercasedArtwork[candidate.toLowerCase()] ??
          _byLowercasedArtwork[_fold(candidate)];
      if (image == null) continue;
      if (charactersOnly && image.kind != characterKind) return null;
      return image;
    }
    return null;
  }

  /// Whether this document has artwork at all. Case-insensitive on the tail,
  /// so a save id's own capitalisation does not decide it.
  bool hasDocument(String documentClass) => _lookup(documentClass) != null;

  /// Whether this document is one of the glossary's creature entries.
  bool isCreatureDocument(String documentClass) =>
      _lookup(documentClass)?.kind == creatureKind;

  /// The artwork one document names, if it has any.
  GlossaryImageRef? artworkForDocument(String documentClass) =>
      _lookup(documentClass);

  /// The species document for one of a creature's many save-side variants.
  ///
  /// The glossary draws one sketch per species — `Scavenger`, `Goblin`,
  /// `Minecrawler` — while a save spawns `Scavenger_Adult`, `Goblin_Black`,
  /// `Minecrawler Nymph`, `MinecrawlerTemple`. Only ~40% of the monsters in a
  /// real save name their species exactly; the rest need matching back to it.
  ///
  /// A species wins when every word of its name appears in the variant's, the
  /// one with the most words first: that is what keeps `LizardFire` on
  /// `FireLizard` rather than on the plain `Lizard` it also contains, and
  /// `Golem_Fire` on `FireGolem` even though the game reversed the words.
  /// Failing that, the longest species the variant starts or ends with, which
  /// catches the ones that respell the species itself (`ShadowBeastCave` for
  /// `Shadowbeast`).
  ///
  /// Only ever a fallback: it must run after the character catalog and the
  /// exact-name probe, or a person named Wolf becomes a wolf.
  String? creatureDocumentFor(String variant) {
    final words = _words(variant);
    if (words.isEmpty) return null;
    _Species? best;
    for (final species in _species) {
      if (!species.words.every(words.contains)) continue;
      if (best == null ||
          species.words.length > best.words.length ||
          (species.words.length == best.words.length &&
              species.folded.length > best.folded.length)) {
        best = species;
      }
    }
    if (best != null) return best.documentClass;
    final folded = _fold(variant);
    for (final species in _species) {
      if (!folded.startsWith(species.folded) &&
          !folded.endsWith(species.folded)) {
        continue;
      }
      if (best == null || species.folded.length > best.folded.length) {
        best = species;
      }
    }
    return best?.documentClass;
  }

  static GlossaryImageCatalog fromJsonString(String json) {
    final decoded = jsonDecode(json);
    if (decoded is! Map) return GlossaryImageCatalog();
    final document = decoded.cast<String, Object?>();
    final raw = document['images'];
    if (raw is! Map) return GlossaryImageCatalog();
    final out = <String, GlossaryImageRef>{};
    raw.forEach((documentClass, entry) {
      if (documentClass is! String || entry is! Map) return;
      final object = entry.cast<String, Object?>();
      final kind = object['kind'] as String? ?? '';
      final name = object['name'] as String? ?? '';
      // A path segment arrives from a bundled asset, but it still ends up in a
      // file path — refuse anything that could climb out of the artwork folder.
      if (!_isPlainSegment(kind) || !_isPlainSegment(name)) return;
      out[documentClass] = GlossaryImageRef(kind: kind, name: name);
    });
    final artwork = <String, GlossaryImageRef>{};
    final rawArtwork = document['artwork'];
    if (rawArtwork is Map) {
      rawArtwork.forEach((name, entry) {
        if (name is! String || entry is! Map) return;
        final kind = entry.cast<String, Object?>()['kind'] as String? ?? '';
        if (!_isPlainSegment(kind) || !_isPlainSegment(name)) return;
        artwork[name] = GlossaryImageRef(kind: kind, name: name);
      });
    }
    return GlossaryImageCatalog(
      Map.unmodifiable(out),
      Map.unmodifiable(artwork),
    );
  }

  static Future<GlossaryImageCatalog> loadBundled() async => fromJsonString(
    await rootBundle.loadString('assets/glossary_images.json'),
  );
}

@immutable
class GlossaryImageRef {
  const GlossaryImageRef({required this.kind, required this.name});

  /// `Characters`, `Creatures` or `Locations`.
  final String kind;

  /// The artwork's own name, e.g. `Diego` — not the document class.
  final String name;
}

/// `Document_Glossary_FireLizard` -> `FireLizard`.
String _documentName(String documentClass) {
  const prefix = 'Document_Glossary_';
  final tail = _classTail(documentClass);
  return tail.startsWith(prefix) ? tail.substring(prefix.length) : tail;
}

/// One creature the glossary draws, indexed by the words of its name.
@immutable
class _Species {
  _Species(this.documentClass, String name)
    : words = _words(name),
      folded = _fold(name);

  final String documentClass;

  /// `FireLizard` -> `{fire, lizard}`.
  final Set<String> words;

  /// `FireLizard` -> `firelizard`.
  final String folded;
}

/// The words of a name, however it spells them: `Minecrawler Nymph`,
/// `MinecrawlerNamed` and `Golem_Fire` all break apart the same way.
Set<String> _words(String value) {
  final spaced = value
      .replaceAll(RegExp('[^A-Za-z0-9]+'), ' ')
      .replaceAllMapped(
        RegExp('([a-z0-9])([A-Z])'),
        (match) => '${match[1]} ${match[2]}',
      )
      .replaceAllMapped(
        RegExp('([A-Z])([A-Z][a-z])'),
        (match) => '${match[1]} ${match[2]}',
      );
  return {
    for (final word in spaced.split(' '))
      if (word.isNotEmpty) word.toLowerCase(),
  };
}

/// Letters and digits only, lowercased.
String _fold(String value) =>
    value.toLowerCase().replaceAll(RegExp('[^a-z0-9]'), '');

/// `/Script/Angelscript.Document_Glossary_X` -> `Document_Glossary_X`.
String _classTail(String documentClass) {
  final trimmed = documentClass.trim();
  final dot = trimmed.lastIndexOf('.');
  return dot < 0 ? trimmed : trimmed.substring(dot + 1);
}

bool _isPlainSegment(String value) =>
    value.isNotEmpty &&
    !value.contains('/') &&
    !value.contains(r'\') &&
    !value.contains('..') &&
    !value.contains(':');
