import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;

/// What the game itself knows about an item, read out of the shipped script
/// cache: its item-type tag, trade value, stack size, damage, stat
/// requirements, equip effect and localized description key.
///
/// Bundled as `assets/item_stats.json`, regenerated by
/// `apps/save-editor/tools/build_item_stats.py` after a game update. Everything
/// here is presentation-only — nothing in it is written back into a save.
@immutable
class ItemStats {
  const ItemStats({
    this.itemType = '',
    this.value,
    this.maxStack,
    this.weight,
    this.superArmorDamage,
    this.magicCircle,
    this.descriptionKey = '',
    this.damage = const {},
    this.requires = const {},
    this.onEquip = const {},
    this.specs = const [],
    this.spellLevels = const [],
    this.spellMana = const [],
    this.onConsume = const [],
    this.teaches = const [],
    this.writing = const [],
    this.ingredientFor = const [],
  });

  factory ItemStats.fromJson(Map<String, Object?> json) {
    return ItemStats(
      itemType: json['itemType'] as String? ?? '',
      value: _number(json['value']),
      maxStack: _number(json['maxStack']),
      weight: _number(json['weight']),
      superArmorDamage: _number(json['superArmorDamage']),
      magicCircle: _number(json['magicCircle']),
      descriptionKey: json['descriptionKey'] as String? ?? '',
      damage: _numbers(json['damage']),
      requires: _numbers(json['requires']),
      onEquip: _numbers(json['onEquip']),
      specs:
          (json['specs'] as List?)?.whereType<String>().toList(
            growable: false,
          ) ??
          const [],
      spellLevels: _levels(json['spellLevels']),
      spellMana: _levels(json['spellMana']),
      onConsume: _effects(json['onConsume']),
      teaches: _recipes(json['teaches']),
      writing: _writing(json['writing']),
      ingredientFor:
          (json['ingredientFor'] as List?)?.whereType<String>().toList(
            growable: false,
          ) ??
          const [],
    );
  }

  /// The `Item_*` GameplayTag the item declares, e.g.
  /// `Item_Weapon_Sword_OneHand`. Empty for the handful of classes that set
  /// none.
  final String itemType;

  /// Base trade value in ore nuggets, before any trader or difficulty factor.
  final num? value;

  /// The stack size the item declares. Carried because the asset carries it;
  /// not shown anywhere — the game has no string for it and never displays it,
  /// and nothing in the editor enforces it.
  final num? maxStack;
  final num? weight;
  final num? superArmorDamage;

  /// Magic circle a rune requires. Mirrored in [requires] as `MagicianLevel`.
  final num? magicCircle;

  /// Loc-catalog id of the flavour text, e.g. `ItAr_Rune_BallLightning_description`.
  final String descriptionKey;

  /// `Item_Damage_*` tag -> base damage.
  final Map<String, num> damage;

  /// Attribute id -> the value needed to use the item (`Strength`, `Dexterity`,
  /// `MagicianLevel`).
  final Map<String, num> requires;

  /// Attribute id -> what wearing this adds (armour protection, ring bonuses).
  final Map<String, num> onEquip;

  /// The item's `Item_Property_*` / `Item_Range_*` / `Food_*` marker tags.
  final List<String> specs;

  /// Per spell level: `Item_Damage_*` tag -> damage. Runes and scrolls only.
  final List<Map<String, num>> spellLevels;

  /// Per spell level: `initialMana`, and `manaPerSecond` for a continuous
  /// spell. Same order and length as [spellLevels].
  final List<Map<String, num>> spellMana;

  /// What eating or drinking the item does — the gameplay effects the item's
  /// own `AddOnConsume` chain names, in the order the game applies them.
  final List<ItemConsumeEffect> onConsume;

  /// The crafting chain a blueprint teaches, in production order: the blank
  /// first, then the rough piece, then the finished weapon. Empty for anything
  /// that is not a blueprint.
  final List<ItemRecipeStep> teaches;

  /// What a book or letter says, in reading order. Two thirds of the writings
  /// carry no description at all — their text IS the item.
  final List<ItemWritingPart> writing;

  /// Item ids this one is an ingredient of. The only useful thing to say about
  /// a lump of iron is what can be made from it.
  final List<String> ingredientFor;

  bool get isEmpty =>
      // A description is content in its own right: two items carry nothing but
      // one, and calling them empty meant hovering them showed no card at all.
      descriptionKey.isEmpty &&
      itemType.isEmpty &&
      value == null &&
      damage.isEmpty &&
      requires.isEmpty &&
      onEquip.isEmpty &&
      onConsume.isEmpty &&
      teaches.isEmpty &&
      writing.isEmpty &&
      ingredientFor.isEmpty &&
      spellLevels.isEmpty;

  static num? _number(Object? value) => value is num ? value : null;

  static Map<String, num> _numbers(Object? value) {
    if (value is! Map) return const {};
    final out = <String, num>{};
    value.forEach((key, entry) {
      if (key is String && entry is num) out[key] = entry;
    });
    return Map.unmodifiable(out);
  }

  static List<ItemWritingPart> _writing(Object? value) {
    if (value is! List) return const [];
    return List.unmodifiable(
      value.whereType<Map>().map(
        (entry) => ItemWritingPart(
          id: entry['id'] as String? ?? '',
          isHeading: entry['kind'] == 'heading',
        ),
      ),
    );
  }

  static List<ItemRecipeStep> _recipes(Object? value) {
    if (value is! List) return const [];
    return List.unmodifiable(
      value.whereType<Map>().map(
        (entry) => ItemRecipeStep(
          station: entry['station'] as String? ?? '',
          needs: _counts(entry['needs']),
          makes: _counts(entry['makes']),
        ),
      ),
    );
  }

  static Map<String, int> _counts(Object? value) {
    if (value is! Map) return const {};
    final out = <String, int>{};
    value.forEach((key, entry) {
      if (key is String && entry is int) out[key] = entry;
    });
    return Map.unmodifiable(out);
  }

  static List<ItemConsumeEffect> _effects(Object? value) {
    if (value is! List) return const [];
    return List.unmodifiable(
      value.whereType<Map>().map(
        (entry) => ItemConsumeEffect(
          effect: entry['effect'] as String? ?? '',
          params: _numbers(entry['params']),
          percent: _numbers(entry['percent']),
        ),
      ),
    );
  }

  static List<Map<String, num>> _levels(Object? value) {
    if (value is! List) return const [];
    return List.unmodifiable(
      value.whereType<Map>().map(
        (entry) => _numbers(entry.cast<String, Object?>()),
      ),
    );
  }
}

/// One gameplay effect an item applies when it is eaten or drunk.
///
/// [effect] is the shipped effect class without its `UGE_Item_` prefix —
/// `Heal_Overtime`, `Strength_Insta`, `Mana_Insta`. An `_Overtime` effect
/// spreads its magnitude over `Duration` seconds; an `_Insta` one applies it at
/// once. [params] holds the magnitudes the item passes in, keyed by the
/// `GE_Param_*` tag without its prefix (`Heal`, `Mana`, `Duration`).
@immutable
class ItemConsumeEffect {
  const ItemConsumeEffect({
    required this.effect,
    this.params = const {},
    this.percent = const {},
  });

  final String effect;
  final Map<String, num> params;

  /// Attribute id -> the FRACTION the effect adds to it, where the effect
  /// raises an attribute by a share of itself rather than by a flat amount
  /// (0.15 is +15%). Declared by the effect class, not by the item.
  final Map<String, num> percent;

  /// Whether the effect spreads over [seconds] rather than landing at once.
  bool get isOverTime => effect.endsWith('_Overtime');

  /// How long an over-time effect lasts, in seconds.
  num? get seconds => params['Duration'];

  /// The magnitudes that are not the duration, i.e. what the effect changes.
  Map<String, num> get magnitudes => {
    for (final entry in params.entries)
      if (entry.key != 'Duration') entry.key: entry.value,
  };
}

/// One step of the crafting chain a blueprint teaches.
///
/// [station] is the bench it is worked at — `forge`, `workbench`, `whetstone`,
/// `inscription`, `alchemy`, `cauldron`. [needs] is what it consumes and
/// [makes] what it yields, both as item id -> count.
@immutable
class ItemRecipeStep {
  const ItemRecipeStep({
    this.station = '',
    this.needs = const {},
    this.makes = const {},
  });

  final String station;
  final Map<String, int> needs;
  final Map<String, int> makes;
}

/// One paragraph or chapter heading of a writing, as a loc-catalog id.
@immutable
class ItemWritingPart {
  const ItemWritingPart({required this.id, this.isHeading = false});

  final String id;
  final bool isHeading;
}

/// One entry of the game's own inventory category rail.
@immutable
class InventoryFilter {
  const InventoryFilter({
    required this.id,
    required this.nameKey,
    required this.icon,
    required this.itemTags,
    required this.sortOrder,
  });

  factory InventoryFilter.fromJson(Map<String, Object?> json) {
    return InventoryFilter(
      id: json['id'] as String? ?? '',
      nameKey: json['nameKey'] as String? ?? '',
      icon: json['icon'] as String? ?? '',
      itemTags:
          (json['itemTags'] as List?)?.whereType<String>().toList(
            growable: false,
          ) ??
          const [],
      sortOrder: (json['sortOrder'] as num?)?.toInt() ?? 1 << 20,
    );
  }

  final String id;

  /// Loc-catalog id of the tab's name (`Text_FilterMelee`).
  final String nameKey;

  /// Shared UI glyph the game puts on the tab (`T_Icon_Melee`).
  final String icon;

  /// Item-type tags this tab collects. GameplayTag matching is hierarchical, so
  /// `Item_Weapon_Rune` also claims `Item_Weapon_Rune_FireBall`.
  final List<String> itemTags;
  final int sortOrder;

  /// The catch-all tab, which lists everything and therefore declares no tags.
  bool get isAll => itemTags.isEmpty;

  bool claims(String itemType) {
    for (final tag in itemTags) {
      if (itemType == tag || itemType.startsWith('${tag}_')) return true;
    }
    return false;
  }
}

/// The bundled item-stats document: the game's inventory filters plus one
/// [ItemStats] per known item id.
@immutable
class ItemStatsCatalog {
  const ItemStatsCatalog({this.filters = const [], this.byItemId = const {}});

  final List<InventoryFilter> filters;
  final Map<String, ItemStats> byItemId;

  /// Case-insensitive lookup; save ids and catalog ids agree on spelling but
  /// not always on case.
  ItemStats? statsFor(String itemId) => byItemId[itemId.trim().toLowerCase()];

  /// The filter the game would file [itemId] under, or null when nothing it
  /// carries belongs to a tab (the game then shows it only under "All").
  ///
  /// A filter that claims one of the item's PROPERTY tags outranks one that
  /// only claims its type. The game marks its forged blanks and heads
  /// `Item_Property_Forge` and the Materials tab claims that tag, but every one
  /// of them still carries a weapon type — so matching on the type alone left
  /// that criterion unreachable and filed seventy-six pieces of smithing stock
  /// under Melee.
  InventoryFilter? filterFor(String itemId) {
    final stats = statsFor(itemId);
    if (stats == null) return null;
    InventoryFilter? byType;
    for (final filter in filters) {
      if (filter.isAll) continue;
      if (stats.specs.any(filter.claims)) return filter;
      if (byType == null &&
          stats.itemType.isNotEmpty &&
          filter.claims(stats.itemType)) {
        byType = filter;
      }
    }
    return byType;
  }

  static ItemStatsCatalog fromJsonString(String json) {
    final decoded = jsonDecode(json);
    if (decoded is! Map) return const ItemStatsCatalog();
    final object = decoded.cast<String, Object?>();
    final filters =
        (object['filters'] as List?)
            ?.whereType<Map>()
            .map((e) => InventoryFilter.fromJson(e.cast<String, Object?>()))
            .where((filter) => filter.id.isNotEmpty)
            .toList()
          ?..sort((a, b) => a.sortOrder.compareTo(b.sortOrder));
    final items = <String, ItemStats>{};
    final rawItems = object['items'];
    if (rawItems is Map) {
      rawItems.forEach((id, entry) {
        if (id is! String || entry is! Map) return;
        items[id.trim().toLowerCase()] = ItemStats.fromJson(
          entry.cast<String, Object?>(),
        );
      });
    }
    return ItemStatsCatalog(
      filters: List.unmodifiable(filters ?? const <InventoryFilter>[]),
      byItemId: Map.unmodifiable(items),
    );
  }

  static Future<ItemStatsCatalog> loadBundled() async =>
      fromJsonString(await rootBundle.loadString('assets/item_stats.json'));
}
