//! Read-only planning of complete trees or explicit overlays against one sealed base cache.
//!
//! Complete-tree planning treats absent base identities as Deletes; explicit overlay planning
//! retains them. Overlay files are always Edits or Adds, even when their bytes match the base.
//! The planner reads all source bytes into the returned value, so compilation never reopens the
//! caller's tree. The explicit overlay route retains absent base modules and never emits original
//! source. Neither route launches the game or mutates the installation.

use std::collections::{BTreeMap, BTreeSet};
use std::io::Read;
use std::path::{Component, Path, PathBuf};

use crate::cache::selective_fullgraph::MAX_SELECTIVE_FULLGRAPH_CHANGES;
use crate::compile::{
    base_full_graph_manifest_v1, FullGraphCompileChangeV1, FullGraphCompileOperationV1,
    FullGraphFinalModuleV1, MAX_FULL_GRAPH_COMPILE_CHANGES_V1, MAX_FULL_GRAPH_FINAL_MODULES_V1,
    MAX_FULL_GRAPH_SOURCE_BYTES_V1,
};

const MAX_FULL_GRAPH_SOURCE_FILE_BYTES_V1: u64 = 16 * 1024 * 1024;
const MAX_FULL_GRAPH_SOURCE_PATH_BYTES_V1: usize = 4 * 1024;

#[derive(Debug)]
pub struct PlannedFullGraphSourceTreeV1 {
    changes: Vec<FullGraphCompileChangeV1>,
    final_manifest: Vec<FullGraphFinalModuleV1>,
}

impl PlannedFullGraphSourceTreeV1 {
    pub fn changes(&self) -> &[FullGraphCompileChangeV1] {
        &self.changes
    }

    pub fn final_manifest(&self) -> &[FullGraphFinalModuleV1] {
        &self.final_manifest
    }

    pub fn into_parts(self) -> (Vec<FullGraphCompileChangeV1>, Vec<FullGraphFinalModuleV1>) {
        (self.changes, self.final_manifest)
    }
}

#[derive(Debug)]
struct AuthoredSourceV1 {
    module_name: String,
    relative_path: String,
    bytes: Vec<u8>,
}

/// Build an exact Add/Edit/Delete plan for `source_root` without writing anywhere.
pub fn plan_complete_source_tree_v1(
    base_cache: &[u8],
    source_root: &Path,
) -> Result<PlannedFullGraphSourceTreeV1, FullGraphSourcePlanErrorV1> {
    let base = base_full_graph_manifest_v1(base_cache)
        .map_err(|error| FullGraphSourcePlanErrorV1::BaseCache(error.to_string()))?
        .into_iter()
        .map(|entry| (entry.module_name, entry.relative_path))
        .collect::<Vec<_>>();
    let sources = collect_authored_sources(source_root)?;
    plan_inventory(base, sources)
}

/// Plan a sparse directory of authored Add/Edit sources. Every supplied `.as` file is an explicit
/// change; absent base modules remain Base. No emitter or Binds input is needed to discover changes.
/// As with complete-tree planning, source paths are canonical and the returned bytes are owned:
/// subsequent edits to the caller's directory cannot alter this plan.
pub fn plan_source_overlays_v1(
    base_cache: &[u8],
    source_root: &Path,
) -> Result<PlannedFullGraphSourceTreeV1, FullGraphSourcePlanErrorV1> {
    let base = base_full_graph_manifest_v1(base_cache)
        .map_err(|error| FullGraphSourcePlanErrorV1::BaseCache(error.to_string()))?
        .into_iter()
        .map(|entry| (entry.module_name, entry.relative_path))
        .collect::<Vec<_>>();
    let sources = collect_authored_sources_bounded(source_root, MAX_SELECTIVE_FULLGRAPH_CHANGES)?;
    plan_inventory_with_missing(base, sources, true, |_| Ok(false))
}

/// Build an Add/Edit/Delete plan while recognizing source files which are byte-identical to the
/// current emitter's compiler-ready representation of their sealed base module.
///
/// The complete-tree CLI is normally fed by `gore as emit-all`. Without this comparison every
/// one of those untouched files is classified as an Edit merely because it is present in the
/// authoritative tree. That defeats selective FullGraph publication: a no-op roundtrip would
/// replace every pristine module with regenerated bytes. Exact bytes are deliberately required;
/// formatting, comments, line endings, or any other authored difference remain an Edit.
pub fn plan_complete_source_tree_with_emitted_base_v1(
    base_cache: &[u8],
    binds_cache: &[u8],
    source_root: &Path,
) -> Result<PlannedFullGraphSourceTreeV1, FullGraphSourcePlanErrorV1> {
    let base = base_full_graph_manifest_v1(base_cache)
        .map_err(|error| FullGraphSourcePlanErrorV1::BaseCache(error.to_string()))?
        .into_iter()
        .map(|entry| (entry.module_name, entry.relative_path))
        .collect::<Vec<_>>();
    let sources = collect_authored_sources(source_root)?;

    let modules = crate::cache::model::parse_modules(base_cache)
        .map_err(|error| FullGraphSourcePlanErrorV1::EmittedBase(error.to_string()))?;
    let mut refs = crate::cache::refs::RefResolver::build(base_cache)
        .map_err(|error| FullGraphSourcePlanErrorV1::EmittedBase(error.to_string()))?;
    let native = crate::cache::binds::NativeApi::from_bytes(binds_cache).ok_or_else(|| {
        FullGraphSourcePlanErrorV1::EmittedBase("sealed Binds.Cache is invalid".to_owned())
    })?;
    let prepared = crate::cache::emit_all::PreparedEmit::new(&modules, &mut refs, Some(native))
        .map_err(|error| FullGraphSourcePlanErrorV1::EmittedBase(error.to_string()))?
        .with_class_defaults(true);
    let module_indices = modules
        .iter()
        .enumerate()
        .map(|(index, module)| (fold(&module.name), index))
        .collect::<BTreeMap<_, _>>();

    plan_inventory_with_unchanged(base, sources, |source| {
        let Some(&index) = module_indices.get(&fold(&source.module_name)) else {
            return Ok(false);
        };
        if prepared.module_relative_path(index) != Some(source.relative_path.as_str()) {
            return Ok(false);
        }
        prepared
            .emit_module(index)
            .map(|emitted| emitted.as_bytes() == source.bytes)
            .map_err(|error| FullGraphSourcePlanErrorV1::EmittedBase(error.to_string()))
    })
}

fn plan_inventory(
    base: Vec<(String, String)>,
    sources: Vec<AuthoredSourceV1>,
) -> Result<PlannedFullGraphSourceTreeV1, FullGraphSourcePlanErrorV1> {
    plan_inventory_with_unchanged(base, sources, |_| Ok(false))
}

fn plan_inventory_with_unchanged(
    base: Vec<(String, String)>,
    sources: Vec<AuthoredSourceV1>,
    is_unchanged: impl FnMut(&AuthoredSourceV1) -> Result<bool, FullGraphSourcePlanErrorV1>,
) -> Result<PlannedFullGraphSourceTreeV1, FullGraphSourcePlanErrorV1> {
    plan_inventory_with_missing(base, sources, false, is_unchanged)
}

fn plan_inventory_with_missing(
    base: Vec<(String, String)>,
    mut sources: Vec<AuthoredSourceV1>,
    retain_missing: bool,
    mut is_unchanged: impl FnMut(&AuthoredSourceV1) -> Result<bool, FullGraphSourcePlanErrorV1>,
) -> Result<PlannedFullGraphSourceTreeV1, FullGraphSourcePlanErrorV1> {
    if sources.is_empty() {
        return Err(FullGraphSourcePlanErrorV1::EmptySourceTree);
    }
    if retain_missing && sources.len() > MAX_SELECTIVE_FULLGRAPH_CHANGES {
        return Err(FullGraphSourcePlanErrorV1::TooManySourceModules {
            actual: sources.len(),
            max: MAX_SELECTIVE_FULLGRAPH_CHANGES,
        });
    }
    sources.sort_by(|left, right| {
        canonical_identity(&left.module_name, &left.relative_path).cmp(&canonical_identity(
            &right.module_name,
            &right.relative_path,
        ))
    });
    let mut base_by_name = BTreeMap::new();
    for (module_name, relative_path) in base {
        if base_by_name
            .insert(fold(&module_name), (module_name, relative_path))
            .is_some()
        {
            return Err(FullGraphSourcePlanErrorV1::BaseCache(
                "base cache contains case-colliding module names".into(),
            ));
        }
    }

    let mut seen_names = BTreeSet::new();
    let mut seen_paths = BTreeSet::new();
    let mut final_manifest = Vec::with_capacity(sources.len());
    let mut changes = Vec::with_capacity(sources.len().saturating_add(base_by_name.len()));
    for source in sources {
        if !seen_names.insert(fold(&source.module_name))
            || !seen_paths.insert(fold(&source.relative_path))
        {
            return Err(FullGraphSourcePlanErrorV1::IdentityCollision {
                module_name: source.module_name,
                relative_path: source.relative_path,
            });
        }
        let operation = match base_by_name.remove(&fold(&source.module_name)) {
            Some((base_name, base_path)) => {
                if base_name != source.module_name || base_path != source.relative_path {
                    return Err(FullGraphSourcePlanErrorV1::BaseIdentityMismatch {
                        source_module: source.module_name,
                        source_path: source.relative_path,
                        base_module: base_name,
                        base_path,
                    });
                }
                (!is_unchanged(&source)?).then_some(FullGraphCompileOperationV1::Edit)
            }
            None => Some(FullGraphCompileOperationV1::Add),
        };
        final_manifest.push(FullGraphFinalModuleV1 {
            module_name: source.module_name.clone(),
            relative_path: source.relative_path.clone(),
        });
        if let Some(operation) = operation {
            changes.push(FullGraphCompileChangeV1 {
                operation,
                module_name: source.module_name,
                relative_path: source.relative_path,
                source: Some(source.bytes),
            });
        }
    }

    for (_, (module_name, relative_path)) in base_by_name {
        if retain_missing {
            final_manifest.push(FullGraphFinalModuleV1 { module_name, relative_path });
        } else {
            changes.push(FullGraphCompileChangeV1 {
                operation: FullGraphCompileOperationV1::Delete,
                module_name,
                relative_path,
                source: None,
            });
        }
    }
    final_manifest.sort_by_key(|entry| canonical_identity(&entry.module_name, &entry.relative_path));
    changes.sort_by(|left, right| {
        canonical_identity(&left.module_name, &left.relative_path).cmp(&canonical_identity(
            &right.module_name,
            &right.relative_path,
        ))
    });
    if changes.len() > MAX_FULL_GRAPH_COMPILE_CHANGES_V1
        || final_manifest.len() > MAX_FULL_GRAPH_FINAL_MODULES_V1
    {
        return Err(FullGraphSourcePlanErrorV1::TooManyModules {
            changes: changes.len(),
            final_modules: final_manifest.len(),
        });
    }
    Ok(PlannedFullGraphSourceTreeV1 {
        changes,
        final_manifest,
    })
}

fn collect_authored_sources(
    root: &Path,
) -> Result<Vec<AuthoredSourceV1>, FullGraphSourcePlanErrorV1> {
    collect_authored_sources_bounded(root, MAX_FULL_GRAPH_FINAL_MODULES_V1)
}

fn collect_authored_sources_bounded(
    root: &Path,
    max_modules: usize,
) -> Result<Vec<AuthoredSourceV1>, FullGraphSourcePlanErrorV1> {
    if !root.is_absolute() {
        return Err(FullGraphSourcePlanErrorV1::UnsafeRoot);
    }
    let mut directory_pins = Vec::new();
    directory_pins.push(open_directory_pin(root)?);
    let mut pending = vec![PathBuf::new()];
    let mut paths = Vec::new();
    while let Some(relative_directory) = pending.pop() {
        let directory = root.join(&relative_directory);
        let mut entries = std::fs::read_dir(&directory)
            .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?
            .collect::<Result<Vec<_>, _>>()
            .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?;
        entries.sort_by_key(std::fs::DirEntry::file_name);
        for entry in entries.into_iter().rev() {
            let relative = relative_directory.join(entry.file_name());
            let metadata = std::fs::symlink_metadata(entry.path())
                .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?;
            if metadata.file_type().is_symlink() || metadata_is_reparse(&metadata) {
                return Err(FullGraphSourcePlanErrorV1::UnsafeEntry(relative));
            }
            if metadata.is_dir() {
                directory_pins.push(open_directory_pin(&entry.path())?);
                pending.push(relative);
            } else if metadata.is_file() {
                if is_angelscript_path(&relative) {
                    paths.push(relative);
                    if paths.len() > max_modules {
                        return Err(FullGraphSourcePlanErrorV1::TooManySourceModules {
                            actual: paths.len(),
                            max: max_modules,
                        });
                    }
                }
            } else {
                return Err(FullGraphSourcePlanErrorV1::UnsafeEntry(relative));
            }
        }
    }
    let mut normalized_paths = paths
        .into_iter()
        .map(|path| {
            let normalized = path_to_slashes(&path)?;
            Ok((path, normalized))
        })
        .collect::<Result<Vec<_>, FullGraphSourcePlanErrorV1>>()?;
    normalized_paths.sort_by(|left, right| left.1.cmp(&right.1));

    let mut total = 0u64;
    let mut sources = Vec::with_capacity(normalized_paths.len());
    for (relative, relative_path) in normalized_paths {
        validate_relative_path(&relative_path)?;
        let mut file = open_source_pin(&root.join(&relative))?;
        let metadata = file
            .metadata()
            .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?;
        if metadata.len() > MAX_FULL_GRAPH_SOURCE_FILE_BYTES_V1 {
            return Err(FullGraphSourcePlanErrorV1::SourceTooLarge {
                path: relative,
                actual: metadata.len(),
                max: MAX_FULL_GRAPH_SOURCE_FILE_BYTES_V1,
            });
        }
        let mut bytes = Vec::with_capacity(metadata.len() as usize);
        (&mut file)
            .take(MAX_FULL_GRAPH_SOURCE_FILE_BYTES_V1 + 1)
            .read_to_end(&mut bytes)
            .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?;
        if bytes.len() as u64 != metadata.len() {
            return Err(FullGraphSourcePlanErrorV1::SourceChanged(relative));
        }
        total = total.checked_add(bytes.len() as u64).ok_or(
            FullGraphSourcePlanErrorV1::AggregateTooLarge {
                actual: u64::MAX,
                max: MAX_FULL_GRAPH_SOURCE_BYTES_V1 as u64,
            },
        )?;
        if total > MAX_FULL_GRAPH_SOURCE_BYTES_V1 as u64 {
            return Err(FullGraphSourcePlanErrorV1::AggregateTooLarge {
                actual: total,
                max: MAX_FULL_GRAPH_SOURCE_BYTES_V1 as u64,
            });
        }
        std::str::from_utf8(&bytes)
            .map_err(|_| FullGraphSourcePlanErrorV1::InvalidUtf8(relative.clone()))?;
        if bytes.contains(&0) {
            return Err(FullGraphSourcePlanErrorV1::NulSource(relative));
        }
        sources.push(AuthoredSourceV1 {
            module_name: module_name_from_relative_path_v1(&relative_path)?,
            relative_path,
            bytes,
        });
    }
    drop(directory_pins);
    Ok(sources)
}

/// Applies the exact donor module-name rule after enforcing this planner's path policy.
pub fn module_name_from_relative_path_v1(
    relative_path: &str,
) -> Result<String, FullGraphSourcePlanErrorV1> {
    validate_relative_path(relative_path)?;
    let (module_name, normalized_path) =
        crate::compile::module_name_from_relative_path_v1(relative_path)
            .map_err(|error| FullGraphSourcePlanErrorV1::InvalidModuleName(error.to_string()))?;
    if normalized_path != relative_path {
        return Err(FullGraphSourcePlanErrorV1::UnsafeRelativePath(
            relative_path.into(),
        ));
    }
    Ok(module_name)
}

fn validate_relative_path(value: &str) -> Result<(), FullGraphSourcePlanErrorV1> {
    if value.is_empty()
        || value.len() > MAX_FULL_GRAPH_SOURCE_PATH_BYTES_V1
        || value.contains('\\')
        || value.contains(':')
        || value.contains('\0')
        || value.chars().any(char::is_control)
    {
        return Err(FullGraphSourcePlanErrorV1::UnsafeRelativePath(value.into()));
    }
    let path = Path::new(value);
    if path.is_absolute()
        || path
            .components()
            .any(|component| !matches!(component, Component::Normal(_)))
        || value.split('/').any(|component| {
            component.is_empty()
                || component.ends_with([' ', '.'])
                || component
                    .chars()
                    .any(|character| matches!(character, '<' | '>' | '"' | '|' | '?' | '*'))
                || windows_reserved_component(component)
        })
    {
        return Err(FullGraphSourcePlanErrorV1::UnsafeRelativePath(value.into()));
    }
    Ok(())
}

fn windows_reserved_component(component: &str) -> bool {
    let stem = component.split('.').next().unwrap_or(component);
    let upper = stem.to_ascii_uppercase();
    matches!(upper.as_str(), "CON" | "PRN" | "AUX" | "NUL")
        || upper
            .strip_prefix("COM")
            .or_else(|| upper.strip_prefix("LPT"))
            .is_some_and(|suffix| suffix.len() == 1 && matches!(suffix.as_bytes()[0], b'1'..=b'9'))
}

fn is_angelscript_path(path: &Path) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| extension.eq_ignore_ascii_case("as"))
}

fn path_to_slashes(path: &Path) -> Result<String, FullGraphSourcePlanErrorV1> {
    path.components()
        .map(|component| match component {
            Component::Normal(value) => value
                .to_str()
                .map(str::to_owned)
                .ok_or_else(|| FullGraphSourcePlanErrorV1::UnsafeEntry(path.to_path_buf())),
            _ => Err(FullGraphSourcePlanErrorV1::UnsafeEntry(path.to_path_buf())),
        })
        .collect::<Result<Vec<_>, _>>()
        .map(|components| components.join("/"))
}

fn canonical_identity(module_name: &str, relative_path: &str) -> (String, String, String, String) {
    (
        fold(module_name),
        fold(relative_path),
        module_name.to_owned(),
        relative_path.to_owned(),
    )
}

fn fold(value: &str) -> String {
    value.chars().flat_map(char::to_lowercase).collect()
}

#[cfg(windows)]
fn open_directory_pin(path: &Path) -> Result<std::fs::File, FullGraphSourcePlanErrorV1> {
    use std::os::windows::fs::OpenOptionsExt as _;
    use windows_sys::Win32::Storage::FileSystem::{
        FILE_FLAG_BACKUP_SEMANTICS, FILE_FLAG_OPEN_REPARSE_POINT, FILE_GENERIC_READ,
        FILE_SHARE_READ,
    };

    let mut options = std::fs::OpenOptions::new();
    options
        .access_mode(FILE_GENERIC_READ)
        .share_mode(FILE_SHARE_READ)
        .custom_flags(FILE_FLAG_BACKUP_SEMANTICS | FILE_FLAG_OPEN_REPARSE_POINT);
    let file = options
        .open(path)
        .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?;
    let metadata = file
        .metadata()
        .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?;
    if !metadata.is_dir() || metadata_is_reparse(&metadata) {
        return Err(FullGraphSourcePlanErrorV1::UnsafeRoot);
    }
    Ok(file)
}

#[cfg(not(windows))]
fn open_directory_pin(path: &Path) -> Result<std::fs::File, FullGraphSourcePlanErrorV1> {
    let metadata = std::fs::symlink_metadata(path)
        .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?;
    if !metadata.is_dir() || metadata.file_type().is_symlink() {
        return Err(FullGraphSourcePlanErrorV1::UnsafeRoot);
    }
    std::fs::File::open(path).map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))
}

#[cfg(windows)]
fn open_source_pin(path: &Path) -> Result<std::fs::File, FullGraphSourcePlanErrorV1> {
    use std::os::windows::fs::OpenOptionsExt as _;
    use windows_sys::Win32::Storage::FileSystem::{
        FILE_FLAG_OPEN_REPARSE_POINT, FILE_GENERIC_READ, FILE_SHARE_READ,
    };
    let mut options = std::fs::OpenOptions::new();
    options
        .access_mode(FILE_GENERIC_READ)
        .share_mode(FILE_SHARE_READ)
        .custom_flags(FILE_FLAG_OPEN_REPARSE_POINT);
    let file = options
        .open(path)
        .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?;
    let metadata = file
        .metadata()
        .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?;
    if !metadata.is_file() || metadata_is_reparse(&metadata) {
        return Err(FullGraphSourcePlanErrorV1::UnsafeEntry(path.to_path_buf()));
    }
    Ok(file)
}

#[cfg(unix)]
fn open_source_pin(path: &Path) -> Result<std::fs::File, FullGraphSourcePlanErrorV1> {
    use std::os::unix::fs::OpenOptionsExt as _;
    let mut options = std::fs::OpenOptions::new();
    options
        .read(true)
        .custom_flags(libc::O_CLOEXEC | libc::O_NOFOLLOW);
    let file = options
        .open(path)
        .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?;
    if !file
        .metadata()
        .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?
        .is_file()
    {
        return Err(FullGraphSourcePlanErrorV1::UnsafeEntry(path.to_path_buf()));
    }
    Ok(file)
}

#[cfg(not(any(windows, unix)))]
fn open_source_pin(path: &Path) -> Result<std::fs::File, FullGraphSourcePlanErrorV1> {
    let metadata = std::fs::symlink_metadata(path)
        .map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))?;
    if !metadata.is_file() || metadata.file_type().is_symlink() {
        return Err(FullGraphSourcePlanErrorV1::UnsafeEntry(path.to_path_buf()));
    }
    std::fs::File::open(path).map_err(|error| FullGraphSourcePlanErrorV1::Io(error.to_string()))
}

#[cfg(windows)]
fn metadata_is_reparse(metadata: &std::fs::Metadata) -> bool {
    use std::os::windows::fs::MetadataExt as _;
    use windows_sys::Win32::Storage::FileSystem::FILE_ATTRIBUTE_REPARSE_POINT;
    metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0
}

#[cfg(not(windows))]
fn metadata_is_reparse(_: &std::fs::Metadata) -> bool {
    false
}

#[derive(Debug, thiserror::Error)]
pub enum FullGraphSourcePlanErrorV1 {
    #[error("base cache cannot supply a canonical module manifest: {0}")]
    BaseCache(String),
    #[error("base cache cannot supply an exact current emitted-source baseline: {0}")]
    EmittedBase(String),
    #[error("full-graph source root must be an absolute real directory")]
    UnsafeRoot,
    #[error("full-graph source tree contains an unsafe entry at {0}")]
    UnsafeEntry(PathBuf),
    #[error("full-graph source path is unsafe: {0:?}")]
    UnsafeRelativePath(String),
    #[error("full-graph source tree contains no .as modules")]
    EmptySourceTree,
    #[error("source directory has {actual} authored modules; maximum is {max}")]
    TooManySourceModules { actual: usize, max: usize },
    #[error("full-graph source tree has {changes} changes and {final_modules} final modules")]
    TooManyModules {
        changes: usize,
        final_modules: usize,
    },
    #[error("full-graph source {path:?} is {actual} bytes; maximum is {max}")]
    SourceTooLarge {
        path: PathBuf,
        actual: u64,
        max: u64,
    },
    #[error("full-graph source aggregate is {actual} bytes; maximum is {max}")]
    AggregateTooLarge { actual: u64, max: u64 },
    #[error("full-graph source changed while it was read: {0}")]
    SourceChanged(PathBuf),
    #[error("full-graph source is not canonical UTF-8: {0}")]
    InvalidUtf8(PathBuf),
    #[error("full-graph source contains NUL: {0}")]
    NulSource(PathBuf),
    #[error("relative path derives an invalid module name: {0:?}")]
    InvalidModuleName(String),
    #[error("full-graph source identities collide at {module_name:?}/{relative_path:?}")]
    IdentityCollision {
        module_name: String,
        relative_path: String,
    },
    #[error(
        "source identity {source_module:?}/{source_path:?} does not exactly match base identity {base_module:?}/{base_path:?}"
    )]
    BaseIdentityMismatch {
        source_module: String,
        source_path: String,
        base_module: String,
        base_path: String,
    },
    #[error("reading full-graph source tree: {0}")]
    Io(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    fn source(path: &str, bytes: &[u8]) -> AuthoredSourceV1 {
        AuthoredSourceV1 {
            module_name: module_name_from_relative_path_v1(path).unwrap(),
            relative_path: path.into(),
            bytes: bytes.into(),
        }
    }

    #[test]
    fn donor_names_and_complete_add_edit_delete_plan_are_exact() {
        assert_eq!(
            module_name_from_relative_path_v1("AI/Foo.as.generated.as").unwrap(),
            "AI.Foo.generated"
        );
        let planned = plan_inventory(
            vec![
                ("AI.Foo".into(), "AI/Foo.as".into()),
                ("Old".into(), "Old.as".into()),
            ],
            vec![source("AI/Foo.as", b"edit"), source("New.as", b"add")],
        )
        .unwrap();
        assert_eq!(planned.final_manifest.len(), 2);
        assert_eq!(planned.changes.len(), 3);
        assert!(planned.changes.iter().any(|change| {
            change.module_name == "AI.Foo" && change.operation == FullGraphCompileOperationV1::Edit
        }));
        assert!(planned.changes.iter().any(|change| {
            change.module_name == "New" && change.operation == FullGraphCompileOperationV1::Add
        }));
        assert!(planned.changes.iter().any(|change| {
            change.module_name == "Old"
                && change.operation == FullGraphCompileOperationV1::Delete
                && change.source.is_none()
        }));
    }

    #[test]
    fn case_or_path_drift_is_never_reclassified_as_an_edit() {
        let error = plan_inventory(
            vec![("AI.Foo".into(), "AI/Foo.as".into())],
            vec![source("ai/foo.as", b"drift")],
        )
        .unwrap_err();
        assert!(matches!(
            error,
            FullGraphSourcePlanErrorV1::BaseIdentityMismatch { .. }
        ));
    }

    #[test]
    fn sparse_changes_retain_the_entire_unprovided_base_without_emission() {
        let base = (0..7317).map(|i| (format!("Base.M{i}"), format!("Base/M{i}.as"))).collect::<Vec<_>>();
        let planned = plan_inventory_with_missing(
            base.clone(),
            vec![source("New/Provider.as", b"int Answer() { return 42; }"),
                 source("Base/M5.as", b"int Consumer() { return Answer(); }")],
            true,
            |_| Ok(false),
        ).unwrap();
        assert_eq!(planned.final_manifest.len(), base.len() + 1);
        assert_eq!(planned.changes.len(), 2);
        assert!(planned.changes.iter().all(|change| change.operation != FullGraphCompileOperationV1::Delete));
        assert!(planned.changes.iter().any(|change| change.module_name == "Base.M5" && change.operation == FullGraphCompileOperationV1::Edit));
        assert!(planned.changes.iter().any(|change| change.module_name == "New.Provider" && change.operation == FullGraphCompileOperationV1::Add));
        for (name, path) in base {
            assert!(planned.final_manifest.iter().any(|entry| entry.module_name == name && entry.relative_path == path));
        }
    }

    #[test]
    fn sparse_identity_drift_collisions_empty_and_overlarge_inputs_fail_closed() {
        for sources in [vec![source("base/Foo.as", b"drift")],
                        vec![source("Base/Foo.as.generated.as", b"wrong path")]] {
            let base_name = sources[0].module_name.to_lowercase();
            let base = if base_name.ends_with("generated") {
                vec![("Base.Foo.generated".into(), "Base/Foo/generated.as".into())]
            } else { vec![("Base.Foo".into(), "Base/Foo.as".into())] };
            assert!(matches!(plan_inventory_with_missing(base, sources, true, |_| Ok(false)),
                Err(FullGraphSourcePlanErrorV1::BaseIdentityMismatch { .. })));
        }
        assert!(matches!(plan_inventory_with_missing(vec![], vec![source("New.as", b"a"), source("new.as", b"b")], true, |_| Ok(false)),
            Err(FullGraphSourcePlanErrorV1::IdentityCollision { .. })));
        assert!(matches!(plan_inventory_with_missing(vec![], vec![], true, |_| Ok(false)),
            Err(FullGraphSourcePlanErrorV1::EmptySourceTree)));
        let too_many = (0..=MAX_SELECTIVE_FULLGRAPH_CHANGES).map(|i| source(&format!("M{i}.as"), b"change")).collect();
        assert!(matches!(plan_inventory_with_missing(vec![], too_many, true, |_| Ok(false)),
            Err(FullGraphSourcePlanErrorV1::TooManySourceModules { actual: 257, max: 256 })));
    }

    #[test]
    fn sparse_discovery_rejects_257_modules_before_reading_source_contents() {
        let dir = tempfile::tempdir().unwrap();
        for index in 0..=MAX_SELECTIVE_FULLGRAPH_CHANGES {
            std::fs::write(dir.path().join(format!("M{index}.as")), [0xff]).unwrap();
        }
        assert!(matches!(plan_source_overlays_v1(&minimal_base(), dir.path()),
            Err(FullGraphSourcePlanErrorV1::TooManySourceModules { actual: 257, max: 256 })));
    }

    fn minimal_base() -> Vec<u8> {
        fn string(bytes: &mut Vec<u8>, value: &str, includes_nul: bool) {
            bytes.extend_from_slice(&((value.len() + usize::from(includes_nul)) as i32).to_le_bytes());
            bytes.extend_from_slice(value.as_bytes());
            bytes.push(0);
        }
        let mut bytes = vec![0x11; 16];
        bytes.extend_from_slice(&crate::cache::header::CACHE_MAGIC.to_le_bytes());
        bytes.extend_from_slice(&1i32.to_le_bytes());
        string(&mut bytes, "Base", true);
        string(&mut bytes, "Base", false);
        bytes.extend_from_slice(&[0; 44]); // five arrays, code hash, imports, statics, events, delegates
        string(&mut bytes, "Base.as", false);
        bytes.extend_from_slice(&0i32.to_le_bytes()); // post-init functions
        bytes.extend_from_slice(&[0; crate::cache::tables::N_TABLES * 4]);
        bytes
    }

    #[test]
    fn sparse_public_planner_owns_source_bytes_and_needs_no_original_source_or_binds() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir(dir.path().join("New")).unwrap();
        let path = dir.path().join("New/Provider.as");
        std::fs::write(&path, b"int Answer() { return 42; }").unwrap();
        let plan = plan_source_overlays_v1(&minimal_base(), dir.path()).unwrap();
        std::fs::write(&path, b"int Answer() { return 99; }").unwrap();
        assert_eq!(plan.changes[0].source.as_deref(), Some(b"int Answer() { return 42; }".as_slice()));
        assert_eq!(plan.changes[0].module_name, "New.Provider");
        assert_eq!(plan.changes[0].operation, FullGraphCompileOperationV1::Add);
    }

    #[test]
    fn sparse_reader_rejects_malformed_and_oversized_sources() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("Bad.as");
        std::fs::write(&path, [0xff]).unwrap();
        assert!(matches!(plan_source_overlays_v1(&minimal_base(), dir.path()), Err(FullGraphSourcePlanErrorV1::InvalidUtf8(_))));
        std::fs::write(&path, b"int x;\0").unwrap();
        assert!(matches!(plan_source_overlays_v1(&minimal_base(), dir.path()), Err(FullGraphSourcePlanErrorV1::NulSource(_))));
        std::fs::File::create(&path).unwrap().set_len(MAX_FULL_GRAPH_SOURCE_FILE_BYTES_V1 + 1).unwrap();
        assert!(matches!(plan_source_overlays_v1(&minimal_base(), dir.path()), Err(FullGraphSourcePlanErrorV1::SourceTooLarge { .. })));
    }

    #[cfg(unix)]
    #[test]
    fn sparse_reader_rejects_linked_sources_and_directories() {
        use std::os::unix::fs::symlink;
        let dir = tempfile::tempdir().unwrap();
        let outside = tempfile::tempdir().unwrap();
        let target = outside.path().join("Real.as");
        std::fs::write(&target, b"int x;").unwrap();
        let link = dir.path().join("Link.as");
        symlink(&target, &link).unwrap();
        assert!(matches!(plan_source_overlays_v1(&minimal_base(), dir.path()), Err(FullGraphSourcePlanErrorV1::UnsafeEntry(_))));
        std::fs::remove_file(&link).unwrap();
        symlink(outside.path(), dir.path().join("Nested")).unwrap();
        assert!(matches!(plan_source_overlays_v1(&minimal_base(), dir.path()), Err(FullGraphSourcePlanErrorV1::UnsafeEntry(_))));
    }

    #[test]
    fn exact_emitted_source_is_base_while_real_differences_remain_changes() {
        let planned = plan_inventory_with_unchanged(
            vec![
                ("Same".into(), "Same.as".into()),
                ("Changed".into(), "Changed.as".into()),
                ("Deleted".into(), "Deleted.as".into()),
            ],
            vec![source("Same.as", b"same"), source("Changed.as", b"edit")],
            |source| Ok(source.module_name == "Same" && source.bytes == b"same"),
        )
        .unwrap();

        assert_eq!(planned.final_manifest.len(), 2);
        assert_eq!(planned.changes.len(), 2);
        assert!(
            !planned
                .changes
                .iter()
                .any(|change| change.module_name == "Same")
        );
        assert!(planned.changes.iter().any(|change| {
            change.module_name == "Changed" && change.operation == FullGraphCompileOperationV1::Edit
        }));
        assert!(planned.changes.iter().any(|change| {
            change.module_name == "Deleted"
                && change.operation == FullGraphCompileOperationV1::Delete
        }));
    }

    #[test]
    #[ignore = "requires GORE_AS_CACHE, GORE_AS_BINDS, and GORE_AS_FULL_SOURCE_TREE fixtures"]
    fn real_emitted_tree_plans_only_the_authored_cross_module_delta() {
        let base = std::fs::read(std::env::var_os("GORE_AS_CACHE").expect("set GORE_AS_CACHE"))
            .unwrap();
        let binds = std::fs::read(std::env::var_os("GORE_AS_BINDS").expect("set GORE_AS_BINDS"))
            .unwrap();
        let source_root =
            PathBuf::from(std::env::var_os("GORE_AS_FULL_SOURCE_TREE").expect("set source tree"));
        let planned =
            plan_complete_source_tree_with_emitted_base_v1(&base, &binds, &source_root).unwrap();
        assert_eq!(planned.final_manifest().len(), 7_318);
        assert_eq!(
            planned
                .changes()
                .iter()
                .map(|change| (change.operation, change.module_name.as_str()))
                .collect::<Vec<_>>(),
            [
                (
                    FullGraphCompileOperationV1::Add,
                    "Gore.FullGraph.DiegoProbe"
                ),
                (
                    FullGraphCompileOperationV1::Edit,
                    "Story.G1R.Conversation.Conversation_OC_STT_DIEGO"
                ),
            ]
        );
    }
}
