[package]
name = "gore-mod"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gore-modgen = { path = "../gore-modgen" }
gore-loc = { path = "../gore-loc" }
gore-fmod = { path = "../gore-fmod" }
gore-tex = { path = "../gore-tex" }
gore-as = { path = "../gore-as" }
image = "0.25"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[dev-dependencies]
tempfile = "3"
